// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:3d102b7bcecbf18e72b655745e5c55d641457fab2fd8184b3da643aeb51bb76f
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code AccountCashFlowClassification} values.
 *
 * <p>Known values of an open set. The API may return values not listed here; treat unknown values as valid.
 */
public final class AccountCashFlowClassification {
    private AccountCashFlowClassification() {}

    /** {@code none} */
    public static final String NONE = "none";

    /** {@code operating} */
    public static final String OPERATING = "operating";

    /** {@code investing} */
    public static final String INVESTING = "investing";

    /** {@code financing} */
    public static final String FINANCING = "financing";

    /** {@code not_applicable} */
    public static final String NOT_APPLICABLE = "not_applicable";
}
