// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:09aa9517f466027d023798abdf939204d057d808cb4eb15566deed6b960adcec
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code AccountsToInclude} values.
 *
 * <p>Allowed values.
 */
public final class AccountsToInclude {
    private AccountsToInclude() {}

    /** {@code all} */
    public static final String ALL = "all";

    /** {@code in_use} */
    public static final String IN_USE = "in_use";
}
