// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:6f5ac28d7c33ac90aa7e2c15d88efd50e8e41c808bcc5489f0c8b1cb7833326a
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code AccountCashFlowClassification} values.
 *
 * <p>Known values of an open set. The API may return values not listed here; treat unknown values as valid.
 */
public final class AccountCashFlowClassification {
    private AccountCashFlowClassification() {}

    /** {@code none} */
    public static final String NONE = "none";

    /** {@code operating} */
    public static final String OPERATING = "operating";

    /** {@code investing} */
    public static final String INVESTING = "investing";

    /** {@code financing} */
    public static final String FINANCING = "financing";

    /** {@code not_applicable} */
    public static final String NOT_APPLICABLE = "not_applicable";
}
