// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:3d102b7bcecbf18e72b655745e5c55d641457fab2fd8184b3da643aeb51bb76f
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code AccountsToInclude} values.
 *
 * <p>Allowed values.
 */
public final class AccountsToInclude {
    private AccountsToInclude() {}

    /** {@code all} */
    public static final String ALL = "all";

    /** {@code in_use} */
    public static final String IN_USE = "in_use";
}
