// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:3d102b7bcecbf18e72b655745e5c55d641457fab2fd8184b3da643aeb51bb76f
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.Json;
import com.desktopaccountingapi.quickbooksdesktop.core.JsonWritable;
import com.desktopaccountingapi.quickbooksdesktop.core.Wire;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;

/**
 * Account tax line as stored in QuickBooks Desktop.
 *
 * <p>Parsed tolerantly: unknown members go to {@link #additionalProperties()} and missing members read as null. {@link #toJson()} writes the wire form back.
 */
public final class AccountTaxLine implements JsonWritable {
    private static final Set<String> KNOWN = new HashSet<>(Arrays.asList("objectType", "taxLineId", "taxLineName"));

    private String objectType;
    private Integer taxLineId;
    private String taxLineName;
    private Map<String, Object> additionalProperties = Collections.emptyMap();

    private AccountTaxLine() {}

    /**
     * Reads the object from parsed JSON (see {@code Json.parse}).
     *
     * @param json parsed JSON object
     * @return the object
     * @throws com.desktopaccountingapi.quickbooksdesktop.core.Json.JsonException if a member has the wrong JSON type
     */
    public static AccountTaxLine fromJson(Object json) {
        Map<String, Object> o = Wire.object(json, "AccountTaxLine");
        AccountTaxLine m = new AccountTaxLine();
        m.objectType = Wire.get(o, "objectType", Wire::asString);
        m.taxLineId = Wire.get(o, "taxLineId", Wire::asInteger);
        m.taxLineName = Wire.get(o, "taxLineName", Wire::asString);
        m.additionalProperties = Wire.extra(o, KNOWN);
        return m;
    }

    /**
     * Parses the object from JSON text.
     *
     * @param json JSON text
     * @return the object
     */
    public static AccountTaxLine parse(String json) {
        return fromJson(Json.parse(json));
    }

    /**
     * Type of this object.
     *
     * @return the value (null only if the API omitted it)
     */
    public String objectType() {
        return objectType;
    }

    /**
     * Tax line of this account tax line.
     *
     * @return the value, or null
     */
    public Integer taxLineId() {
        return taxLineId;
    }

    /**
     * Tax line name of this account tax line.
     *
     * @return the value, or null
     */
    public String taxLineName() {
        return taxLineName;
    }

    /**
     * Members the API sent that this SDK version does not know.
     *
     * @return unmodifiable map, in wire order
     */
    public Map<String, Object> additionalProperties() {
        return additionalProperties;
    }

    @Override
    public Map<String, Object> toWire() {
        Map<String, Object> w = new LinkedHashMap<>();
        w.put("objectType", this.objectType);
        w.put("taxLineId", this.taxLineId);
        w.put("taxLineName", this.taxLineName);
        w.putAll(this.additionalProperties);
        return w;
    }

    @Override
    public String toString() {
        return "AccountTaxLine" + toJson();
    }
}
