// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:d4adaec794b6cf028d0f87bcaed3668ec305d5e364a02008e8a22258ee3a7d59
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code AccountingDefaultTransactionClass} values.
 *
 * <p>Known values of an open set. The API may return values not listed here; treat unknown values as valid.
 */
public final class AccountingDefaultTransactionClass {
    private AccountingDefaultTransactionClass() {}

    /** {@code none} */
    public static final String NONE = "none";

    /** {@code accounts} */
    public static final String ACCOUNTS = "accounts";

    /** {@code items} */
    public static final String ITEMS = "items";

    /** {@code names} */
    public static final String NAMES = "names";
}
