// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:1cc3058cecb557ce1cc724d5236d36860df6bec39636e2d427c8a408bf5f2ca2
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code AccountsToInclude} values.
 *
 * <p>Allowed values.
 */
public final class AccountsToInclude {
    private AccountsToInclude() {}

    /** {@code all} */
    public static final String ALL = "all";

    /** {@code in_use} */
    public static final String IN_USE = "in_use";
}
