// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:79b06eb2008381661d24d3bd5e23643483ec1bf9b70d5f4cdff2a2a71e22fe94
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code AgingReportType} values.
 *
 * <p>Allowed values.
 */
public final class AgingReportType {
    private AgingReportType() {}

    /** {@code ap_aging_detail} */
    public static final String AP_AGING_DETAIL = "ap_aging_detail";

    /** {@code ap_aging_summary} */
    public static final String AP_AGING_SUMMARY = "ap_aging_summary";

    /** {@code ar_aging_detail} */
    public static final String AR_AGING_DETAIL = "ar_aging_detail";

    /** {@code ar_aging_summary} */
    public static final String AR_AGING_SUMMARY = "ar_aging_summary";

    /** {@code collections_report} */
    public static final String COLLECTIONS_REPORT = "collections_report";
}
