// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:79b06eb2008381661d24d3bd5e23643483ec1bf9b70d5f4cdff2a2a71e22fe94
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.InputObject;
import com.desktopaccountingapi.quickbooksdesktop.core.Wire;
import java.math.BigDecimal;
import java.util.List;

/**
 * Fields for creating an applied to transaction.
 *
 * <p>Fluent setters return this object. Fields you never set are not sent; on clearable fields, null is sent to clear the value.
 */
public final class ApplyToTransactionInput extends InputObject {
    /**
     * Creates an empty object. Set the required field {@code transactionId} before sending.
     */
    public ApplyToTransactionInput() {
        super("transactionId");
    }

    /**
     * Creates the object with its required fields.
     *
     * @param transactionId ID of the transaction.
     */
    public ApplyToTransactionInput(String transactionId) {
        this();
        transactionId(transactionId);
    }

    /**
     * ID of the transaction.
     *
     * <p>Required. Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ApplyToTransactionInput transactionId(String value) {
        setOptional("transactionId", value);
        return this;
    }

    /**
     * The {@code transactionId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String transactionId() {
        return value("transactionId");
    }

    /**
     * Payment amount of this applied to transaction. Decimal string with up to 2 decimal places.
     *
     * <p>Decimal; scale is preserved on the wire. Example: <code>"1250.00"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ApplyToTransactionInput paymentAmount(BigDecimal value) {
        setOptional("paymentAmount", Wire.decimalText(value));
        return this;
    }

    /**
     * The {@code paymentAmount} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public BigDecimal paymentAmount() {
        return Wire.decimalOrNull(value("paymentAmount"));
    }

    /**
     * Apply credits entries for this applied to transaction.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ApplyToTransactionInput applyCredits(List<ApplyCreditInput> value) {
        setOptional("applyCredits", value);
        return this;
    }

    /**
     * The {@code applyCredits} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public List<ApplyCreditInput> applyCredits() {
        return value("applyCredits");
    }

    /**
     * Discount amount of this applied to transaction. Decimal string with up to 2 decimal places.
     *
     * <p>Decimal; scale is preserved on the wire. Example: <code>"1250.00"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ApplyToTransactionInput discountAmount(BigDecimal value) {
        setOptional("discountAmount", Wire.decimalText(value));
        return this;
    }

    /**
     * The {@code discountAmount} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public BigDecimal discountAmount() {
        return Wire.decimalOrNull(value("discountAmount"));
    }

    /**
     * ID of the discount account for this applied to transaction.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ApplyToTransactionInput discountAccountId(String value) {
        setOptional("discountAccountId", value);
        return this;
    }

    /**
     * The {@code discountAccountId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String discountAccountId() {
        return value("discountAccountId");
    }

    /**
     * ID of the discount class for this applied to transaction.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ApplyToTransactionInput discountClassId(String value) {
        setOptional("discountClassId", value);
        return this;
    }

    /**
     * The {@code discountClassId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String discountClassId() {
        return value("discountClassId");
    }
}
