// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:1cc3058cecb557ce1cc724d5236d36860df6bec39636e2d427c8a408bf5f2ca2
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.InputObject;
import com.desktopaccountingapi.quickbooksdesktop.core.Wire;
import java.math.BigDecimal;

/**
 * Fields for creating an apply check to transaction.
 *
 * <p>Fluent setters return this object. Fields you never set are not sent; on clearable fields, null is sent to clear the value.
 */
public final class ApplyCheckToTxnInput extends InputObject {
    /**
     * Creates an empty object. Set the required field {@code transactionId} before sending.
     */
    public ApplyCheckToTxnInput() {
        super("transactionId");
    }

    /**
     * Creates the object with its required fields.
     *
     * @param transactionId ID of the transaction.
     */
    public ApplyCheckToTxnInput(String transactionId) {
        this();
        transactionId(transactionId);
    }

    /**
     * ID of the transaction.
     *
     * <p>Required. Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ApplyCheckToTxnInput transactionId(String value) {
        setOptional("transactionId", value);
        return this;
    }

    /**
     * The {@code transactionId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String transactionId() {
        return value("transactionId");
    }

    /**
     * Amount as a decimal string.
     *
     * <p>Decimal; scale is preserved on the wire. Example: <code>"1250.00"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ApplyCheckToTxnInput amount(BigDecimal value) {
        setOptional("amount", Wire.decimalText(value));
        return this;
    }

    /**
     * The {@code amount} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public BigDecimal amount() {
        return Wire.decimalOrNull(value("amount"));
    }
}
