// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:6f5ac28d7c33ac90aa7e2c15d88efd50e8e41c808bcc5489f0c8b1cb7833326a
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.InputObject;

/**
 * Barcode details for this discount item.
 *
 * <p>Fluent setters return this object. Fields you never set are not sent; on clearable fields, null is sent to clear the value.
 */
public final class BarcodeCreateInput extends InputObject {
    /**
     * Creates an empty object.
     */
    public BarcodeCreateInput() {
        super();
    }

    /**
     * Value.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public BarcodeCreateInput valueValue(String value) {
        setOptional("value", value);
        return this;
    }

    /**
     * The {@code value} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String valueValue() {
        return value("value");
    }

    /**
     * Assign even if used of this bar code.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public BarcodeCreateInput assignEvenIfUsed(Boolean value) {
        setOptional("assignEvenIfUsed", value);
        return this;
    }

    /**
     * The {@code assignEvenIfUsed} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Boolean assignEvenIfUsed() {
        return value("assignEvenIfUsed");
    }

    /**
     * Allow override of this bar code.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public BarcodeCreateInput allowOverride(Boolean value) {
        setOptional("allowOverride", value);
        return this;
    }

    /**
     * The {@code allowOverride} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Boolean allowOverride() {
        return value("allowOverride");
    }
}
