// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:79b06eb2008381661d24d3bd5e23643483ec1bf9b70d5f4cdff2a2a71e22fe94
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.Json;
import com.desktopaccountingapi.quickbooksdesktop.core.JsonWritable;
import com.desktopaccountingapi.quickbooksdesktop.core.Wire;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;

/**
 * Bill to pay as stored in QuickBooks Desktop.
 *
 * <p>Parsed tolerantly: unknown members go to {@link #additionalProperties()} and missing members read as null. {@link #toJson()} writes the wire form back.
 */
public final class BillsToPay implements JsonWritable {
    private static final Set<String> KNOWN = new HashSet<>(Arrays.asList("objectType", "bill", "credit"));

    private String objectType;
    private BillToPay bill;
    private Credit credit;
    private Map<String, Object> additionalProperties = Collections.emptyMap();

    private BillsToPay() {}

    /**
     * Reads the object from parsed JSON (see {@code Json.parse}).
     *
     * @param json parsed JSON object
     * @return the object
     * @throws com.desktopaccountingapi.quickbooksdesktop.core.Json.JsonException if a member has the wrong JSON type
     */
    public static BillsToPay fromJson(Object json) {
        Map<String, Object> o = Wire.object(json, "BillsToPay");
        BillsToPay m = new BillsToPay();
        m.objectType = Wire.get(o, "objectType", Wire::asString);
        m.bill = Wire.get(o, "bill", BillToPay::fromJson);
        m.credit = Wire.get(o, "credit", Credit::fromJson);
        m.additionalProperties = Wire.extra(o, KNOWN);
        return m;
    }

    /**
     * Parses the object from JSON text.
     *
     * @param json JSON text
     * @return the object
     */
    public static BillsToPay parse(String json) {
        return fromJson(Json.parse(json));
    }

    /**
     * Type of this object.
     *
     * @return the value (null only if the API omitted it)
     */
    public String objectType() {
        return objectType;
    }

    /**
     * Bill details for this bill to pay.
     *
     * @return the value, or null
     */
    public BillToPay bill() {
        return bill;
    }

    /**
     * Credit details.
     *
     * @return the value, or null
     */
    public Credit credit() {
        return credit;
    }

    /**
     * Members the API sent that this SDK version does not know.
     *
     * @return unmodifiable map, in wire order
     */
    public Map<String, Object> additionalProperties() {
        return additionalProperties;
    }

    @Override
    public Map<String, Object> toWire() {
        Map<String, Object> w = new LinkedHashMap<>();
        w.put("objectType", this.objectType);
        w.put("bill", this.bill);
        w.put("credit", this.credit);
        w.putAll(this.additionalProperties);
        return w;
    }

    @Override
    public String toString() {
        return "BillsToPay" + toJson();
    }
}
