// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:b5774d24bc8154ccc2acb85370ae27581a072c3f5070a529111ee2dd26f103b9
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code BudgetSummaryReportType} values.
 *
 * <p>Allowed values.
 */
public final class BudgetSummaryReportType {
    private BudgetSummaryReportType() {}

    /** {@code balance_sheet_budget_overview} */
    public static final String BALANCE_SHEET_BUDGET_OVERVIEW = "balance_sheet_budget_overview";

    /** {@code balance_sheet_budget_vs_actual} */
    public static final String BALANCE_SHEET_BUDGET_VS_ACTUAL = "balance_sheet_budget_vs_actual";

    /** {@code profit_and_loss_budget_overview} */
    public static final String PROFIT_AND_LOSS_BUDGET_OVERVIEW = "profit_and_loss_budget_overview";

    /** {@code profit_and_loss_budget_performance} */
    public static final String PROFIT_AND_LOSS_BUDGET_PERFORMANCE = "profit_and_loss_budget_performance";

    /** {@code profit_and_loss_budget_vs_actual} */
    public static final String PROFIT_AND_LOSS_BUDGET_VS_ACTUAL = "profit_and_loss_budget_vs_actual";
}
