// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:3d102b7bcecbf18e72b655745e5c55d641457fab2fd8184b3da643aeb51bb76f
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code BudgetCriterion} values.
 *
 * <p>Allowed values.
 */
public final class BudgetCriterion {
    private BudgetCriterion() {}

    /** {@code accounts} */
    public static final String ACCOUNTS = "accounts";

    /** {@code accounts_and_classes} */
    public static final String ACCOUNTS_AND_CLASSES = "accounts_and_classes";

    /** {@code accounts_and_customers} */
    public static final String ACCOUNTS_AND_CUSTOMERS = "accounts_and_customers";
}
