// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:d4adaec794b6cf028d0f87bcaed3668ec305d5e364a02008e8a22258ee3a7d59
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.Json;
import com.desktopaccountingapi.quickbooksdesktop.core.JsonWritable;
import com.desktopaccountingapi.quickbooksdesktop.core.Wire;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Build assembly as stored in QuickBooks Desktop.
 *
 * <p>Parsed tolerantly: unknown members go to {@link #additionalProperties()} and missing members read as null. {@link #toJson()} writes the wire form back.
 */
public final class BuildAssembly implements JsonWritable {
    private static final Set<String> KNOWN = new HashSet<>(Arrays.asList("id", "objectType", "createdAt", "updatedAt", "revisionNumber", "transactionNumber", "inventoryAssemblyItem", "inventorySite", "inventorySiteLocation", "serialNumber", "lotNumber", "expirationDate", "transactionDate", "refNumber", "memo", "isPending", "quantityToBuild", "quantityCanBuild", "quantityOnHand", "quantityOnSalesOrder", "externalId", "lines", "customFields"));

    private String id;
    private String objectType;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;
    private String revisionNumber;
    private Integer transactionNumber;
    private Reference inventoryAssemblyItem;
    private Reference inventorySite;
    private Reference inventorySiteLocation;
    private String serialNumber;
    private String lotNumber;
    private String expirationDate;
    private LocalDate transactionDate;
    private String refNumber;
    private String memo;
    private Boolean isPending;
    private Double quantityToBuild;
    private Double quantityCanBuild;
    private Double quantityOnHand;
    private Double quantityOnSalesOrder;
    private String externalId;
    private List<Line> lines;
    private List<CustomField> customFields;
    private Map<String, Object> additionalProperties = Collections.emptyMap();

    private BuildAssembly() {}

    /**
     * Reads the object from parsed JSON (see {@code Json.parse}).
     *
     * @param json parsed JSON object
     * @return the object
     * @throws com.desktopaccountingapi.quickbooksdesktop.core.Json.JsonException if a member has the wrong JSON type
     */
    public static BuildAssembly fromJson(Object json) {
        Map<String, Object> o = Wire.object(json, "BuildAssembly");
        BuildAssembly m = new BuildAssembly();
        m.id = Wire.get(o, "id", Wire::asString);
        m.objectType = Wire.get(o, "objectType", Wire::asString);
        m.createdAt = Wire.get(o, "createdAt", Wire::asDateTime);
        m.updatedAt = Wire.get(o, "updatedAt", Wire::asDateTime);
        m.revisionNumber = Wire.get(o, "revisionNumber", Wire::asString);
        m.transactionNumber = Wire.get(o, "transactionNumber", Wire::asInteger);
        m.inventoryAssemblyItem = Wire.get(o, "inventoryAssemblyItem", Reference::fromJson);
        m.inventorySite = Wire.get(o, "inventorySite", Reference::fromJson);
        m.inventorySiteLocation = Wire.get(o, "inventorySiteLocation", Reference::fromJson);
        m.serialNumber = Wire.get(o, "serialNumber", Wire::asString);
        m.lotNumber = Wire.get(o, "lotNumber", Wire::asString);
        m.expirationDate = Wire.get(o, "expirationDate", Wire::asString);
        m.transactionDate = Wire.get(o, "transactionDate", Wire::asDate);
        m.refNumber = Wire.get(o, "refNumber", Wire::asString);
        m.memo = Wire.get(o, "memo", Wire::asString);
        m.isPending = Wire.get(o, "isPending", Wire::asBoolean);
        m.quantityToBuild = Wire.get(o, "quantityToBuild", Wire::asDouble);
        m.quantityCanBuild = Wire.get(o, "quantityCanBuild", Wire::asDouble);
        m.quantityOnHand = Wire.get(o, "quantityOnHand", Wire::asDouble);
        m.quantityOnSalesOrder = Wire.get(o, "quantityOnSalesOrder", Wire::asDouble);
        m.externalId = Wire.get(o, "externalId", Wire::asString);
        m.lines = Wire.list(o, "lines", Line::fromJson);
        m.customFields = Wire.list(o, "customFields", CustomField::fromJson);
        m.additionalProperties = Wire.extra(o, KNOWN);
        return m;
    }

    /**
     * Parses the object from JSON text.
     *
     * @param json JSON text
     * @return the object
     */
    public static BuildAssembly parse(String json) {
        return fromJson(Json.parse(json));
    }

    /**
     * QuickBooks-assigned ID of this build assembly.
     *
     * @return the value (null only if the API omitted it)
     */
    public String id() {
        return id;
    }

    /**
     * Type of this object.
     *
     * @return the value (null only if the API omitted it)
     */
    public String objectType() {
        return objectType;
    }

    /**
     * When this build assembly was created, as an ISO 8601 date-time with the QuickBooks computer's UTC offset.
     *
     * <p>Example: <code>"2026-10-05T09:14:03-07:00"</code>.
     *
     * @return the value (null only if the API omitted it)
     */
    public OffsetDateTime createdAt() {
        return createdAt;
    }

    /**
     * When this build assembly was last changed, as an ISO 8601 date-time with the QuickBooks computer's UTC offset. Whole seconds: a second change within the same second keeps this value, so incremental syncs should overlap `updatedAfter` and deduplicate by `id` and `revisionNumber`.
     *
     * <p>Example: <code>"2026-10-05T09:14:03-07:00"</code>.
     *
     * @return the value (null only if the API omitted it)
     */
    public OffsetDateTime updatedAt() {
        return updatedAt;
    }

    /**
     * Current revision of this build assembly. Send it unchanged when updating; a stale value is rejected. QuickBooks changes it at most once per second, so a second edit within the same second keeps the same value. This API spaces its own consecutive writes to one object by over a second; edits made elsewhere in the same second are not detected.
     *
     * @return the value (null only if the API omitted it)
     */
    public String revisionNumber() {
        return revisionNumber;
    }

    /**
     * Sequential transaction number QuickBooks assigns internally.
     *
     * @return the value, or null
     */
    public Integer transactionNumber() {
        return transactionNumber;
    }

    /**
     * The inventory assembly item for this build assembly.
     *
     * @return the value, or null
     */
    public Reference inventoryAssemblyItem() {
        return inventoryAssemblyItem;
    }

    /**
     * The inventory site for this build assembly.
     *
     * @return the value, or null
     */
    public Reference inventorySite() {
        return inventorySite;
    }

    /**
     * The inventory site location for this build assembly.
     *
     * @return the value, or null
     */
    public Reference inventorySiteLocation() {
        return inventorySiteLocation;
    }

    /**
     * Serial number of this build assembly.
     *
     * @return the value, or null
     */
    public String serialNumber() {
        return serialNumber;
    }

    /**
     * Lot number of this build assembly.
     *
     * @return the value, or null
     */
    public String lotNumber() {
        return lotNumber;
    }

    /**
     * Expiration date of this build assembly.
     *
     * @return the value, or null
     */
    public String expirationDate() {
        return expirationDate;
    }

    /**
     * Date of this build assembly (YYYY-MM-DD).
     *
     * <p>Example: <code>"2026-10-05"</code>.
     *
     * @return the value, or null
     */
    public LocalDate transactionDate() {
        return transactionDate;
    }

    /**
     * Reference number of this build assembly, such as an invoice or check number. Case-sensitive.
     *
     * @return the value, or null
     */
    public String refNumber() {
        return refNumber;
    }

    /**
     * Internal memo for this build assembly; shown in reports, not on printed forms.
     *
     * @return the value, or null
     */
    public String memo() {
        return memo;
    }

    /**
     * Whether this build assembly is pending (not yet final) and does not post to accounts.
     *
     * @return the value, or null
     */
    public Boolean isPending() {
        return isPending;
    }

    /**
     * Quantity to build of this build assembly.
     *
     * @return the value, or null
     */
    public Double quantityToBuild() {
        return quantityToBuild;
    }

    /**
     * Quantity can build of this build assembly.
     *
     * @return the value, or null
     */
    public Double quantityCanBuild() {
        return quantityCanBuild;
    }

    /**
     * Quantity on hand of this build assembly.
     *
     * @return the value, or null
     */
    public Double quantityOnHand() {
        return quantityOnHand;
    }

    /**
     * Quantity on sales order of this build assembly.
     *
     * @return the value, or null
     */
    public Double quantityOnSalesOrder() {
        return quantityOnSalesOrder;
    }

    /**
     * Your own UUID for this build assembly, stored by QuickBooks so you can match records with your system.
     *
     * @return the value, or null
     */
    public String externalId() {
        return externalId;
    }

    /**
     * Line items of this build assembly.
     *
     * @return the value (null only if the API omitted it)
     */
    public List<Line> lines() {
        return lines;
    }

    /**
     * Custom field values QuickBooks stores on this build assembly.
     *
     * @return the value (null only if the API omitted it)
     */
    public List<CustomField> customFields() {
        return customFields;
    }

    /**
     * Members the API sent that this SDK version does not know.
     *
     * @return unmodifiable map, in wire order
     */
    public Map<String, Object> additionalProperties() {
        return additionalProperties;
    }

    @Override
    public Map<String, Object> toWire() {
        Map<String, Object> w = new LinkedHashMap<>();
        w.put("id", this.id);
        w.put("objectType", this.objectType);
        w.put("createdAt", this.createdAt);
        w.put("updatedAt", this.updatedAt);
        w.put("revisionNumber", this.revisionNumber);
        w.put("transactionNumber", this.transactionNumber);
        w.put("inventoryAssemblyItem", this.inventoryAssemblyItem);
        w.put("inventorySite", this.inventorySite);
        w.put("inventorySiteLocation", this.inventorySiteLocation);
        w.put("serialNumber", this.serialNumber);
        w.put("lotNumber", this.lotNumber);
        w.put("expirationDate", this.expirationDate);
        w.put("transactionDate", this.transactionDate);
        w.put("refNumber", this.refNumber);
        w.put("memo", this.memo);
        w.put("isPending", this.isPending);
        w.put("quantityToBuild", this.quantityToBuild);
        w.put("quantityCanBuild", this.quantityCanBuild);
        w.put("quantityOnHand", this.quantityOnHand);
        w.put("quantityOnSalesOrder", this.quantityOnSalesOrder);
        w.put("externalId", this.externalId);
        w.put("lines", this.lines);
        w.put("customFields", this.customFields);
        w.putAll(this.additionalProperties);
        return w;
    }

    @Override
    public String toString() {
        return "BuildAssembly" + toJson();
    }
}
