// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:1cc3058cecb557ce1cc724d5236d36860df6bec39636e2d427c8a408bf5f2ca2
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.InputObject;
import java.time.LocalDate;

/**
 * Fields for creating a build assembly.
 *
 * <p>Fluent setters return this object. Fields you never set are not sent; on clearable fields, null is sent to clear the value.
 */
public final class BuildAssemblyCreateInput extends InputObject {
    /**
     * Creates an empty object. Set the required fields {@code inventoryAssemblyItemId}, {@code quantityToBuild} before sending.
     */
    public BuildAssemblyCreateInput() {
        super("inventoryAssemblyItemId", "quantityToBuild");
    }

    /**
     * Creates the object with its required fields.
     *
     * @param inventoryAssemblyItemId ID of the inventory assembly item for this build assembly.
     * @param quantityToBuild Quantity to build of this build assembly.
     */
    public BuildAssemblyCreateInput(String inventoryAssemblyItemId, Double quantityToBuild) {
        this();
        inventoryAssemblyItemId(inventoryAssemblyItemId);
        quantityToBuild(quantityToBuild);
    }

    /**
     * ID of the inventory assembly item for this build assembly.
     *
     * <p>Required. Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public BuildAssemblyCreateInput inventoryAssemblyItemId(String value) {
        setOptional("inventoryAssemblyItemId", value);
        return this;
    }

    /**
     * The {@code inventoryAssemblyItemId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String inventoryAssemblyItemId() {
        return value("inventoryAssemblyItemId");
    }

    /**
     * ID of the inventory site for this build assembly.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public BuildAssemblyCreateInput inventorySiteId(String value) {
        setOptional("inventorySiteId", value);
        return this;
    }

    /**
     * The {@code inventorySiteId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String inventorySiteId() {
        return value("inventorySiteId");
    }

    /**
     * ID of the inventory site location for this build assembly.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public BuildAssemblyCreateInput inventorySiteLocationId(String value) {
        setOptional("inventorySiteLocationId", value);
        return this;
    }

    /**
     * The {@code inventorySiteLocationId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String inventorySiteLocationId() {
        return value("inventorySiteLocationId");
    }

    /**
     * Serial number of this build assembly. Cannot be combined with lotNumber.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public BuildAssemblyCreateInput serialNumber(String value) {
        setOptional("serialNumber", value);
        return this;
    }

    /**
     * The {@code serialNumber} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String serialNumber() {
        return value("serialNumber");
    }

    /**
     * Lot number of this build assembly. Cannot be combined with serialNumber.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public BuildAssemblyCreateInput lotNumber(String value) {
        setOptional("lotNumber", value);
        return this;
    }

    /**
     * The {@code lotNumber} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String lotNumber() {
        return value("lotNumber");
    }

    /**
     * Expiration date of this build assembly.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public BuildAssemblyCreateInput expirationDate(String value) {
        setOptional("expirationDate", value);
        return this;
    }

    /**
     * The {@code expirationDate} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String expirationDate() {
        return value("expirationDate");
    }

    /**
     * Date of this build assembly (YYYY-MM-DD).
     *
     * <p>Example: <code>"2026-10-05"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public BuildAssemblyCreateInput transactionDate(LocalDate value) {
        setOptional("transactionDate", value);
        return this;
    }

    /**
     * The {@code transactionDate} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public LocalDate transactionDate() {
        return value("transactionDate");
    }

    /**
     * Reference number of this build assembly, such as an invoice or check number. Case-sensitive.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public BuildAssemblyCreateInput refNumber(String value) {
        setOptional("refNumber", value);
        return this;
    }

    /**
     * The {@code refNumber} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String refNumber() {
        return value("refNumber");
    }

    /**
     * Internal memo for this build assembly; shown in reports, not on printed forms.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public BuildAssemblyCreateInput memo(String value) {
        setOptional("memo", value);
        return this;
    }

    /**
     * The {@code memo} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String memo() {
        return value("memo");
    }

    /**
     * Quantity to build of this build assembly.
     *
     * <p>Required.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public BuildAssemblyCreateInput quantityToBuild(Double value) {
        setOptional("quantityToBuild", value);
        return this;
    }

    /**
     * Quantity to build of this build assembly.
     *
     * @param value the value
     * @return this object
     */
    public BuildAssemblyCreateInput quantityToBuild(double value) {
        setOptional("quantityToBuild", value);
        return this;
    }

    /**
     * The {@code quantityToBuild} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Double quantityToBuild() {
        return value("quantityToBuild");
    }

    /**
     * Mark pending if required of this build assembly.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public BuildAssemblyCreateInput markPendingIfRequired(Boolean value) {
        setOptional("markPendingIfRequired", value);
        return this;
    }

    /**
     * The {@code markPendingIfRequired} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Boolean markPendingIfRequired() {
        return value("markPendingIfRequired");
    }

    /**
     * Your own UUID for this build assembly, stored by QuickBooks so you can match records with your system.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public BuildAssemblyCreateInput externalId(String value) {
        setOptional("externalId", value);
        return this;
    }

    /**
     * The {@code externalId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String externalId() {
        return value("externalId");
    }
}
