// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:1fc5496cc47b442606ea78c818f94a29798b32785dc14c59e7986e24f10bf332
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.Json;
import com.desktopaccountingapi.quickbooksdesktop.core.JsonWritable;
import com.desktopaccountingapi.quickbooksdesktop.core.Wire;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;

/**
 * Class as stored in QuickBooks Desktop.
 *
 * <p>Parsed tolerantly: unknown members go to {@link #additionalProperties()} and missing members read as null. {@link #toJson()} writes the wire form back.
 */
public final class Class implements JsonWritable {
    private static final Set<String> KNOWN = new HashSet<>(Arrays.asList("id", "objectType", "createdAt", "updatedAt", "revisionNumber", "name", "fullName", "isActive", "parent", "sublevel"));

    private String id;
    private String objectType;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;
    private String revisionNumber;
    private String name;
    private String fullName;
    private Boolean isActive;
    private Reference parent;
    private Integer sublevel;
    private Map<String, Object> additionalProperties = Collections.emptyMap();

    private Class() {}

    /**
     * Reads the object from parsed JSON (see {@code Json.parse}).
     *
     * @param json parsed JSON object
     * @return the object
     * @throws com.desktopaccountingapi.quickbooksdesktop.core.Json.JsonException if a member has the wrong JSON type
     */
    public static Class fromJson(Object json) {
        Map<String, Object> o = Wire.object(json, "Class");
        Class m = new Class();
        m.id = Wire.get(o, "id", Wire::asString);
        m.objectType = Wire.get(o, "objectType", Wire::asString);
        m.createdAt = Wire.get(o, "createdAt", Wire::asDateTime);
        m.updatedAt = Wire.get(o, "updatedAt", Wire::asDateTime);
        m.revisionNumber = Wire.get(o, "revisionNumber", Wire::asString);
        m.name = Wire.get(o, "name", Wire::asString);
        m.fullName = Wire.get(o, "fullName", Wire::asString);
        m.isActive = Wire.get(o, "isActive", Wire::asBoolean);
        m.parent = Wire.get(o, "parent", Reference::fromJson);
        m.sublevel = Wire.get(o, "sublevel", Wire::asInteger);
        m.additionalProperties = Wire.extra(o, KNOWN);
        return m;
    }

    /**
     * Parses the object from JSON text.
     *
     * @param json JSON text
     * @return the object
     */
    public static Class parse(String json) {
        return fromJson(Json.parse(json));
    }

    /**
     * QuickBooks-assigned ID of this class.
     *
     * @return the value (null only if the API omitted it)
     */
    public String id() {
        return id;
    }

    /**
     * Type of this object.
     *
     * @return the value (null only if the API omitted it)
     */
    public String objectType() {
        return objectType;
    }

    /**
     * When this class was created, as an ISO 8601 date-time with the QuickBooks computer's UTC offset.
     *
     * <p>Example: <code>"2026-10-05T09:14:03-07:00"</code>.
     *
     * @return the value (null only if the API omitted it)
     */
    public OffsetDateTime createdAt() {
        return createdAt;
    }

    /**
     * When this class was last changed, as an ISO 8601 date-time with the QuickBooks computer's UTC offset. Whole seconds: a second change within the same second keeps this value, so incremental syncs should overlap `updatedAfter` and deduplicate by `id` and `revisionNumber`.
     *
     * <p>Example: <code>"2026-10-05T09:14:03-07:00"</code>.
     *
     * @return the value (null only if the API omitted it)
     */
    public OffsetDateTime updatedAt() {
        return updatedAt;
    }

    /**
     * Current revision of this class. Send it unchanged when updating; a stale value is rejected. QuickBooks changes it at most once per second, so a second edit within the same second keeps the same value. This API spaces its own consecutive writes to one object by over a second; edits made elsewhere in the same second are not detected.
     *
     * @return the value (null only if the API omitted it)
     */
    public String revisionNumber() {
        return revisionNumber;
    }

    /**
     * Name of this class, unique within its parent level.
     *
     * @return the value, or null
     */
    public String name() {
        return name;
    }

    /**
     * Full hierarchical name of this class: parent names and its own name separated by colons.
     *
     * @return the value, or null
     */
    public String fullName() {
        return fullName;
    }

    /**
     * Whether this class is active. Inactive objects stay in QuickBooks but are hidden from most lists.
     *
     * @return the value, or null
     */
    public Boolean isActive() {
        return isActive;
    }

    /**
     * Parent object one level up in the hierarchy, or null at the top level.
     *
     * @return the value, or null
     */
    public Reference parent() {
        return parent;
    }

    /**
     * Depth in the hierarchy: 0 for top-level objects, 1 for their children and so on.
     *
     * @return the value, or null
     */
    public Integer sublevel() {
        return sublevel;
    }

    /**
     * Members the API sent that this SDK version does not know.
     *
     * @return unmodifiable map, in wire order
     */
    public Map<String, Object> additionalProperties() {
        return additionalProperties;
    }

    @Override
    public Map<String, Object> toWire() {
        Map<String, Object> w = new LinkedHashMap<>();
        w.put("id", this.id);
        w.put("objectType", this.objectType);
        w.put("createdAt", this.createdAt);
        w.put("updatedAt", this.updatedAt);
        w.put("revisionNumber", this.revisionNumber);
        w.put("name", this.name);
        w.put("fullName", this.fullName);
        w.put("isActive", this.isActive);
        w.put("parent", this.parent);
        w.put("sublevel", this.sublevel);
        w.putAll(this.additionalProperties);
        return w;
    }

    @Override
    public String toString() {
        return "Class" + toJson();
    }
}
