// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:d4adaec794b6cf028d0f87bcaed3668ec305d5e364a02008e8a22258ee3a7d59
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code CurrencyFormatInputThousandSeparator} values.
 *
 * <p>Allowed values.
 */
public final class CurrencyFormatInputThousandSeparator {
    private CurrencyFormatInputThousandSeparator() {}

    /** {@code comma} */
    public static final String COMMA = "comma";

    /** {@code period} */
    public static final String PERIOD = "period";

    /** {@code space} */
    public static final String SPACE = "space";

    /** {@code apostrophe} */
    public static final String APOSTROPHE = "apostrophe";
}
