// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:3d102b7bcecbf18e72b655745e5c55d641457fab2fd8184b3da643aeb51bb76f
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code CurrencyFormatDecimalSeparator} values.
 *
 * <p>Known values of an open set. The API may return values not listed here; treat unknown values as valid.
 */
public final class CurrencyFormatDecimalSeparator {
    private CurrencyFormatDecimalSeparator() {}

    /** {@code period} */
    public static final String PERIOD = "period";

    /** {@code comma} */
    public static final String COMMA = "comma";
}
