// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:b5774d24bc8154ccc2acb85370ae27581a072c3f5070a529111ee2dd26f103b9
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.InputObject;
import com.desktopaccountingapi.quickbooksdesktop.core.Wire;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

/**
 * Fields for updating a customer.
 *
 * <p>Fluent setters return this object. Fields you never set are not sent; on clearable fields, null is sent to clear the value.
 */
public final class CustomerUpdateInput extends InputObject {
    /**
     * Creates an empty object. Set the required field {@code revisionNumber} before sending.
     */
    public CustomerUpdateInput() {
        super("revisionNumber");
    }

    /**
     * Creates the object with its required fields.
     *
     * @param revisionNumber Current revision of this customer. Send it unchanged when updating; a stale value is rejected. QuickBooks changes it at most once per second, so a second edit within the same second keeps the same value. This API spaces its own consecutive writes to one object by over a second; edits made elsewhere in the same second are not detected.
     */
    public CustomerUpdateInput(String revisionNumber) {
        this();
        revisionNumber(revisionNumber);
    }

    /**
     * Current revision of this customer. Send it unchanged when updating; a stale value is rejected. QuickBooks changes it at most once per second, so a second edit within the same second keeps the same value. This API spaces its own consecutive writes to one object by over a second; edits made elsewhere in the same second are not detected.
     *
     * <p>Required.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public CustomerUpdateInput revisionNumber(String value) {
        setOptional("revisionNumber", value);
        return this;
    }

    /**
     * The {@code revisionNumber} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String revisionNumber() {
        return value("revisionNumber");
    }

    /**
     * Name of this customer, unique within its parent level.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public CustomerUpdateInput name(String value) {
        setOptional("name", value);
        return this;
    }

    /**
     * The {@code name} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String name() {
        return value("name");
    }

    /**
     * Whether this customer is active. Inactive objects stay in QuickBooks but are hidden from most lists.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public CustomerUpdateInput isActive(Boolean value) {
        setOptional("isActive", value);
        return this;
    }

    /**
     * The {@code isActive} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Boolean isActive() {
        return value("isActive");
    }

    /**
     * ID of the class for this customer.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public CustomerUpdateInput classId(String value) {
        setOptional("classId", value);
        return this;
    }

    /**
     * The {@code classId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String classId() {
        return value("classId");
    }

    /**
     * ID of the parent object, making this customer a child in the hierarchy.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public CustomerUpdateInput parentId(String value) {
        setOptional("parentId", value);
        return this;
    }

    /**
     * The {@code parentId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String parentId() {
        return value("parentId");
    }

    /**
     * Company name.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public CustomerUpdateInput companyName(String value) {
        setNullable("companyName", value);
        return this;
    }

    /**
     * The {@code companyName} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String companyName() {
        return value("companyName");
    }

    /**
     * Salutation such as Mr. or Dr.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public CustomerUpdateInput salutation(String value) {
        setNullable("salutation", value);
        return this;
    }

    /**
     * The {@code salutation} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String salutation() {
        return value("salutation");
    }

    /**
     * First name.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public CustomerUpdateInput firstName(String value) {
        setNullable("firstName", value);
        return this;
    }

    /**
     * The {@code firstName} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String firstName() {
        return value("firstName");
    }

    /**
     * Middle name or initial.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public CustomerUpdateInput middleName(String value) {
        setNullable("middleName", value);
        return this;
    }

    /**
     * The {@code middleName} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String middleName() {
        return value("middleName");
    }

    /**
     * Last name.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public CustomerUpdateInput lastName(String value) {
        setNullable("lastName", value);
        return this;
    }

    /**
     * The {@code lastName} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String lastName() {
        return value("lastName");
    }

    /**
     * Job title.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public CustomerUpdateInput jobTitle(String value) {
        setNullable("jobTitle", value);
        return this;
    }

    /**
     * The {@code jobTitle} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String jobTitle() {
        return value("jobTitle");
    }

    /**
     * Billing address for this customer.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public CustomerUpdateInput billingAddress(AddressUpdateInput value) {
        setOptional("billingAddress", value);
        return this;
    }

    /**
     * The {@code billingAddress} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public AddressUpdateInput billingAddress() {
        return value("billingAddress");
    }

    /**
     * Shipping address for this customer.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public CustomerUpdateInput shippingAddress(AddressUpdateInput value) {
        setOptional("shippingAddress", value);
        return this;
    }

    /**
     * The {@code shippingAddress} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public AddressUpdateInput shippingAddress() {
        return value("shippingAddress");
    }

    /**
     * Alternate shipping addresses entries for this customer.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public CustomerUpdateInput alternateShippingAddresses(List<ShippingAddressUpdateInput> value) {
        setOptional("alternateShippingAddresses", value);
        return this;
    }

    /**
     * The {@code alternateShippingAddresses} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public List<ShippingAddressUpdateInput> alternateShippingAddresses() {
        return value("alternateShippingAddresses");
    }

    /**
     * Main phone number.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public CustomerUpdateInput phone(String value) {
        setNullable("phone", value);
        return this;
    }

    /**
     * The {@code phone} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String phone() {
        return value("phone");
    }

    /**
     * Alternate phone number.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public CustomerUpdateInput alternatePhone(String value) {
        setNullable("alternatePhone", value);
        return this;
    }

    /**
     * The {@code alternatePhone} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String alternatePhone() {
        return value("alternatePhone");
    }

    /**
     * Fax number.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public CustomerUpdateInput fax(String value) {
        setNullable("fax", value);
        return this;
    }

    /**
     * The {@code fax} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String fax() {
        return value("fax");
    }

    /**
     * Email address.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public CustomerUpdateInput email(String value) {
        setNullable("email", value);
        return this;
    }

    /**
     * The {@code email} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String email() {
        return value("email");
    }

    /**
     * Email address copied on emailed forms.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public CustomerUpdateInput ccEmail(String value) {
        setNullable("ccEmail", value);
        return this;
    }

    /**
     * The {@code ccEmail} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String ccEmail() {
        return value("ccEmail");
    }

    /**
     * Name of the main contact person.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public CustomerUpdateInput contact(String value) {
        setNullable("contact", value);
        return this;
    }

    /**
     * The {@code contact} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String contact() {
        return value("contact");
    }

    /**
     * Name of an alternate contact person.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public CustomerUpdateInput alternateContact(String value) {
        setNullable("alternateContact", value);
        return this;
    }

    /**
     * The {@code alternateContact} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String alternateContact() {
        return value("alternateContact");
    }

    /**
     * Custom contact fields entries for this customer.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public CustomerUpdateInput customContactFields(List<CustomContactFieldInput> value) {
        setOptional("customContactFields", value);
        return this;
    }

    /**
     * The {@code customContactFields} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public List<CustomContactFieldInput> customContactFields() {
        return value("customContactFields");
    }

    /**
     * Additional contacts entries for this customer.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public CustomerUpdateInput additionalContacts(List<ContactUpdateInput> value) {
        setOptional("additionalContacts", value);
        return this;
    }

    /**
     * The {@code additionalContacts} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public List<ContactUpdateInput> additionalContacts() {
        return value("additionalContacts");
    }

    /**
     * ID of the customer type for this customer.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public CustomerUpdateInput customerTypeId(String value) {
        setOptional("customerTypeId", value);
        return this;
    }

    /**
     * The {@code customerTypeId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String customerTypeId() {
        return value("customerTypeId");
    }

    /**
     * ID of the terms for this customer.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public CustomerUpdateInput termsId(String value) {
        setOptional("termsId", value);
        return this;
    }

    /**
     * The {@code termsId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String termsId() {
        return value("termsId");
    }

    /**
     * ID of the sales representative for this customer.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public CustomerUpdateInput salesRepresentativeId(String value) {
        setOptional("salesRepresentativeId", value);
        return this;
    }

    /**
     * The {@code salesRepresentativeId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String salesRepresentativeId() {
        return value("salesRepresentativeId");
    }

    /**
     * ID of the sales tax code for this customer.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public CustomerUpdateInput salesTaxCodeId(String value) {
        setOptional("salesTaxCodeId", value);
        return this;
    }

    /**
     * The {@code salesTaxCodeId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String salesTaxCodeId() {
        return value("salesTaxCodeId");
    }

    /**
     * ID of the sales tax item for this customer.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public CustomerUpdateInput salesTaxItemId(String value) {
        setOptional("salesTaxItemId", value);
        return this;
    }

    /**
     * The {@code salesTaxItemId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String salesTaxItemId() {
        return value("salesTaxItemId");
    }

    /**
     * Resale number of this customer.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public CustomerUpdateInput resaleNumber(String value) {
        setNullable("resaleNumber", value);
        return this;
    }

    /**
     * The {@code resaleNumber} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String resaleNumber() {
        return value("resaleNumber");
    }

    /**
     * Account number for this customer.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public CustomerUpdateInput accountNumber(String value) {
        setNullable("accountNumber", value);
        return this;
    }

    /**
     * The {@code accountNumber} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String accountNumber() {
        return value("accountNumber");
    }

    /**
     * Credit limit as a decimal string.
     *
     * <p>Decimal; scale is preserved on the wire. Example: <code>"1250.00"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public CustomerUpdateInput creditLimit(BigDecimal value) {
        setOptional("creditLimit", Wire.decimalText(value));
        return this;
    }

    /**
     * The {@code creditLimit} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public BigDecimal creditLimit() {
        return Wire.decimalOrNull(value("creditLimit"));
    }

    /**
     * ID of the preferred payment method for this customer.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public CustomerUpdateInput preferredPaymentMethodId(String value) {
        setOptional("preferredPaymentMethodId", value);
        return this;
    }

    /**
     * The {@code preferredPaymentMethodId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String preferredPaymentMethodId() {
        return value("preferredPaymentMethodId");
    }

    /**
     * The {@code creditCard} field.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public CustomerUpdateInput creditCard(CreditCardUpdateInput value) {
        setOptional("creditCard", value);
        return this;
    }

    /**
     * The {@code creditCard} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public CreditCardUpdateInput creditCard() {
        return value("creditCard");
    }

    /**
     * Job status of this customer.
     *
     * <p>Allowed values are in {@link CustomerUpdateInputJobStatus}.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public CustomerUpdateInput jobStatus(String value) {
        setOptional("jobStatus", value);
        return this;
    }

    /**
     * The {@code jobStatus} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String jobStatus() {
        return value("jobStatus");
    }

    /**
     * Job start date (YYYY-MM-DD).
     *
     * <p>Example: <code>"2026-10-05"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public CustomerUpdateInput jobStartDate(LocalDate value) {
        setOptional("jobStartDate", value);
        return this;
    }

    /**
     * The {@code jobStartDate} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public LocalDate jobStartDate() {
        return value("jobStartDate");
    }

    /**
     * Job projected end date (YYYY-MM-DD).
     *
     * <p>Example: <code>"2026-10-05"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public CustomerUpdateInput jobProjectedEndDate(LocalDate value) {
        setOptional("jobProjectedEndDate", value);
        return this;
    }

    /**
     * The {@code jobProjectedEndDate} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public LocalDate jobProjectedEndDate() {
        return value("jobProjectedEndDate");
    }

    /**
     * Job end date (YYYY-MM-DD).
     *
     * <p>Example: <code>"2026-10-05"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public CustomerUpdateInput jobEndDate(LocalDate value) {
        setOptional("jobEndDate", value);
        return this;
    }

    /**
     * The {@code jobEndDate} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public LocalDate jobEndDate() {
        return value("jobEndDate");
    }

    /**
     * Job description of this customer.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public CustomerUpdateInput jobDescription(String value) {
        setNullable("jobDescription", value);
        return this;
    }

    /**
     * The {@code jobDescription} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String jobDescription() {
        return value("jobDescription");
    }

    /**
     * ID of the job type for this customer.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public CustomerUpdateInput jobTypeId(String value) {
        setOptional("jobTypeId", value);
        return this;
    }

    /**
     * The {@code jobTypeId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String jobTypeId() {
        return value("jobTypeId");
    }

    /**
     * Note for this customer.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public CustomerUpdateInput note(String value) {
        setNullable("note", value);
        return this;
    }

    /**
     * The {@code note} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String note() {
        return value("note");
    }

    /**
     * Additional notes entries for this customer.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public CustomerUpdateInput additionalNotes(List<NoteUpdateInput> value) {
        setOptional("additionalNotes", value);
        return this;
    }

    /**
     * The {@code additionalNotes} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public List<NoteUpdateInput> additionalNotes() {
        return value("additionalNotes");
    }

    /**
     * Preferred delivery method of this customer.
     *
     * <p>Allowed values are in {@link CustomerUpdateInputPreferredDeliveryMethod}.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public CustomerUpdateInput preferredDeliveryMethod(String value) {
        setOptional("preferredDeliveryMethod", value);
        return this;
    }

    /**
     * The {@code preferredDeliveryMethod} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String preferredDeliveryMethod() {
        return value("preferredDeliveryMethod");
    }

    /**
     * ID of the price level for this customer.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public CustomerUpdateInput priceLevelId(String value) {
        setOptional("priceLevelId", value);
        return this;
    }

    /**
     * The {@code priceLevelId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String priceLevelId() {
        return value("priceLevelId");
    }

    /**
     * ID of the currency for this customer.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public CustomerUpdateInput currencyId(String value) {
        setOptional("currencyId", value);
        return this;
    }

    /**
     * The {@code currencyId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String currencyId() {
        return value("currencyId");
    }
}
