// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:1cc3058cecb557ce1cc724d5236d36860df6bec39636e2d427c8a408bf5f2ca2
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code CustomSummaryReportType} values.
 *
 * <p>Allowed values.
 */
public final class CustomSummaryReportType {
    private CustomSummaryReportType() {}

    /** {@code custom_summary} */
    public static final String CUSTOM_SUMMARY = "custom_summary";
}
