// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:79b06eb2008381661d24d3bd5e23643483ec1bf9b70d5f4cdff2a2a71e22fe94
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code CustomerCreateInputPreferredDeliveryMethod} values.
 *
 * <p>Allowed values.
 */
public final class CustomerCreateInputPreferredDeliveryMethod {
    private CustomerCreateInputPreferredDeliveryMethod() {}

    /** {@code none} */
    public static final String NONE = "none";

    /** {@code email} */
    public static final String EMAIL = "email";

    /** {@code mail} */
    public static final String MAIL = "mail";
}
