// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:1fc5496cc47b442606ea78c818f94a29798b32785dc14c59e7986e24f10bf332
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code CustomSummaryReportType} values.
 *
 * <p>Allowed values.
 */
public final class CustomSummaryReportType {
    private CustomSummaryReportType() {}

    /** {@code custom_summary} */
    public static final String CUSTOM_SUMMARY = "custom_summary";
}
