// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:1fc5496cc47b442606ea78c818f94a29798b32785dc14c59e7986e24f10bf332
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code CustomerCreateInputJobStatus} values.
 *
 * <p>Allowed values.
 */
public final class CustomerCreateInputJobStatus {
    private CustomerCreateInputJobStatus() {}

    /** {@code awarded} */
    public static final String AWARDED = "awarded";

    /** {@code closed} */
    public static final String CLOSED = "closed";

    /** {@code in_progress} */
    public static final String IN_PROGRESS = "in_progress";

    /** {@code none} */
    public static final String NONE = "none";

    /** {@code not_awarded} */
    public static final String NOT_AWARDED = "not_awarded";

    /** {@code pending} */
    public static final String PENDING = "pending";
}
