// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:68a0d76d6b51187adfc66d768eae8e30675b5093f4ae538b0d9c32c905b9bb2d
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.InputObject;
import com.desktopaccountingapi.quickbooksdesktop.core.Wire;
import java.math.BigDecimal;

/**
 * Fields for creating a date-driven term.
 *
 * <p>Fluent setters return this object. Fields you never set are not sent; on clearable fields, null is sent to clear the value.
 */
public final class DateDrivenTermCreateInput extends InputObject {
    /**
     * Creates an empty object. Set the required fields {@code name}, {@code dueDayOfMonth} before sending.
     */
    public DateDrivenTermCreateInput() {
        super("name", "dueDayOfMonth");
    }

    /**
     * Creates the object with its required fields.
     *
     * @param name Name of this date-driven term, unique within its parent level.
     * @param dueDayOfMonth Due day of month of this date-driven term.
     */
    public DateDrivenTermCreateInput(String name, Integer dueDayOfMonth) {
        this();
        name(name);
        dueDayOfMonth(dueDayOfMonth);
    }

    /**
     * Name of this date-driven term, unique within its parent level.
     *
     * <p>Required.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public DateDrivenTermCreateInput name(String value) {
        setOptional("name", value);
        return this;
    }

    /**
     * The {@code name} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String name() {
        return value("name");
    }

    /**
     * Whether this date-driven term is active. Inactive objects stay in QuickBooks but are hidden from most lists.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public DateDrivenTermCreateInput isActive(Boolean value) {
        setOptional("isActive", value);
        return this;
    }

    /**
     * The {@code isActive} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Boolean isActive() {
        return value("isActive");
    }

    /**
     * Due day of month of this date-driven term.
     *
     * <p>Required.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public DateDrivenTermCreateInput dueDayOfMonth(Integer value) {
        setOptional("dueDayOfMonth", value);
        return this;
    }

    /**
     * The {@code dueDayOfMonth} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Integer dueDayOfMonth() {
        return value("dueDayOfMonth");
    }

    /**
     * Grace period days of this date-driven term.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public DateDrivenTermCreateInput gracePeriodDays(Integer value) {
        setOptional("gracePeriodDays", value);
        return this;
    }

    /**
     * The {@code gracePeriodDays} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Integer gracePeriodDays() {
        return value("gracePeriodDays");
    }

    /**
     * Discount day of month of this date-driven term.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public DateDrivenTermCreateInput discountDayOfMonth(Integer value) {
        setOptional("discountDayOfMonth", value);
        return this;
    }

    /**
     * The {@code discountDayOfMonth} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Integer discountDayOfMonth() {
        return value("discountDayOfMonth");
    }

    /**
     * Discount percentage of this date-driven term. Percentage as a decimal string: "7.5" means 7.5 %.
     *
     * <p>Decimal; scale is preserved on the wire. Example: <code>"7.5"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public DateDrivenTermCreateInput discountPercentage(BigDecimal value) {
        setOptional("discountPercentage", Wire.decimalText(value));
        return this;
    }

    /**
     * The {@code discountPercentage} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public BigDecimal discountPercentage() {
        return Wire.decimalOrNull(value("discountPercentage"));
    }
}
