// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:1fc5496cc47b442606ea78c818f94a29798b32785dc14c59e7986e24f10bf332
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.Json;
import com.desktopaccountingapi.quickbooksdesktop.core.JsonWritable;
import com.desktopaccountingapi.quickbooksdesktop.core.Wire;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;

/**
 * Default unit as stored in QuickBooks Desktop.
 *
 * <p>Parsed tolerantly: unknown members go to {@link #additionalProperties()} and missing members read as null. {@link #toJson()} writes the wire form back.
 */
public final class DefaultUnit implements JsonWritable {
    private static final Set<String> KNOWN = new HashSet<>(Arrays.asList("unitUsedFor", "unit"));

    private String unitUsedFor;
    private String unit;
    private Map<String, Object> additionalProperties = Collections.emptyMap();

    private DefaultUnit() {}

    /**
     * Reads the object from parsed JSON (see {@code Json.parse}).
     *
     * @param json parsed JSON object
     * @return the object
     * @throws com.desktopaccountingapi.quickbooksdesktop.core.Json.JsonException if a member has the wrong JSON type
     */
    public static DefaultUnit fromJson(Object json) {
        Map<String, Object> o = Wire.object(json, "DefaultUnit");
        DefaultUnit m = new DefaultUnit();
        m.unitUsedFor = Wire.get(o, "unitUsedFor", Wire::asString);
        m.unit = Wire.get(o, "unit", Wire::asString);
        m.additionalProperties = Wire.extra(o, KNOWN);
        return m;
    }

    /**
     * Parses the object from JSON text.
     *
     * @param json JSON text
     * @return the object
     */
    public static DefaultUnit parse(String json) {
        return fromJson(Json.parse(json));
    }

    /**
     * Unit used for of this default unit.
     *
     * <p>Known values are in {@link DefaultUnitUnitUsedFor}; other values may appear.
     *
     * @return the value, or null
     */
    public String unitUsedFor() {
        return unitUsedFor;
    }

    /**
     * Unit of this default unit.
     *
     * @return the value, or null
     */
    public String unit() {
        return unit;
    }

    /**
     * Members the API sent that this SDK version does not know.
     *
     * @return unmodifiable map, in wire order
     */
    public Map<String, Object> additionalProperties() {
        return additionalProperties;
    }

    @Override
    public Map<String, Object> toWire() {
        Map<String, Object> w = new LinkedHashMap<>();
        w.put("unitUsedFor", this.unitUsedFor);
        w.put("unit", this.unit);
        w.putAll(this.additionalProperties);
        return w;
    }

    @Override
    public String toString() {
        return "DefaultUnit" + toJson();
    }
}
