// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:68a0d76d6b51187adfc66d768eae8e30675b5093f4ae538b0d9c32c905b9bb2d
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code DefaultUnitCreateInputUnitUsedFor} values.
 *
 * <p>Allowed values.
 */
public final class DefaultUnitCreateInputUnitUsedFor {
    private DefaultUnitCreateInputUnitUsedFor() {}

    /** {@code purchase} */
    public static final String PURCHASE = "purchase";

    /** {@code sales} */
    public static final String SALES = "sales";

    /** {@code shipping} */
    public static final String SHIPPING = "shipping";
}
