// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:6f5ac28d7c33ac90aa7e2c15d88efd50e8e41c808bcc5489f0c8b1cb7833326a
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.Json;
import com.desktopaccountingapi.quickbooksdesktop.core.JsonWritable;
import com.desktopaccountingapi.quickbooksdesktop.core.Wire;
import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;

/**
 * Deposit line as stored in QuickBooks Desktop.
 *
 * <p>Parsed tolerantly: unknown members go to {@link #additionalProperties()} and missing members read as null. {@link #toJson()} writes the wire form back.
 */
public final class DepositLine implements JsonWritable {
    private static final Set<String> KNOWN = new HashSet<>(Arrays.asList("objectType", "transactionType", "paymentTransactionId", "id", "paymentTransactionLineId", "entity", "account", "memo", "checkNumber", "paymentMethod", "class", "amount"));

    private String objectType;
    private String transactionType;
    private String paymentTransactionId;
    private String id;
    private String paymentTransactionLineId;
    private Reference entity;
    private Reference account;
    private String memo;
    private String checkNumber;
    private Reference paymentMethod;
    private Reference classRef;
    private BigDecimal amount;
    private Map<String, Object> additionalProperties = Collections.emptyMap();

    private DepositLine() {}

    /**
     * Reads the object from parsed JSON (see {@code Json.parse}).
     *
     * @param json parsed JSON object
     * @return the object
     * @throws com.desktopaccountingapi.quickbooksdesktop.core.Json.JsonException if a member has the wrong JSON type
     */
    public static DepositLine fromJson(Object json) {
        Map<String, Object> o = Wire.object(json, "DepositLine");
        DepositLine m = new DepositLine();
        m.objectType = Wire.get(o, "objectType", Wire::asString);
        m.transactionType = Wire.get(o, "transactionType", Wire::asString);
        m.paymentTransactionId = Wire.get(o, "paymentTransactionId", Wire::asString);
        m.id = Wire.get(o, "id", Wire::asString);
        m.paymentTransactionLineId = Wire.get(o, "paymentTransactionLineId", Wire::asString);
        m.entity = Wire.get(o, "entity", Reference::fromJson);
        m.account = Wire.get(o, "account", Reference::fromJson);
        m.memo = Wire.get(o, "memo", Wire::asString);
        m.checkNumber = Wire.get(o, "checkNumber", Wire::asString);
        m.paymentMethod = Wire.get(o, "paymentMethod", Reference::fromJson);
        m.classRef = Wire.get(o, "class", Reference::fromJson);
        m.amount = Wire.get(o, "amount", Wire::asDecimal);
        m.additionalProperties = Wire.extra(o, KNOWN);
        return m;
    }

    /**
     * Parses the object from JSON text.
     *
     * @param json JSON text
     * @return the object
     */
    public static DepositLine parse(String json) {
        return fromJson(Json.parse(json));
    }

    /**
     * Type of this object.
     *
     * @return the value (null only if the API omitted it)
     */
    public String objectType() {
        return objectType;
    }

    /**
     * Transaction type of this deposit line.
     *
     * <p>Known values are in {@link DepositLineTransactionType}; other values may appear.
     *
     * @return the value, or null
     */
    public String transactionType() {
        return transactionType;
    }

    /**
     * ID of the payment transaction.
     *
     * @return the value, or null
     */
    public String paymentTransactionId() {
        return paymentTransactionId;
    }

    /**
     * QuickBooks-assigned ID of this deposit line.
     *
     * @return the value, or null
     */
    public String id() {
        return id;
    }

    /**
     * ID of the payment transaction line.
     *
     * @return the value, or null
     */
    public String paymentTransactionLineId() {
        return paymentTransactionLineId;
    }

    /**
     * The entity for this deposit line.
     *
     * @return the value, or null
     */
    public Reference entity() {
        return entity;
    }

    /**
     * The account for this deposit line.
     *
     * @return the value, or null
     */
    public Reference account() {
        return account;
    }

    /**
     * Internal memo for this deposit line; shown in reports, not on printed forms.
     *
     * @return the value, or null
     */
    public String memo() {
        return memo;
    }

    /**
     * Check number of this deposit line.
     *
     * @return the value, or null
     */
    public String checkNumber() {
        return checkNumber;
    }

    /**
     * The payment method for this deposit line.
     *
     * @return the value, or null
     */
    public Reference paymentMethod() {
        return paymentMethod;
    }

    /**
     * The class for this deposit line.
     *
     * @return the value, or null
     */
    public Reference classRef() {
        return classRef;
    }

    /**
     * Amount as a decimal string.
     *
     * <p>Decimal; scale is preserved on the wire. Example: <code>"1250.00"</code>.
     *
     * @return the value, or null
     */
    public BigDecimal amount() {
        return amount;
    }

    /**
     * Members the API sent that this SDK version does not know.
     *
     * @return unmodifiable map, in wire order
     */
    public Map<String, Object> additionalProperties() {
        return additionalProperties;
    }

    @Override
    public Map<String, Object> toWire() {
        Map<String, Object> w = new LinkedHashMap<>();
        w.put("objectType", this.objectType);
        w.put("transactionType", this.transactionType);
        w.put("paymentTransactionId", this.paymentTransactionId);
        w.put("id", this.id);
        w.put("paymentTransactionLineId", this.paymentTransactionLineId);
        w.put("entity", this.entity);
        w.put("account", this.account);
        w.put("memo", this.memo);
        w.put("checkNumber", this.checkNumber);
        w.put("paymentMethod", this.paymentMethod);
        w.put("class", this.classRef);
        w.put("amount", Wire.decimalText(this.amount));
        w.putAll(this.additionalProperties);
        return w;
    }

    @Override
    public String toString() {
        return "DepositLine" + toJson();
    }
}
