// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:b5774d24bc8154ccc2acb85370ae27581a072c3f5070a529111ee2dd26f103b9
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.InputObject;
import com.desktopaccountingapi.quickbooksdesktop.core.Wire;
import java.math.BigDecimal;

/**
 * Cash back details for this deposit.
 *
 * <p>Fluent setters return this object. Fields you never set are not sent; on clearable fields, null is sent to clear the value.
 */
public final class DepositCashBackLineCreateInput extends InputObject {
    /**
     * Creates an empty object. Set the required field {@code accountId} before sending.
     */
    public DepositCashBackLineCreateInput() {
        super("accountId");
    }

    /**
     * Creates the object with its required fields.
     *
     * @param accountId ID of the account for this cash back info.
     */
    public DepositCashBackLineCreateInput(String accountId) {
        this();
        accountId(accountId);
    }

    /**
     * ID of the account for this cash back info.
     *
     * <p>Required. Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public DepositCashBackLineCreateInput accountId(String value) {
        setOptional("accountId", value);
        return this;
    }

    /**
     * The {@code accountId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String accountId() {
        return value("accountId");
    }

    /**
     * Internal memo for this cash back info; shown in reports, not on printed forms.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public DepositCashBackLineCreateInput memo(String value) {
        setOptional("memo", value);
        return this;
    }

    /**
     * The {@code memo} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String memo() {
        return value("memo");
    }

    /**
     * Amount as a decimal string.
     *
     * <p>Decimal; scale is preserved on the wire. Example: <code>"1250.00"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public DepositCashBackLineCreateInput amount(BigDecimal value) {
        setOptional("amount", Wire.decimalText(value));
        return this;
    }

    /**
     * The {@code amount} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public BigDecimal amount() {
        return Wire.decimalOrNull(value("amount"));
    }
}
