// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:1cc3058cecb557ce1cc724d5236d36860df6bec39636e2d427c8a408bf5f2ca2
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.InputObject;
import com.desktopaccountingapi.quickbooksdesktop.core.Wire;
import java.math.BigDecimal;

/**
 * Fields for creating an earnings.
 *
 * <p>Fluent setters return this object. Fields you never set are not sent; on clearable fields, null is sent to clear the value.
 */
public final class EarningInput extends InputObject {
    /**
     * Creates an empty object. Set the required field {@code payrollWageItemId} before sending.
     */
    public EarningInput() {
        super("payrollWageItemId");
    }

    /**
     * Creates the object with its required fields.
     *
     * @param payrollWageItemId ID of the payroll wage item for this earnings.
     */
    public EarningInput(String payrollWageItemId) {
        this();
        payrollWageItemId(payrollWageItemId);
    }

    /**
     * ID of the payroll wage item for this earnings.
     *
     * <p>Required. Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public EarningInput payrollWageItemId(String value) {
        setOptional("payrollWageItemId", value);
        return this;
    }

    /**
     * The {@code payrollWageItemId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String payrollWageItemId() {
        return value("payrollWageItemId");
    }

    /**
     * Price per unit, as a decimal string. Cannot be combined with ratePercent.
     *
     * <p>Decimal; scale is preserved on the wire. Example: <code>"19.99"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public EarningInput rate(BigDecimal value) {
        setOptional("rate", Wire.decimalText(value));
        return this;
    }

    /**
     * The {@code rate} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public BigDecimal rate() {
        return Wire.decimalOrNull(value("rate"));
    }

    /**
     * Price as a percentage, for percentage-based items. Percentage as a decimal string: "7.5" means 7.5 %. Cannot be combined with rate.
     *
     * <p>Decimal; scale is preserved on the wire. Example: <code>"7.5"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public EarningInput ratePercent(BigDecimal value) {
        setOptional("ratePercent", Wire.decimalText(value));
        return this;
    }

    /**
     * The {@code ratePercent} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public BigDecimal ratePercent() {
        return Wire.decimalOrNull(value("ratePercent"));
    }
}
