// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:68a0d76d6b51187adfc66d768eae8e30675b5093f4ae538b0d9c32c905b9bb2d
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.InputObject;

/**
 * Emergency contact details for this employee.
 *
 * <p>Fluent setters return this object. Fields you never set are not sent; on clearable fields, null is sent to clear the value.
 */
public final class EmergencyContactInput extends InputObject {
    /**
     * Creates an empty object.
     */
    public EmergencyContactInput() {
        super();
    }

    /**
     * The {@code primaryContact} field.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public EmergencyContactInput primaryContact(PrimaryContactInput value) {
        setOptional("primaryContact", value);
        return this;
    }

    /**
     * The {@code primaryContact} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public PrimaryContactInput primaryContact() {
        return value("primaryContact");
    }

    /**
     * The {@code secondaryContact} field.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public EmergencyContactInput secondaryContact(SecondaryContactInput value) {
        setOptional("secondaryContact", value);
        return this;
    }

    /**
     * The {@code secondaryContact} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public SecondaryContactInput secondaryContact() {
        return value("secondaryContact");
    }
}
