// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:b5774d24bc8154ccc2acb85370ae27581a072c3f5070a529111ee2dd26f103b9
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code EmployeeCreateInputUsCitizenshipStatus} values.
 *
 * <p>Allowed values.
 */
public final class EmployeeCreateInputUsCitizenshipStatus {
    private EmployeeCreateInputUsCitizenshipStatus() {}

    /** {@code citizen} */
    public static final String CITIZEN = "citizen";

    /** {@code non_citizen} */
    public static final String NON_CITIZEN = "non_citizen";
}
