// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:79b06eb2008381661d24d3bd5e23643483ec1bf9b70d5f4cdff2a2a71e22fe94
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code EmployeeCreateInputI9OnFileStatus} values.
 *
 * <p>Allowed values.
 */
public final class EmployeeCreateInputI9OnFileStatus {
    private EmployeeCreateInputI9OnFileStatus() {}

    /** {@code on_file} */
    public static final String ON_FILE = "on_file";

    /** {@code not_on_file} */
    public static final String NOT_ON_FILE = "not_on_file";
}
