// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:6f5ac28d7c33ac90aa7e2c15d88efd50e8e41c808bcc5489f0c8b1cb7833326a
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code EmployeeEthnicity} values.
 *
 * <p>Known values of an open set. The API may return values not listed here; treat unknown values as valid.
 */
public final class EmployeeEthnicity {
    private EmployeeEthnicity() {}

    /** {@code american_indian} */
    public static final String AMERICAN_INDIAN = "american_indian";

    /** {@code asian} */
    public static final String ASIAN = "asian";

    /** {@code black} */
    public static final String BLACK = "black";

    /** {@code hawaiian} */
    public static final String HAWAIIAN = "hawaiian";

    /** {@code hispanic} */
    public static final String HISPANIC = "hispanic";

    /** {@code white} */
    public static final String WHITE = "white";

    /** {@code two_or_more_races} */
    public static final String TWO_OR_MORE_RACES = "two_or_more_races";
}
