// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:1fc5496cc47b442606ea78c818f94a29798b32785dc14c59e7986e24f10bf332
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code EmployeePayrollUseTimeDataToCreatePaychecks} values.
 *
 * <p>Known values of an open set. The API may return values not listed here; treat unknown values as valid.
 */
public final class EmployeePayrollUseTimeDataToCreatePaychecks {
    private EmployeePayrollUseTimeDataToCreatePaychecks() {}

    /** {@code not_set} */
    public static final String NOT_SET = "not_set";

    /** {@code uses_time_data} */
    public static final String USES_TIME_DATA = "uses_time_data";

    /** {@code does_not_use_time_data} */
    public static final String DOES_NOT_USE_TIME_DATA = "does_not_use_time_data";
}
