// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:1cc3058cecb557ce1cc724d5236d36860df6bec39636e2d427c8a408bf5f2ca2
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.Json;
import com.desktopaccountingapi.quickbooksdesktop.core.JsonWritable;
import com.desktopaccountingapi.quickbooksdesktop.core.Wire;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Employee payroll info as stored in QuickBooks Desktop.
 *
 * <p>Parsed tolerantly: unknown members go to {@link #additionalProperties()} and missing members read as null. {@link #toJson()} writes the wire form back.
 */
public final class EmployeePayroll implements JsonWritable {
    private static final Set<String> KNOWN = new HashSet<>(Arrays.asList("payPeriod", "class", "deleteAllEarnings", "earnings", "useTimeDataToCreatePaychecks", "sickHours", "vacationHours"));

    private String payPeriod;
    private Reference classRef;
    private Boolean deleteAllEarnings;
    private List<Earning> earnings;
    private String useTimeDataToCreatePaychecks;
    private SickHour sickHours;
    private VacationHour vacationHours;
    private Map<String, Object> additionalProperties = Collections.emptyMap();

    private EmployeePayroll() {}

    /**
     * Reads the object from parsed JSON (see {@code Json.parse}).
     *
     * @param json parsed JSON object
     * @return the object
     * @throws com.desktopaccountingapi.quickbooksdesktop.core.Json.JsonException if a member has the wrong JSON type
     */
    public static EmployeePayroll fromJson(Object json) {
        Map<String, Object> o = Wire.object(json, "EmployeePayroll");
        EmployeePayroll m = new EmployeePayroll();
        m.payPeriod = Wire.get(o, "payPeriod", Wire::asString);
        m.classRef = Wire.get(o, "class", Reference::fromJson);
        m.deleteAllEarnings = Wire.get(o, "deleteAllEarnings", Wire::asBoolean);
        m.earnings = Wire.list(o, "earnings", Earning::fromJson);
        m.useTimeDataToCreatePaychecks = Wire.get(o, "useTimeDataToCreatePaychecks", Wire::asString);
        m.sickHours = Wire.get(o, "sickHours", SickHour::fromJson);
        m.vacationHours = Wire.get(o, "vacationHours", VacationHour::fromJson);
        m.additionalProperties = Wire.extra(o, KNOWN);
        return m;
    }

    /**
     * Parses the object from JSON text.
     *
     * @param json JSON text
     * @return the object
     */
    public static EmployeePayroll parse(String json) {
        return fromJson(Json.parse(json));
    }

    /**
     * Pay period of this employee payroll info.
     *
     * <p>Known values are in {@link EmployeePayrollPayPeriod}; other values may appear.
     *
     * @return the value, or null
     */
    public String payPeriod() {
        return payPeriod;
    }

    /**
     * The class for this employee payroll info.
     *
     * @return the value, or null
     */
    public Reference classRef() {
        return classRef;
    }

    /**
     * Delete all earnings of this employee payroll info.
     *
     * @return the value, or null
     */
    public Boolean deleteAllEarnings() {
        return deleteAllEarnings;
    }

    /**
     * Earnings entries for this employee payroll info.
     *
     * @return the value (null only if the API omitted it)
     */
    public List<Earning> earnings() {
        return earnings;
    }

    /**
     * Use time data to create paychecks of this employee payroll info.
     *
     * <p>Known values are in {@link EmployeePayrollUseTimeDataToCreatePaychecks}; other values may appear.
     *
     * @return the value, or null
     */
    public String useTimeDataToCreatePaychecks() {
        return useTimeDataToCreatePaychecks;
    }

    /**
     * Sick hours details for this employee payroll info.
     *
     * @return the value, or null
     */
    public SickHour sickHours() {
        return sickHours;
    }

    /**
     * Vacation hours details for this employee payroll info.
     *
     * @return the value, or null
     */
    public VacationHour vacationHours() {
        return vacationHours;
    }

    /**
     * Members the API sent that this SDK version does not know.
     *
     * @return unmodifiable map, in wire order
     */
    public Map<String, Object> additionalProperties() {
        return additionalProperties;
    }

    @Override
    public Map<String, Object> toWire() {
        Map<String, Object> w = new LinkedHashMap<>();
        w.put("payPeriod", this.payPeriod);
        w.put("class", this.classRef);
        w.put("deleteAllEarnings", this.deleteAllEarnings);
        w.put("earnings", this.earnings);
        w.put("useTimeDataToCreatePaychecks", this.useTimeDataToCreatePaychecks);
        w.put("sickHours", this.sickHours);
        w.put("vacationHours", this.vacationHours);
        w.putAll(this.additionalProperties);
        return w;
    }

    @Override
    public String toString() {
        return "EmployeePayroll" + toJson();
    }
}
