// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:b5774d24bc8154ccc2acb85370ae27581a072c3f5070a529111ee2dd26f103b9
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.InputObject;
import java.time.LocalDate;
import java.util.List;

/**
 * Fields for creating an estimate. Requires at least one of: lines or lineGroups.
 *
 * <p>Fluent setters return this object. Fields you never set are not sent; on clearable fields, null is sent to clear the value.
 */
public final class EstimateCreateInput extends InputObject {
    /**
     * Creates an empty object. Set the required field {@code customerId} before sending.
     */
    public EstimateCreateInput() {
        super("customerId");
    }

    /**
     * Creates the object with its required fields.
     *
     * @param customerId ID of the customer for this estimate.
     */
    public EstimateCreateInput(String customerId) {
        this();
        customerId(customerId);
    }

    /**
     * ID of the customer for this estimate.
     *
     * <p>Required. Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public EstimateCreateInput customerId(String value) {
        setOptional("customerId", value);
        return this;
    }

    /**
     * The {@code customerId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String customerId() {
        return value("customerId");
    }

    /**
     * ID of the class for this estimate.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public EstimateCreateInput classId(String value) {
        setOptional("classId", value);
        return this;
    }

    /**
     * The {@code classId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String classId() {
        return value("classId");
    }

    /**
     * ID of the document template for this estimate.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public EstimateCreateInput documentTemplateId(String value) {
        setOptional("documentTemplateId", value);
        return this;
    }

    /**
     * The {@code documentTemplateId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String documentTemplateId() {
        return value("documentTemplateId");
    }

    /**
     * Date of this estimate (YYYY-MM-DD).
     *
     * <p>Example: <code>"2026-10-05"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public EstimateCreateInput transactionDate(LocalDate value) {
        setOptional("transactionDate", value);
        return this;
    }

    /**
     * The {@code transactionDate} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public LocalDate transactionDate() {
        return value("transactionDate");
    }

    /**
     * Reference number of this estimate, such as an invoice or check number. Case-sensitive.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public EstimateCreateInput refNumber(String value) {
        setOptional("refNumber", value);
        return this;
    }

    /**
     * The {@code refNumber} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String refNumber() {
        return value("refNumber");
    }

    /**
     * Billing address for this estimate.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public EstimateCreateInput billingAddress(AddressCreateInput value) {
        setOptional("billingAddress", value);
        return this;
    }

    /**
     * The {@code billingAddress} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public AddressCreateInput billingAddress() {
        return value("billingAddress");
    }

    /**
     * Shipping address for this estimate.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public EstimateCreateInput shippingAddress(AddressCreateInput value) {
        setOptional("shippingAddress", value);
        return this;
    }

    /**
     * The {@code shippingAddress} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public AddressCreateInput shippingAddress() {
        return value("shippingAddress");
    }

    /**
     * Whether this estimate is active. Inactive objects stay in QuickBooks but are hidden from most lists.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public EstimateCreateInput isActive(Boolean value) {
        setOptional("isActive", value);
        return this;
    }

    /**
     * The {@code isActive} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Boolean isActive() {
        return value("isActive");
    }

    /**
     * Purchase order number of this estimate.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public EstimateCreateInput purchaseOrderNumber(String value) {
        setOptional("purchaseOrderNumber", value);
        return this;
    }

    /**
     * The {@code purchaseOrderNumber} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String purchaseOrderNumber() {
        return value("purchaseOrderNumber");
    }

    /**
     * ID of the terms for this estimate.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public EstimateCreateInput termsId(String value) {
        setOptional("termsId", value);
        return this;
    }

    /**
     * The {@code termsId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String termsId() {
        return value("termsId");
    }

    /**
     * Date payment of this estimate is due (YYYY-MM-DD).
     *
     * <p>Example: <code>"2026-10-05"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public EstimateCreateInput dueDate(LocalDate value) {
        setOptional("dueDate", value);
        return this;
    }

    /**
     * The {@code dueDate} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public LocalDate dueDate() {
        return value("dueDate");
    }

    /**
     * ID of the sales representative for this estimate.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public EstimateCreateInput salesRepresentativeId(String value) {
        setOptional("salesRepresentativeId", value);
        return this;
    }

    /**
     * The {@code salesRepresentativeId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String salesRepresentativeId() {
        return value("salesRepresentativeId");
    }

    /**
     * Shipment origin of this estimate.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public EstimateCreateInput shipmentOrigin(String value) {
        setOptional("shipmentOrigin", value);
        return this;
    }

    /**
     * The {@code shipmentOrigin} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String shipmentOrigin() {
        return value("shipmentOrigin");
    }

    /**
     * ID of the sales tax item for this estimate.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public EstimateCreateInput salesTaxItemId(String value) {
        setOptional("salesTaxItemId", value);
        return this;
    }

    /**
     * The {@code salesTaxItemId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String salesTaxItemId() {
        return value("salesTaxItemId");
    }

    /**
     * Internal memo for this estimate; shown in reports, not on printed forms.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public EstimateCreateInput memo(String value) {
        setOptional("memo", value);
        return this;
    }

    /**
     * The {@code memo} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String memo() {
        return value("memo");
    }

    /**
     * ID of the customer message for this estimate.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public EstimateCreateInput customerMessageId(String value) {
        setOptional("customerMessageId", value);
        return this;
    }

    /**
     * The {@code customerMessageId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String customerMessageId() {
        return value("customerMessageId");
    }

    /**
     * Whether this estimate is in the queue of forms to email.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public EstimateCreateInput isQueuedForEmail(Boolean value) {
        setOptional("isQueuedForEmail", value);
        return this;
    }

    /**
     * The {@code isQueuedForEmail} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Boolean isQueuedForEmail() {
        return value("isQueuedForEmail");
    }

    /**
     * ID of the sales tax code for this estimate.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public EstimateCreateInput salesTaxCodeId(String value) {
        setOptional("salesTaxCodeId", value);
        return this;
    }

    /**
     * The {@code salesTaxCodeId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String salesTaxCodeId() {
        return value("salesTaxCodeId");
    }

    /**
     * Built-in "Other" text field on this estimate.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public EstimateCreateInput otherCustomField(String value) {
        setOptional("otherCustomField", value);
        return this;
    }

    /**
     * The {@code otherCustomField} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String otherCustomField() {
        return value("otherCustomField");
    }

    /**
     * Exchange rate from this estimate's currency to the home currency.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public EstimateCreateInput exchangeRate(Double value) {
        setOptional("exchangeRate", value);
        return this;
    }

    /**
     * Exchange rate from this estimate's currency to the home currency.
     *
     * @param value the value
     * @return this object
     */
    public EstimateCreateInput exchangeRate(double value) {
        setOptional("exchangeRate", value);
        return this;
    }

    /**
     * The {@code exchangeRate} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Double exchangeRate() {
        return value("exchangeRate");
    }

    /**
     * Your own UUID for this estimate, stored by QuickBooks so you can match records with your system.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public EstimateCreateInput externalId(String value) {
        setOptional("externalId", value);
        return this;
    }

    /**
     * The {@code externalId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String externalId() {
        return value("externalId");
    }

    /**
     * Line items of this estimate.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public EstimateCreateInput lines(List<EstimateLineCreateInput> value) {
        setOptional("lines", value);
        return this;
    }

    /**
     * The {@code lines} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public List<EstimateLineCreateInput> lines() {
        return value("lines");
    }

    /**
     * Group lines of this estimate: each expands an item group into its component lines.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public EstimateCreateInput lineGroups(List<EstimateLineGroupCreateInput> value) {
        setOptional("lineGroups", value);
        return this;
    }

    /**
     * The {@code lineGroups} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public List<EstimateLineGroupCreateInput> lineGroups() {
        return value("lineGroups");
    }
}
