// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:79b06eb2008381661d24d3bd5e23643483ec1bf9b70d5f4cdff2a2a71e22fe94
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.Json;
import com.desktopaccountingapi.quickbooksdesktop.core.JsonWritable;
import com.desktopaccountingapi.quickbooksdesktop.core.Wire;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;

/**
 * Finance charge preferences as stored in QuickBooks Desktop.
 *
 * <p>Parsed tolerantly: unknown members go to {@link #additionalProperties()} and missing members read as null. {@link #toJson()} writes the wire form back.
 */
public final class FinanceCharge implements JsonWritable {
    private static final Set<String> KNOWN = new HashSet<>(Arrays.asList("annualInterestRate", "minimumFinanceCharge", "gracePeriod", "financeChargeAccount", "isAssessingForOverdueCharges", "calculateChargesFrom", "isMarkedToBePrinted"));

    private Double annualInterestRate;
    private Double minimumFinanceCharge;
    private Integer gracePeriod;
    private Reference financeChargeAccount;
    private Boolean isAssessingForOverdueCharges;
    private String calculateChargesFrom;
    private Boolean isMarkedToBePrinted;
    private Map<String, Object> additionalProperties = Collections.emptyMap();

    private FinanceCharge() {}

    /**
     * Reads the object from parsed JSON (see {@code Json.parse}).
     *
     * @param json parsed JSON object
     * @return the object
     * @throws com.desktopaccountingapi.quickbooksdesktop.core.Json.JsonException if a member has the wrong JSON type
     */
    public static FinanceCharge fromJson(Object json) {
        Map<String, Object> o = Wire.object(json, "FinanceCharge");
        FinanceCharge m = new FinanceCharge();
        m.annualInterestRate = Wire.get(o, "annualInterestRate", Wire::asDouble);
        m.minimumFinanceCharge = Wire.get(o, "minimumFinanceCharge", Wire::asDouble);
        m.gracePeriod = Wire.get(o, "gracePeriod", Wire::asInteger);
        m.financeChargeAccount = Wire.get(o, "financeChargeAccount", Reference::fromJson);
        m.isAssessingForOverdueCharges = Wire.get(o, "isAssessingForOverdueCharges", Wire::asBoolean);
        m.calculateChargesFrom = Wire.get(o, "calculateChargesFrom", Wire::asString);
        m.isMarkedToBePrinted = Wire.get(o, "isMarkedToBePrinted", Wire::asBoolean);
        m.additionalProperties = Wire.extra(o, KNOWN);
        return m;
    }

    /**
     * Parses the object from JSON text.
     *
     * @param json JSON text
     * @return the object
     */
    public static FinanceCharge parse(String json) {
        return fromJson(Json.parse(json));
    }

    /**
     * Annual interest rate of this finance charge preferences.
     *
     * @return the value, or null
     */
    public Double annualInterestRate() {
        return annualInterestRate;
    }

    /**
     * Minimum finance charge of this finance charge preferences. A number with up to 2 decimal places.
     *
     * @return the value, or null
     */
    public Double minimumFinanceCharge() {
        return minimumFinanceCharge;
    }

    /**
     * Grace period of this finance charge preferences.
     *
     * @return the value, or null
     */
    public Integer gracePeriod() {
        return gracePeriod;
    }

    /**
     * The finance charge account for this finance charge preferences.
     *
     * @return the value, or null
     */
    public Reference financeChargeAccount() {
        return financeChargeAccount;
    }

    /**
     * Whether this finance charge preferences is assessing for overdue charges.
     *
     * @return the value, or null
     */
    public Boolean isAssessingForOverdueCharges() {
        return isAssessingForOverdueCharges;
    }

    /**
     * Calculate charges from of this finance charge preferences.
     *
     * <p>Known values are in {@link FinanceChargeCalculateChargesFrom}; other values may appear.
     *
     * @return the value, or null
     */
    public String calculateChargesFrom() {
        return calculateChargesFrom;
    }

    /**
     * Whether this finance charge preferences is marked to be printed.
     *
     * @return the value, or null
     */
    public Boolean isMarkedToBePrinted() {
        return isMarkedToBePrinted;
    }

    /**
     * Members the API sent that this SDK version does not know.
     *
     * @return unmodifiable map, in wire order
     */
    public Map<String, Object> additionalProperties() {
        return additionalProperties;
    }

    @Override
    public Map<String, Object> toWire() {
        Map<String, Object> w = new LinkedHashMap<>();
        w.put("annualInterestRate", this.annualInterestRate);
        w.put("minimumFinanceCharge", this.minimumFinanceCharge);
        w.put("gracePeriod", this.gracePeriod);
        w.put("financeChargeAccount", this.financeChargeAccount);
        w.put("isAssessingForOverdueCharges", this.isAssessingForOverdueCharges);
        w.put("calculateChargesFrom", this.calculateChargesFrom);
        w.put("isMarkedToBePrinted", this.isMarkedToBePrinted);
        w.putAll(this.additionalProperties);
        return w;
    }

    @Override
    public String toString() {
        return "FinanceCharge" + toJson();
    }
}
