// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:b5774d24bc8154ccc2acb85370ae27581a072c3f5070a529111ee2dd26f103b9
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code InventoryAdjustmentLineSerialNumberAction} values.
 *
 * <p>Known values of an open set. The API may return values not listed here; treat unknown values as valid.
 */
public final class InventoryAdjustmentLineSerialNumberAction {
    private InventoryAdjustmentLineSerialNumberAction() {}

    /** {@code added} */
    public static final String ADDED = "added";

    /** {@code removed} */
    public static final String REMOVED = "removed";
}
