// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:3d102b7bcecbf18e72b655745e5c55d641457fab2fd8184b3da643aeb51bb76f
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.Json;
import com.desktopaccountingapi.quickbooksdesktop.core.JsonWritable;
import com.desktopaccountingapi.quickbooksdesktop.core.Wire;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Inventory adjustment as stored in QuickBooks Desktop.
 *
 * <p>Parsed tolerantly: unknown members go to {@link #additionalProperties()} and missing members read as null. {@link #toJson()} writes the wire form back.
 */
public final class InventoryAdjustment implements JsonWritable {
    private static final Set<String> KNOWN = new HashSet<>(Arrays.asList("id", "objectType", "createdAt", "updatedAt", "revisionNumber", "transactionNumber", "account", "inventorySite", "transactionDate", "refNumber", "customer", "class", "memo", "externalId", "lines", "customFields"));

    private String id;
    private String objectType;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;
    private String revisionNumber;
    private Integer transactionNumber;
    private Reference account;
    private Reference inventorySite;
    private LocalDate transactionDate;
    private String refNumber;
    private Reference customer;
    private Reference classRef;
    private String memo;
    private String externalId;
    private List<InventoryAdjustmentLine> lines;
    private List<CustomField> customFields;
    private Map<String, Object> additionalProperties = Collections.emptyMap();

    private InventoryAdjustment() {}

    /**
     * Reads the object from parsed JSON (see {@code Json.parse}).
     *
     * @param json parsed JSON object
     * @return the object
     * @throws com.desktopaccountingapi.quickbooksdesktop.core.Json.JsonException if a member has the wrong JSON type
     */
    public static InventoryAdjustment fromJson(Object json) {
        Map<String, Object> o = Wire.object(json, "InventoryAdjustment");
        InventoryAdjustment m = new InventoryAdjustment();
        m.id = Wire.get(o, "id", Wire::asString);
        m.objectType = Wire.get(o, "objectType", Wire::asString);
        m.createdAt = Wire.get(o, "createdAt", Wire::asDateTime);
        m.updatedAt = Wire.get(o, "updatedAt", Wire::asDateTime);
        m.revisionNumber = Wire.get(o, "revisionNumber", Wire::asString);
        m.transactionNumber = Wire.get(o, "transactionNumber", Wire::asInteger);
        m.account = Wire.get(o, "account", Reference::fromJson);
        m.inventorySite = Wire.get(o, "inventorySite", Reference::fromJson);
        m.transactionDate = Wire.get(o, "transactionDate", Wire::asDate);
        m.refNumber = Wire.get(o, "refNumber", Wire::asString);
        m.customer = Wire.get(o, "customer", Reference::fromJson);
        m.classRef = Wire.get(o, "class", Reference::fromJson);
        m.memo = Wire.get(o, "memo", Wire::asString);
        m.externalId = Wire.get(o, "externalId", Wire::asString);
        m.lines = Wire.list(o, "lines", InventoryAdjustmentLine::fromJson);
        m.customFields = Wire.list(o, "customFields", CustomField::fromJson);
        m.additionalProperties = Wire.extra(o, KNOWN);
        return m;
    }

    /**
     * Parses the object from JSON text.
     *
     * @param json JSON text
     * @return the object
     */
    public static InventoryAdjustment parse(String json) {
        return fromJson(Json.parse(json));
    }

    /**
     * QuickBooks-assigned ID of this inventory adjustment.
     *
     * @return the value (null only if the API omitted it)
     */
    public String id() {
        return id;
    }

    /**
     * Type of this object.
     *
     * @return the value (null only if the API omitted it)
     */
    public String objectType() {
        return objectType;
    }

    /**
     * When this inventory adjustment was created, as an ISO 8601 date-time with the QuickBooks computer's UTC offset.
     *
     * <p>Example: <code>"2026-10-05T09:14:03-07:00"</code>.
     *
     * @return the value (null only if the API omitted it)
     */
    public OffsetDateTime createdAt() {
        return createdAt;
    }

    /**
     * When this inventory adjustment was last changed, as an ISO 8601 date-time with the QuickBooks computer's UTC offset. Whole seconds: a second change within the same second keeps this value, so incremental syncs should overlap `updatedAfter` and deduplicate by `id` and `revisionNumber`.
     *
     * <p>Example: <code>"2026-10-05T09:14:03-07:00"</code>.
     *
     * @return the value (null only if the API omitted it)
     */
    public OffsetDateTime updatedAt() {
        return updatedAt;
    }

    /**
     * Current revision of this inventory adjustment. Send it unchanged when updating; a stale value is rejected. QuickBooks changes it at most once per second, so a second edit within the same second keeps the same value. This API spaces its own consecutive writes to one object by over a second; edits made elsewhere in the same second are not detected.
     *
     * @return the value (null only if the API omitted it)
     */
    public String revisionNumber() {
        return revisionNumber;
    }

    /**
     * Sequential transaction number QuickBooks assigns internally.
     *
     * @return the value, or null
     */
    public Integer transactionNumber() {
        return transactionNumber;
    }

    /**
     * The account for this inventory adjustment.
     *
     * @return the value, or null
     */
    public Reference account() {
        return account;
    }

    /**
     * The inventory site for this inventory adjustment.
     *
     * @return the value, or null
     */
    public Reference inventorySite() {
        return inventorySite;
    }

    /**
     * Date of this inventory adjustment (YYYY-MM-DD).
     *
     * <p>Example: <code>"2026-10-05"</code>.
     *
     * @return the value, or null
     */
    public LocalDate transactionDate() {
        return transactionDate;
    }

    /**
     * Reference number of this inventory adjustment, such as an invoice or check number. Case-sensitive.
     *
     * @return the value, or null
     */
    public String refNumber() {
        return refNumber;
    }

    /**
     * The customer for this inventory adjustment.
     *
     * @return the value, or null
     */
    public Reference customer() {
        return customer;
    }

    /**
     * The class for this inventory adjustment.
     *
     * @return the value, or null
     */
    public Reference classRef() {
        return classRef;
    }

    /**
     * Internal memo for this inventory adjustment; shown in reports, not on printed forms.
     *
     * @return the value, or null
     */
    public String memo() {
        return memo;
    }

    /**
     * Your own UUID for this inventory adjustment, stored by QuickBooks so you can match records with your system.
     *
     * @return the value, or null
     */
    public String externalId() {
        return externalId;
    }

    /**
     * Line items of this inventory adjustment.
     *
     * @return the value (null only if the API omitted it)
     */
    public List<InventoryAdjustmentLine> lines() {
        return lines;
    }

    /**
     * Custom field values QuickBooks stores on this inventory adjustment.
     *
     * @return the value (null only if the API omitted it)
     */
    public List<CustomField> customFields() {
        return customFields;
    }

    /**
     * Members the API sent that this SDK version does not know.
     *
     * @return unmodifiable map, in wire order
     */
    public Map<String, Object> additionalProperties() {
        return additionalProperties;
    }

    @Override
    public Map<String, Object> toWire() {
        Map<String, Object> w = new LinkedHashMap<>();
        w.put("id", this.id);
        w.put("objectType", this.objectType);
        w.put("createdAt", this.createdAt);
        w.put("updatedAt", this.updatedAt);
        w.put("revisionNumber", this.revisionNumber);
        w.put("transactionNumber", this.transactionNumber);
        w.put("account", this.account);
        w.put("inventorySite", this.inventorySite);
        w.put("transactionDate", this.transactionDate);
        w.put("refNumber", this.refNumber);
        w.put("customer", this.customer);
        w.put("class", this.classRef);
        w.put("memo", this.memo);
        w.put("externalId", this.externalId);
        w.put("lines", this.lines);
        w.put("customFields", this.customFields);
        w.putAll(this.additionalProperties);
        return w;
    }

    @Override
    public String toString() {
        return "InventoryAdjustment" + toJson();
    }
}
