// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:68a0d76d6b51187adfc66d768eae8e30675b5093f4ae538b0d9c32c905b9bb2d
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.InputObject;
import com.desktopaccountingapi.quickbooksdesktop.core.Wire;
import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * Fields for creating an inventory item.
 *
 * <p>Fluent setters return this object. Fields you never set are not sent; on clearable fields, null is sent to clear the value.
 */
public final class InventoryItemCreateInput extends InputObject {
    /**
     * Creates an empty object. Set the required field {@code name} before sending.
     */
    public InventoryItemCreateInput() {
        super("name");
    }

    /**
     * Creates the object with its required fields.
     *
     * @param name Name of this inventory item, unique within its parent level.
     */
    public InventoryItemCreateInput(String name) {
        this();
        name(name);
    }

    /**
     * Name of this inventory item, unique within its parent level.
     *
     * <p>Required.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public InventoryItemCreateInput name(String value) {
        setOptional("name", value);
        return this;
    }

    /**
     * The {@code name} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String name() {
        return value("name");
    }

    /**
     * Barcode details for this inventory item.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public InventoryItemCreateInput barcode(BarcodeCreateInput value) {
        setOptional("barcode", value);
        return this;
    }

    /**
     * The {@code barcode} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public BarcodeCreateInput barcode() {
        return value("barcode");
    }

    /**
     * Whether this inventory item is active. Inactive objects stay in QuickBooks but are hidden from most lists.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public InventoryItemCreateInput isActive(Boolean value) {
        setOptional("isActive", value);
        return this;
    }

    /**
     * The {@code isActive} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Boolean isActive() {
        return value("isActive");
    }

    /**
     * ID of the class for this inventory item.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public InventoryItemCreateInput classId(String value) {
        setOptional("classId", value);
        return this;
    }

    /**
     * The {@code classId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String classId() {
        return value("classId");
    }

    /**
     * ID of the parent object, making this inventory item a child in the hierarchy.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public InventoryItemCreateInput parentId(String value) {
        setOptional("parentId", value);
        return this;
    }

    /**
     * The {@code parentId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String parentId() {
        return value("parentId");
    }

    /**
     * Sku of this inventory item.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public InventoryItemCreateInput sku(String value) {
        setOptional("sku", value);
        return this;
    }

    /**
     * The {@code sku} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String sku() {
        return value("sku");
    }

    /**
     * ID of the unit of measure set for this inventory item.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public InventoryItemCreateInput unitOfMeasureSetId(String value) {
        setOptional("unitOfMeasureSetId", value);
        return this;
    }

    /**
     * The {@code unitOfMeasureSetId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String unitOfMeasureSetId() {
        return value("unitOfMeasureSetId");
    }

    /**
     * ID of the sales tax code for this inventory item.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public InventoryItemCreateInput salesTaxCodeId(String value) {
        setOptional("salesTaxCodeId", value);
        return this;
    }

    /**
     * The {@code salesTaxCodeId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String salesTaxCodeId() {
        return value("salesTaxCodeId");
    }

    /**
     * Sales description of this inventory item.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public InventoryItemCreateInput salesDescription(String value) {
        setOptional("salesDescription", value);
        return this;
    }

    /**
     * The {@code salesDescription} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String salesDescription() {
        return value("salesDescription");
    }

    /**
     * Sales price of this inventory item. Decimal string with up to 5 decimal places.
     *
     * <p>Decimal; scale is preserved on the wire. Example: <code>"19.99"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public InventoryItemCreateInput salesPrice(BigDecimal value) {
        setOptional("salesPrice", Wire.decimalText(value));
        return this;
    }

    /**
     * The {@code salesPrice} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public BigDecimal salesPrice() {
        return Wire.decimalOrNull(value("salesPrice"));
    }

    /**
     * ID of the income account for this inventory item.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public InventoryItemCreateInput incomeAccountId(String value) {
        setOptional("incomeAccountId", value);
        return this;
    }

    /**
     * The {@code incomeAccountId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String incomeAccountId() {
        return value("incomeAccountId");
    }

    /**
     * Purchase description of this inventory item.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public InventoryItemCreateInput purchaseDescription(String value) {
        setOptional("purchaseDescription", value);
        return this;
    }

    /**
     * The {@code purchaseDescription} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String purchaseDescription() {
        return value("purchaseDescription");
    }

    /**
     * Purchase cost of this inventory item. Decimal string with up to 5 decimal places.
     *
     * <p>Decimal; scale is preserved on the wire. Example: <code>"19.99"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public InventoryItemCreateInput purchaseCost(BigDecimal value) {
        setOptional("purchaseCost", Wire.decimalText(value));
        return this;
    }

    /**
     * The {@code purchaseCost} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public BigDecimal purchaseCost() {
        return Wire.decimalOrNull(value("purchaseCost"));
    }

    /**
     * ID of the cogs account for this inventory item.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public InventoryItemCreateInput cogsAccountId(String value) {
        setOptional("cogsAccountId", value);
        return this;
    }

    /**
     * The {@code cogsAccountId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String cogsAccountId() {
        return value("cogsAccountId");
    }

    /**
     * ID of the preferred vendor for this inventory item.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public InventoryItemCreateInput preferredVendorId(String value) {
        setOptional("preferredVendorId", value);
        return this;
    }

    /**
     * The {@code preferredVendorId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String preferredVendorId() {
        return value("preferredVendorId");
    }

    /**
     * ID of the asset account for this inventory item.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public InventoryItemCreateInput assetAccountId(String value) {
        setOptional("assetAccountId", value);
        return this;
    }

    /**
     * The {@code assetAccountId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String assetAccountId() {
        return value("assetAccountId");
    }

    /**
     * Reorder point of this inventory item.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public InventoryItemCreateInput reorderPoint(Double value) {
        setOptional("reorderPoint", value);
        return this;
    }

    /**
     * Reorder point of this inventory item.
     *
     * @param value the value
     * @return this object
     */
    public InventoryItemCreateInput reorderPoint(double value) {
        setOptional("reorderPoint", value);
        return this;
    }

    /**
     * The {@code reorderPoint} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Double reorderPoint() {
        return value("reorderPoint");
    }

    /**
     * Maximum quantity on hand of this inventory item.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public InventoryItemCreateInput maximumQuantityOnHand(Double value) {
        setOptional("maximumQuantityOnHand", value);
        return this;
    }

    /**
     * Maximum quantity on hand of this inventory item.
     *
     * @param value the value
     * @return this object
     */
    public InventoryItemCreateInput maximumQuantityOnHand(double value) {
        setOptional("maximumQuantityOnHand", value);
        return this;
    }

    /**
     * The {@code maximumQuantityOnHand} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Double maximumQuantityOnHand() {
        return value("maximumQuantityOnHand");
    }

    /**
     * Quantity on hand of this inventory item.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public InventoryItemCreateInput quantityOnHand(Double value) {
        setOptional("quantityOnHand", value);
        return this;
    }

    /**
     * Quantity on hand of this inventory item.
     *
     * @param value the value
     * @return this object
     */
    public InventoryItemCreateInput quantityOnHand(double value) {
        setOptional("quantityOnHand", value);
        return this;
    }

    /**
     * The {@code quantityOnHand} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Double quantityOnHand() {
        return value("quantityOnHand");
    }

    /**
     * Total value of this inventory item. Decimal string with up to 2 decimal places.
     *
     * <p>Decimal; scale is preserved on the wire. Example: <code>"1250.00"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public InventoryItemCreateInput totalValue(BigDecimal value) {
        setOptional("totalValue", Wire.decimalText(value));
        return this;
    }

    /**
     * The {@code totalValue} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public BigDecimal totalValue() {
        return Wire.decimalOrNull(value("totalValue"));
    }

    /**
     * Inventory date (YYYY-MM-DD).
     *
     * <p>Example: <code>"2026-10-05"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public InventoryItemCreateInput inventoryDate(LocalDate value) {
        setOptional("inventoryDate", value);
        return this;
    }

    /**
     * The {@code inventoryDate} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public LocalDate inventoryDate() {
        return value("inventoryDate");
    }

    /**
     * Your own UUID for this inventory item, stored by QuickBooks so you can match records with your system.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public InventoryItemCreateInput externalId(String value) {
        setOptional("externalId", value);
        return this;
    }

    /**
     * The {@code externalId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String externalId() {
        return value("externalId");
    }
}
