// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:68a0d76d6b51187adfc66d768eae8e30675b5093f4ae538b0d9c32c905b9bb2d
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.InputObject;
import com.desktopaccountingapi.quickbooksdesktop.core.Wire;
import java.math.BigDecimal;

/**
 * Fields for updating an item line.
 *
 * <p>Fluent setters return this object. Fields you never set are not sent; on clearable fields, null is sent to clear the value.
 */
public final class ItemLineUpdateInput extends InputObject {
    /**
     * Creates an empty object. Set the required field {@code id} before sending.
     */
    public ItemLineUpdateInput() {
        super("id");
    }

    /**
     * Creates the object with its required fields.
     *
     * @param id QuickBooks-assigned ID of this item line. Use "-1" to add a new line.
     */
    public ItemLineUpdateInput(String id) {
        this();
        id(id);
    }

    /**
     * QuickBooks-assigned ID of this item line. Use "-1" to add a new line.
     *
     * <p>Required. Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ItemLineUpdateInput id(String value) {
        setOptional("id", value);
        return this;
    }

    /**
     * The {@code id} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String id() {
        return value("id");
    }

    /**
     * ID of the item for this item line.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ItemLineUpdateInput itemId(String value) {
        setOptional("itemId", value);
        return this;
    }

    /**
     * The {@code itemId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String itemId() {
        return value("itemId");
    }

    /**
     * ID of the inventory site for this item line.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ItemLineUpdateInput inventorySiteId(String value) {
        setOptional("inventorySiteId", value);
        return this;
    }

    /**
     * The {@code inventorySiteId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String inventorySiteId() {
        return value("inventorySiteId");
    }

    /**
     * ID of the inventory site location for this item line.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ItemLineUpdateInput inventorySiteLocationId(String value) {
        setOptional("inventorySiteLocationId", value);
        return this;
    }

    /**
     * The {@code inventorySiteLocationId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String inventorySiteLocationId() {
        return value("inventorySiteLocationId");
    }

    /**
     * Serial number of this item line. Cannot be combined with lotNumber.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public ItemLineUpdateInput serialNumber(String value) {
        setNullable("serialNumber", value);
        return this;
    }

    /**
     * The {@code serialNumber} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String serialNumber() {
        return value("serialNumber");
    }

    /**
     * Lot number of this item line. Cannot be combined with serialNumber.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public ItemLineUpdateInput lotNumber(String value) {
        setNullable("lotNumber", value);
        return this;
    }

    /**
     * The {@code lotNumber} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String lotNumber() {
        return value("lotNumber");
    }

    /**
     * Expiration date of this item line.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public ItemLineUpdateInput expirationDate(String value) {
        setNullable("expirationDate", value);
        return this;
    }

    /**
     * The {@code expirationDate} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String expirationDate() {
        return value("expirationDate");
    }

    /**
     * Description of this item line.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public ItemLineUpdateInput description(String value) {
        setNullable("description", value);
        return this;
    }

    /**
     * The {@code description} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String description() {
        return value("description");
    }

    /**
     * Quantity of the item.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ItemLineUpdateInput quantity(Double value) {
        setOptional("quantity", value);
        return this;
    }

    /**
     * Quantity of the item.
     *
     * @param value the value
     * @return this object
     */
    public ItemLineUpdateInput quantity(double value) {
        setOptional("quantity", value);
        return this;
    }

    /**
     * The {@code quantity} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Double quantity() {
        return value("quantity");
    }

    /**
     * Unit of measure for the quantity.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public ItemLineUpdateInput unitOfMeasure(String value) {
        setNullable("unitOfMeasure", value);
        return this;
    }

    /**
     * The {@code unitOfMeasure} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String unitOfMeasure() {
        return value("unitOfMeasure");
    }

    /**
     * ID of the override unit of measure set for this item line.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ItemLineUpdateInput overrideUnitOfMeasureSetId(String value) {
        setOptional("overrideUnitOfMeasureSetId", value);
        return this;
    }

    /**
     * The {@code overrideUnitOfMeasureSetId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String overrideUnitOfMeasureSetId() {
        return value("overrideUnitOfMeasureSetId");
    }

    /**
     * Cost of this item line. Decimal string with up to 5 decimal places.
     *
     * <p>Decimal; scale is preserved on the wire. Example: <code>"19.99"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ItemLineUpdateInput cost(BigDecimal value) {
        setOptional("cost", Wire.decimalText(value));
        return this;
    }

    /**
     * The {@code cost} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public BigDecimal cost() {
        return Wire.decimalOrNull(value("cost"));
    }

    /**
     * Amount as a decimal string.
     *
     * <p>Decimal; scale is preserved on the wire. Example: <code>"1250.00"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ItemLineUpdateInput amount(BigDecimal value) {
        setOptional("amount", Wire.decimalText(value));
        return this;
    }

    /**
     * The {@code amount} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public BigDecimal amount() {
        return Wire.decimalOrNull(value("amount"));
    }

    /**
     * ID of the customer for this item line.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ItemLineUpdateInput customerId(String value) {
        setOptional("customerId", value);
        return this;
    }

    /**
     * The {@code customerId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String customerId() {
        return value("customerId");
    }

    /**
     * ID of the class for this item line.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ItemLineUpdateInput classId(String value) {
        setOptional("classId", value);
        return this;
    }

    /**
     * The {@code classId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String classId() {
        return value("classId");
    }

    /**
     * Whether this line can be billed to a customer.
     *
     * <p>Allowed values are in {@link ItemLineUpdateInputBillingStatus}.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ItemLineUpdateInput billingStatus(String value) {
        setOptional("billingStatus", value);
        return this;
    }

    /**
     * The {@code billingStatus} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String billingStatus() {
        return value("billingStatus");
    }

    /**
     * ID of the override item account for this item line.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ItemLineUpdateInput overrideItemAccountId(String value) {
        setOptional("overrideItemAccountId", value);
        return this;
    }

    /**
     * The {@code overrideItemAccountId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String overrideItemAccountId() {
        return value("overrideItemAccountId");
    }

    /**
     * ID of the sales representative for this item line.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ItemLineUpdateInput salesRepresentativeId(String value) {
        setOptional("salesRepresentativeId", value);
        return this;
    }

    /**
     * The {@code salesRepresentativeId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String salesRepresentativeId() {
        return value("salesRepresentativeId");
    }
}
