// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:09aa9517f466027d023798abdf939204d057d808cb4eb15566deed6b960adcec
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code ItemType} values.
 *
 * <p>Allowed values.
 */
public final class ItemType {
    private ItemType() {}

    /** {@code all_except_fixed_asset} */
    public static final String ALL_EXCEPT_FIXED_ASSET = "all_except_fixed_asset";

    /** {@code assembly} */
    public static final String ASSEMBLY = "assembly";

    /** {@code discount} */
    public static final String DISCOUNT = "discount";

    /** {@code fixed_asset} */
    public static final String FIXED_ASSET = "fixed_asset";

    /** {@code inventory} */
    public static final String INVENTORY = "inventory";

    /** {@code inventory_and_assembly} */
    public static final String INVENTORY_AND_ASSEMBLY = "inventory_and_assembly";

    /** {@code non_inventory} */
    public static final String NON_INVENTORY = "non_inventory";

    /** {@code other_charge} */
    public static final String OTHER_CHARGE = "other_charge";

    /** {@code payment} */
    public static final String PAYMENT = "payment";

    /** {@code sales} */
    public static final String SALES = "sales";

    /** {@code sales_tax} */
    public static final String SALES_TAX = "sales_tax";

    /** {@code service} */
    public static final String SERVICE = "service";
}
