// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:b5774d24bc8154ccc2acb85370ae27581a072c3f5070a529111ee2dd26f103b9
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code JobReportType} values.
 *
 * <p>Allowed values.
 */
public final class JobReportType {
    private JobReportType() {}

    /** {@code item_estimates_vs_actuals} */
    public static final String ITEM_ESTIMATES_VS_ACTUALS = "item_estimates_vs_actuals";

    /** {@code item_profitability} */
    public static final String ITEM_PROFITABILITY = "item_profitability";

    /** {@code job_estimates_vs_actuals_detail} */
    public static final String JOB_ESTIMATES_VS_ACTUALS_DETAIL = "job_estimates_vs_actuals_detail";

    /** {@code job_estimates_vs_actuals_summary} */
    public static final String JOB_ESTIMATES_VS_ACTUALS_SUMMARY = "job_estimates_vs_actuals_summary";

    /** {@code job_profitability_detail} */
    public static final String JOB_PROFITABILITY_DETAIL = "job_profitability_detail";

    /** {@code job_profitability_summary} */
    public static final String JOB_PROFITABILITY_SUMMARY = "job_profitability_summary";
}
