// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:3d102b7bcecbf18e72b655745e5c55d641457fab2fd8184b3da643aeb51bb76f
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.Json;
import com.desktopaccountingapi.quickbooksdesktop.core.JsonWritable;
import com.desktopaccountingapi.quickbooksdesktop.core.Wire;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;

/**
 * Jobs and estimates preferences as stored in QuickBooks Desktop.
 *
 * <p>Parsed tolerantly: unknown members go to {@link #additionalProperties()} and missing members read as null. {@link #toJson()} writes the wire form back.
 */
public final class JobsAndEstimate implements JsonWritable {
    private static final Set<String> KNOWN = new HashSet<>(Arrays.asList("isUsingEstimates", "isUsingProgressInvoicing", "isPrintingItemsWithZeroAmounts"));

    private Boolean isUsingEstimates;
    private Boolean isUsingProgressInvoicing;
    private Boolean isPrintingItemsWithZeroAmounts;
    private Map<String, Object> additionalProperties = Collections.emptyMap();

    private JobsAndEstimate() {}

    /**
     * Reads the object from parsed JSON (see {@code Json.parse}).
     *
     * @param json parsed JSON object
     * @return the object
     * @throws com.desktopaccountingapi.quickbooksdesktop.core.Json.JsonException if a member has the wrong JSON type
     */
    public static JobsAndEstimate fromJson(Object json) {
        Map<String, Object> o = Wire.object(json, "JobsAndEstimate");
        JobsAndEstimate m = new JobsAndEstimate();
        m.isUsingEstimates = Wire.get(o, "isUsingEstimates", Wire::asBoolean);
        m.isUsingProgressInvoicing = Wire.get(o, "isUsingProgressInvoicing", Wire::asBoolean);
        m.isPrintingItemsWithZeroAmounts = Wire.get(o, "isPrintingItemsWithZeroAmounts", Wire::asBoolean);
        m.additionalProperties = Wire.extra(o, KNOWN);
        return m;
    }

    /**
     * Parses the object from JSON text.
     *
     * @param json JSON text
     * @return the object
     */
    public static JobsAndEstimate parse(String json) {
        return fromJson(Json.parse(json));
    }

    /**
     * Whether this jobs and estimates preferences is using estimates.
     *
     * @return the value, or null
     */
    public Boolean isUsingEstimates() {
        return isUsingEstimates;
    }

    /**
     * Whether this jobs and estimates preferences is using progress invoicing.
     *
     * @return the value, or null
     */
    public Boolean isUsingProgressInvoicing() {
        return isUsingProgressInvoicing;
    }

    /**
     * Whether this jobs and estimates preferences is printing items with zero amounts.
     *
     * @return the value, or null
     */
    public Boolean isPrintingItemsWithZeroAmounts() {
        return isPrintingItemsWithZeroAmounts;
    }

    /**
     * Members the API sent that this SDK version does not know.
     *
     * @return unmodifiable map, in wire order
     */
    public Map<String, Object> additionalProperties() {
        return additionalProperties;
    }

    @Override
    public Map<String, Object> toWire() {
        Map<String, Object> w = new LinkedHashMap<>();
        w.put("isUsingEstimates", this.isUsingEstimates);
        w.put("isUsingProgressInvoicing", this.isUsingProgressInvoicing);
        w.put("isPrintingItemsWithZeroAmounts", this.isPrintingItemsWithZeroAmounts);
        w.putAll(this.additionalProperties);
        return w;
    }

    @Override
    public String toString() {
        return "JobsAndEstimate" + toJson();
    }
}
