// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:3d102b7bcecbf18e72b655745e5c55d641457fab2fd8184b3da643aeb51bb76f
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code LineUpdateInputJournalLineType} values.
 *
 * <p>Allowed values.
 */
public final class LineUpdateInputJournalLineType {
    private LineUpdateInputJournalLineType() {}

    /** {@code debit} */
    public static final String DEBIT = "debit";

    /** {@code credit} */
    public static final String CREDIT = "credit";
}
