// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:d4adaec794b6cf028d0f87bcaed3668ec305d5e364a02008e8a22258ee3a7d59
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code LineUpdateInputJournalLineType} values.
 *
 * <p>Allowed values.
 */
public final class LineUpdateInputJournalLineType {
    private LineUpdateInputJournalLineType() {}

    /** {@code debit} */
    public static final String DEBIT = "debit";

    /** {@code credit} */
    public static final String CREDIT = "credit";
}
