// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:6f5ac28d7c33ac90aa7e2c15d88efd50e8e41c808bcc5489f0c8b1cb7833326a
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.InputObject;

/**
 * Fields for creating a non-inventory item. Requires at least one of: salesOrPurchaseDetails or salesAndPurchaseDetails.
 *
 * <p>Fluent setters return this object. Fields you never set are not sent; on clearable fields, null is sent to clear the value.
 */
public final class NonInventoryItemCreateInput extends InputObject {
    /**
     * Creates an empty object. Set the required field {@code name} before sending.
     */
    public NonInventoryItemCreateInput() {
        super("name");
    }

    /**
     * Creates the object with its required fields.
     *
     * @param name Name of this non-inventory item, unique within its parent level.
     */
    public NonInventoryItemCreateInput(String name) {
        this();
        name(name);
    }

    /**
     * Name of this non-inventory item, unique within its parent level.
     *
     * <p>Required.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public NonInventoryItemCreateInput name(String value) {
        setOptional("name", value);
        return this;
    }

    /**
     * The {@code name} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String name() {
        return value("name");
    }

    /**
     * Barcode details for this non-inventory item.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public NonInventoryItemCreateInput barcode(BarcodeCreateInput value) {
        setOptional("barcode", value);
        return this;
    }

    /**
     * The {@code barcode} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public BarcodeCreateInput barcode() {
        return value("barcode");
    }

    /**
     * Whether this non-inventory item is active. Inactive objects stay in QuickBooks but are hidden from most lists.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public NonInventoryItemCreateInput isActive(Boolean value) {
        setOptional("isActive", value);
        return this;
    }

    /**
     * The {@code isActive} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Boolean isActive() {
        return value("isActive");
    }

    /**
     * ID of the parent object, making this non-inventory item a child in the hierarchy.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public NonInventoryItemCreateInput parentId(String value) {
        setOptional("parentId", value);
        return this;
    }

    /**
     * The {@code parentId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String parentId() {
        return value("parentId");
    }

    /**
     * ID of the class for this non-inventory item.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public NonInventoryItemCreateInput classId(String value) {
        setOptional("classId", value);
        return this;
    }

    /**
     * The {@code classId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String classId() {
        return value("classId");
    }

    /**
     * Sku of this non-inventory item.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public NonInventoryItemCreateInput sku(String value) {
        setOptional("sku", value);
        return this;
    }

    /**
     * The {@code sku} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String sku() {
        return value("sku");
    }

    /**
     * ID of the unit of measure set for this non-inventory item.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public NonInventoryItemCreateInput unitOfMeasureSetId(String value) {
        setOptional("unitOfMeasureSetId", value);
        return this;
    }

    /**
     * The {@code unitOfMeasureSetId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String unitOfMeasureSetId() {
        return value("unitOfMeasureSetId");
    }

    /**
     * ID of the sales tax code for this non-inventory item.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public NonInventoryItemCreateInput salesTaxCodeId(String value) {
        setOptional("salesTaxCodeId", value);
        return this;
    }

    /**
     * The {@code salesTaxCodeId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String salesTaxCodeId() {
        return value("salesTaxCodeId");
    }

    /**
     * The {@code salesOrPurchaseDetails} field.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public NonInventoryItemCreateInput salesOrPurchaseDetails(SalesOrPurchaseDetailCreateInput value) {
        setOptional("salesOrPurchaseDetails", value);
        return this;
    }

    /**
     * The {@code salesOrPurchaseDetails} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public SalesOrPurchaseDetailCreateInput salesOrPurchaseDetails() {
        return value("salesOrPurchaseDetails");
    }

    /**
     * The {@code salesAndPurchaseDetails} field.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public NonInventoryItemCreateInput salesAndPurchaseDetails(SalesAndPurchaseDetailCreateInput value) {
        setOptional("salesAndPurchaseDetails", value);
        return this;
    }

    /**
     * The {@code salesAndPurchaseDetails} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public SalesAndPurchaseDetailCreateInput salesAndPurchaseDetails() {
        return value("salesAndPurchaseDetails");
    }

    /**
     * Your own UUID for this non-inventory item, stored by QuickBooks so you can match records with your system.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public NonInventoryItemCreateInput externalId(String value) {
        setOptional("externalId", value);
        return this;
    }

    /**
     * The {@code externalId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String externalId() {
        return value("externalId");
    }
}
