// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:79b06eb2008381661d24d3bd5e23643483ec1bf9b70d5f4cdff2a2a71e22fe94
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.InputObject;

/**
 * Fields for creating an additional notes.
 *
 * <p>Fluent setters return this object. Fields you never set are not sent; on clearable fields, null is sent to clear the value.
 */
public final class NoteCreateInput extends InputObject {
    /**
     * Creates an empty object. Set the required field {@code note} before sending.
     */
    public NoteCreateInput() {
        super("note");
    }

    /**
     * Creates the object with its required fields.
     *
     * @param note Note for this additional notes.
     */
    public NoteCreateInput(String note) {
        this();
        note(note);
    }

    /**
     * Note for this additional notes.
     *
     * <p>Required.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public NoteCreateInput note(String value) {
        setOptional("note", value);
        return this;
    }

    /**
     * The {@code note} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String note() {
        return value("note");
    }
}
