// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:68a0d76d6b51187adfc66d768eae8e30675b5093f4ae538b0d9c32c905b9bb2d
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.InputObject;

/**
 * Fields for creating an other charge item. Requires at least one of: salesOrPurchaseDetails or salesAndPurchaseDetails.
 *
 * <p>Fluent setters return this object. Fields you never set are not sent; on clearable fields, null is sent to clear the value.
 */
public final class OtherChargeItemCreateInput extends InputObject {
    /**
     * Creates an empty object. Set the required field {@code name} before sending.
     */
    public OtherChargeItemCreateInput() {
        super("name");
    }

    /**
     * Creates the object with its required fields.
     *
     * @param name Name of this other charge item, unique within its parent level.
     */
    public OtherChargeItemCreateInput(String name) {
        this();
        name(name);
    }

    /**
     * Name of this other charge item, unique within its parent level.
     *
     * <p>Required.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public OtherChargeItemCreateInput name(String value) {
        setOptional("name", value);
        return this;
    }

    /**
     * The {@code name} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String name() {
        return value("name");
    }

    /**
     * Barcode details for this other charge item.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public OtherChargeItemCreateInput barcode(BarcodeCreateInput value) {
        setOptional("barcode", value);
        return this;
    }

    /**
     * The {@code barcode} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public BarcodeCreateInput barcode() {
        return value("barcode");
    }

    /**
     * Whether this other charge item is active. Inactive objects stay in QuickBooks but are hidden from most lists.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public OtherChargeItemCreateInput isActive(Boolean value) {
        setOptional("isActive", value);
        return this;
    }

    /**
     * The {@code isActive} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Boolean isActive() {
        return value("isActive");
    }

    /**
     * ID of the class for this other charge item.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public OtherChargeItemCreateInput classId(String value) {
        setOptional("classId", value);
        return this;
    }

    /**
     * The {@code classId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String classId() {
        return value("classId");
    }

    /**
     * ID of the parent object, making this other charge item a child in the hierarchy.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public OtherChargeItemCreateInput parentId(String value) {
        setOptional("parentId", value);
        return this;
    }

    /**
     * The {@code parentId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String parentId() {
        return value("parentId");
    }

    /**
     * ID of the sales tax code for this other charge item.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public OtherChargeItemCreateInput salesTaxCodeId(String value) {
        setOptional("salesTaxCodeId", value);
        return this;
    }

    /**
     * The {@code salesTaxCodeId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String salesTaxCodeId() {
        return value("salesTaxCodeId");
    }

    /**
     * Sales or purchase details details for this other charge item. Cannot be combined with salesAndPurchaseDetails.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public OtherChargeItemCreateInput salesOrPurchaseDetails(SalesOrPurchaseDetailCreateInput value) {
        setOptional("salesOrPurchaseDetails", value);
        return this;
    }

    /**
     * The {@code salesOrPurchaseDetails} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public SalesOrPurchaseDetailCreateInput salesOrPurchaseDetails() {
        return value("salesOrPurchaseDetails");
    }

    /**
     * Sales and purchase details details for this other charge item. Cannot be combined with salesOrPurchaseDetails.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public OtherChargeItemCreateInput salesAndPurchaseDetails(SalesAndPurchaseDetailCreateInput value) {
        setOptional("salesAndPurchaseDetails", value);
        return this;
    }

    /**
     * The {@code salesAndPurchaseDetails} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public SalesAndPurchaseDetailCreateInput salesAndPurchaseDetails() {
        return value("salesAndPurchaseDetails");
    }

    /**
     * Your own UUID for this other charge item, stored by QuickBooks so you can match records with your system.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public OtherChargeItemCreateInput externalId(String value) {
        setOptional("externalId", value);
        return this;
    }

    /**
     * The {@code externalId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String externalId() {
        return value("externalId");
    }
}
