// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:b5774d24bc8154ccc2acb85370ae27581a072c3f5070a529111ee2dd26f103b9
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code OtherChargeItemSpecialItemType} values.
 *
 * <p>Known values of an open set. The API may return values not listed here; treat unknown values as valid.
 */
public final class OtherChargeItemSpecialItemType {
    private OtherChargeItemSpecialItemType() {}

    /** {@code finance_charge} */
    public static final String FINANCE_CHARGE = "finance_charge";

    /** {@code reimbursable_expense_group} */
    public static final String REIMBURSABLE_EXPENSE_GROUP = "reimbursable_expense_group";

    /** {@code reimbursable_expense_subtotal} */
    public static final String REIMBURSABLE_EXPENSE_SUBTOTAL = "reimbursable_expense_subtotal";
}
