// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:1fc5496cc47b442606ea78c818f94a29798b32785dc14c59e7986e24f10bf332
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.InputObject;
import java.util.Map;

/**
 * qbXML request elements as JSON, keyed by element name (names end in `Rq`). Attributes are `&#64;name`, element text next to attributes is `#text`, and repeated elements are arrays. Elements are sent in the order given.
 *
 * <p>Set members with {@link #put(String, Object)}; values are any JSON-compatible Java values (Map, List, String, Number, Boolean, null).
 */
public final class PassthroughInput extends InputObject {
    /** Creates an empty object. */
    public PassthroughInput() {
        super();
    }

    /**
     * Creates an object with the given members.
     *
     * @param members members to copy
     * @return the object
     */
    public static PassthroughInput of(Map<String, ?> members) {
        PassthroughInput o = new PassthroughInput();
        for (Map.Entry<String, ?> e : members.entrySet()) o.put(e.getKey(), e.getValue());
        return o;
    }

    /**
     * Sets a member.
     *
     * @param key member name
     * @param value JSON-compatible value
     * @return this object
     */
    public PassthroughInput put(String key, Object value) {
        setNullable(key, value);
        return this;
    }
}
