// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:68a0d76d6b51187adfc66d768eae8e30675b5093f4ae538b0d9c32c905b9bb2d
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code PaymentStatus} values.
 *
 * <p>Allowed values.
 */
public final class PaymentStatus {
    private PaymentStatus() {}

    /** {@code all} */
    public static final String ALL = "all";

    /** {@code paid} */
    public static final String PAID = "paid";

    /** {@code not_paid} */
    public static final String NOT_PAID = "not_paid";
}
