// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:d4adaec794b6cf028d0f87bcaed3668ec305d5e364a02008e8a22258ee3a7d59
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code PaymentMethodCreateInputPaymentMethodType} values.
 *
 * <p>Allowed values.
 */
public final class PaymentMethodCreateInputPaymentMethodType {
    private PaymentMethodCreateInputPaymentMethodType() {}

    /** {@code american_express} */
    public static final String AMERICAN_EXPRESS = "american_express";

    /** {@code cash} */
    public static final String CASH = "cash";

    /** {@code check} */
    public static final String CHECK = "check";

    /** {@code debit_card} */
    public static final String DEBIT_CARD = "debit_card";

    /** {@code discover} */
    public static final String DISCOVER = "discover";

    /** {@code e_check} */
    public static final String E_CHECK = "e_check";

    /** {@code gift_card} */
    public static final String GIFT_CARD = "gift_card";

    /** {@code master_card} */
    public static final String MASTER_CARD = "master_card";

    /** {@code other} */
    public static final String OTHER = "other";

    /** {@code other_credit_card} */
    public static final String OTHER_CREDIT_CARD = "other_credit_card";

    /** {@code visa} */
    public static final String VISA = "visa";
}
