// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:09aa9517f466027d023798abdf939204d057d808cb4eb15566deed6b960adcec
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code PayrollDetailReportType} values.
 *
 * <p>Allowed values.
 */
public final class PayrollDetailReportType {
    private PayrollDetailReportType() {}

    /** {@code employee_state_taxes_detail} */
    public static final String EMPLOYEE_STATE_TAXES_DETAIL = "employee_state_taxes_detail";

    /** {@code payroll_item_detail} */
    public static final String PAYROLL_ITEM_DETAIL = "payroll_item_detail";

    /** {@code payroll_review_detail} */
    public static final String PAYROLL_REVIEW_DETAIL = "payroll_review_detail";

    /** {@code payroll_transaction_detail} */
    public static final String PAYROLL_TRANSACTION_DETAIL = "payroll_transaction_detail";

    /** {@code payroll_transactions_by_payee} */
    public static final String PAYROLL_TRANSACTIONS_BY_PAYEE = "payroll_transactions_by_payee";
}
