// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:d4adaec794b6cf028d0f87bcaed3668ec305d5e364a02008e8a22258ee3a7d59
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.Json;
import com.desktopaccountingapi.quickbooksdesktop.core.JsonWritable;
import com.desktopaccountingapi.quickbooksdesktop.core.Wire;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;

/**
 * Payroll wage item as stored in QuickBooks Desktop.
 *
 * <p>Parsed tolerantly: unknown members go to {@link #additionalProperties()} and missing members read as null. {@link #toJson()} writes the wire form back.
 */
public final class PayrollWageItem implements JsonWritable {
    private static final Set<String> KNOWN = new HashSet<>(Arrays.asList("id", "objectType", "createdAt", "updatedAt", "revisionNumber", "name", "isActive", "wageType", "expenseAccount", "overtimeMultiplier", "rate", "ratePercent"));

    private String id;
    private String objectType;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;
    private String revisionNumber;
    private String name;
    private Boolean isActive;
    private String wageType;
    private Reference expenseAccount;
    private BigDecimal overtimeMultiplier;
    private BigDecimal rate;
    private BigDecimal ratePercent;
    private Map<String, Object> additionalProperties = Collections.emptyMap();

    private PayrollWageItem() {}

    /**
     * Reads the object from parsed JSON (see {@code Json.parse}).
     *
     * @param json parsed JSON object
     * @return the object
     * @throws com.desktopaccountingapi.quickbooksdesktop.core.Json.JsonException if a member has the wrong JSON type
     */
    public static PayrollWageItem fromJson(Object json) {
        Map<String, Object> o = Wire.object(json, "PayrollWageItem");
        PayrollWageItem m = new PayrollWageItem();
        m.id = Wire.get(o, "id", Wire::asString);
        m.objectType = Wire.get(o, "objectType", Wire::asString);
        m.createdAt = Wire.get(o, "createdAt", Wire::asDateTime);
        m.updatedAt = Wire.get(o, "updatedAt", Wire::asDateTime);
        m.revisionNumber = Wire.get(o, "revisionNumber", Wire::asString);
        m.name = Wire.get(o, "name", Wire::asString);
        m.isActive = Wire.get(o, "isActive", Wire::asBoolean);
        m.wageType = Wire.get(o, "wageType", Wire::asString);
        m.expenseAccount = Wire.get(o, "expenseAccount", Reference::fromJson);
        m.overtimeMultiplier = Wire.get(o, "overtimeMultiplier", Wire::asDecimal);
        m.rate = Wire.get(o, "rate", Wire::asDecimal);
        m.ratePercent = Wire.get(o, "ratePercent", Wire::asDecimal);
        m.additionalProperties = Wire.extra(o, KNOWN);
        return m;
    }

    /**
     * Parses the object from JSON text.
     *
     * @param json JSON text
     * @return the object
     */
    public static PayrollWageItem parse(String json) {
        return fromJson(Json.parse(json));
    }

    /**
     * QuickBooks-assigned ID of this payroll wage item.
     *
     * @return the value (null only if the API omitted it)
     */
    public String id() {
        return id;
    }

    /**
     * Type of this object.
     *
     * @return the value (null only if the API omitted it)
     */
    public String objectType() {
        return objectType;
    }

    /**
     * When this payroll wage item was created, as an ISO 8601 date-time with the QuickBooks computer's UTC offset.
     *
     * <p>Example: <code>"2026-10-05T09:14:03-07:00"</code>.
     *
     * @return the value (null only if the API omitted it)
     */
    public OffsetDateTime createdAt() {
        return createdAt;
    }

    /**
     * When this payroll wage item was last changed, as an ISO 8601 date-time with the QuickBooks computer's UTC offset. Whole seconds: a second change within the same second keeps this value, so incremental syncs should overlap `updatedAfter` and deduplicate by `id` and `revisionNumber`.
     *
     * <p>Example: <code>"2026-10-05T09:14:03-07:00"</code>.
     *
     * @return the value (null only if the API omitted it)
     */
    public OffsetDateTime updatedAt() {
        return updatedAt;
    }

    /**
     * Current revision of this payroll wage item. Send it unchanged when updating; a stale value is rejected. QuickBooks changes it at most once per second, so a second edit within the same second keeps the same value. This API spaces its own consecutive writes to one object by over a second; edits made elsewhere in the same second are not detected.
     *
     * @return the value (null only if the API omitted it)
     */
    public String revisionNumber() {
        return revisionNumber;
    }

    /**
     * Name of this payroll wage item, unique within its parent level.
     *
     * @return the value, or null
     */
    public String name() {
        return name;
    }

    /**
     * Whether this payroll wage item is active. Inactive objects stay in QuickBooks but are hidden from most lists.
     *
     * @return the value, or null
     */
    public Boolean isActive() {
        return isActive;
    }

    /**
     * Wage type of this payroll wage item.
     *
     * <p>Known values are in {@link PayrollWageItemWageType}; other values may appear.
     *
     * @return the value, or null
     */
    public String wageType() {
        return wageType;
    }

    /**
     * The expense account for this payroll wage item.
     *
     * @return the value, or null
     */
    public Reference expenseAccount() {
        return expenseAccount;
    }

    /**
     * Overtime pay multiplier as a decimal string, for example "1.5" for time and a half.
     *
     * <p>Decimal; scale is preserved on the wire. Example: <code>"19.99"</code>.
     *
     * @return the value, or null
     */
    public BigDecimal overtimeMultiplier() {
        return overtimeMultiplier;
    }

    /**
     * Price per unit, as a decimal string.
     *
     * <p>Decimal; scale is preserved on the wire. Example: <code>"19.99"</code>.
     *
     * @return the value, or null
     */
    public BigDecimal rate() {
        return rate;
    }

    /**
     * Price as a percentage, for percentage-based items. Percentage as a decimal string: "7.5" means 7.5 %.
     *
     * <p>Decimal; scale is preserved on the wire. Example: <code>"7.5"</code>.
     *
     * @return the value, or null
     */
    public BigDecimal ratePercent() {
        return ratePercent;
    }

    /**
     * Members the API sent that this SDK version does not know.
     *
     * @return unmodifiable map, in wire order
     */
    public Map<String, Object> additionalProperties() {
        return additionalProperties;
    }

    @Override
    public Map<String, Object> toWire() {
        Map<String, Object> w = new LinkedHashMap<>();
        w.put("id", this.id);
        w.put("objectType", this.objectType);
        w.put("createdAt", this.createdAt);
        w.put("updatedAt", this.updatedAt);
        w.put("revisionNumber", this.revisionNumber);
        w.put("name", this.name);
        w.put("isActive", this.isActive);
        w.put("wageType", this.wageType);
        w.put("expenseAccount", this.expenseAccount);
        w.put("overtimeMultiplier", Wire.decimalText(this.overtimeMultiplier));
        w.put("rate", Wire.decimalText(this.rate));
        w.put("ratePercent", Wire.decimalText(this.ratePercent));
        w.putAll(this.additionalProperties);
        return w;
    }

    @Override
    public String toString() {
        return "PayrollWageItem" + toJson();
    }
}
