// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:6f5ac28d7c33ac90aa7e2c15d88efd50e8e41c808bcc5489f0c8b1cb7833326a
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code PerItemPriceLevelInputAdjustRelativeTo} values.
 *
 * <p>Allowed values.
 */
public final class PerItemPriceLevelInputAdjustRelativeTo {
    private PerItemPriceLevelInputAdjustRelativeTo() {}

    /** {@code standard_price} */
    public static final String STANDARD_PRICE = "standard_price";

    /** {@code cost} */
    public static final String COST = "cost";

    /** {@code current_custom_price} */
    public static final String CURRENT_CUSTOM_PRICE = "current_custom_price";
}
