// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:3d102b7bcecbf18e72b655745e5c55d641457fab2fd8184b3da643aeb51bb76f
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code PriceLevelPriceLevelType} values.
 *
 * <p>Known values of an open set. The API may return values not listed here; treat unknown values as valid.
 */
public final class PriceLevelPriceLevelType {
    private PriceLevelPriceLevelType() {}

    /** {@code fixed_percentage} */
    public static final String FIXED_PERCENTAGE = "fixed_percentage";

    /** {@code per_item} */
    public static final String PER_ITEM = "per_item";
}
