// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:1fc5496cc47b442606ea78c818f94a29798b32785dc14c59e7986e24f10bf332
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.InputObject;
import com.desktopaccountingapi.quickbooksdesktop.core.Wire;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

/**
 * Fields for updating a received payment.
 *
 * <p>Fluent setters return this object. Fields you never set are not sent; on clearable fields, null is sent to clear the value.
 */
public final class ReceivePaymentUpdateInput extends InputObject {
    /**
     * Creates an empty object. Set the required field {@code revisionNumber} before sending.
     */
    public ReceivePaymentUpdateInput() {
        super("revisionNumber");
    }

    /**
     * Creates the object with its required fields.
     *
     * @param revisionNumber Current revision of this received payment. Send it unchanged when updating; a stale value is rejected. QuickBooks changes it at most once per second, so a second edit within the same second keeps the same value. This API spaces its own consecutive writes to one object by over a second; edits made elsewhere in the same second are not detected.
     */
    public ReceivePaymentUpdateInput(String revisionNumber) {
        this();
        revisionNumber(revisionNumber);
    }

    /**
     * Current revision of this received payment. Send it unchanged when updating; a stale value is rejected. QuickBooks changes it at most once per second, so a second edit within the same second keeps the same value. This API spaces its own consecutive writes to one object by over a second; edits made elsewhere in the same second are not detected.
     *
     * <p>Required.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ReceivePaymentUpdateInput revisionNumber(String value) {
        setOptional("revisionNumber", value);
        return this;
    }

    /**
     * The {@code revisionNumber} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String revisionNumber() {
        return stored("revisionNumber");
    }

    /**
     * ID of the customer for this received payment.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ReceivePaymentUpdateInput customerId(String value) {
        setOptional("customerId", value);
        return this;
    }

    /**
     * The {@code customerId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String customerId() {
        return stored("customerId");
    }

    /**
     * ID of the receivables account for this received payment.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ReceivePaymentUpdateInput receivablesAccountId(String value) {
        setOptional("receivablesAccountId", value);
        return this;
    }

    /**
     * The {@code receivablesAccountId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String receivablesAccountId() {
        return stored("receivablesAccountId");
    }

    /**
     * Date of this received payment (YYYY-MM-DD).
     *
     * <p>Example: <code>"2026-10-05"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ReceivePaymentUpdateInput transactionDate(LocalDate value) {
        setOptional("transactionDate", value);
        return this;
    }

    /**
     * The {@code transactionDate} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public LocalDate transactionDate() {
        return stored("transactionDate");
    }

    /**
     * Reference number of this received payment, such as an invoice or check number. Case-sensitive.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public ReceivePaymentUpdateInput refNumber(String value) {
        setNullable("refNumber", value);
        return this;
    }

    /**
     * The {@code refNumber} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String refNumber() {
        return stored("refNumber");
    }

    /**
     * Total amount of this received payment as a decimal string.
     *
     * <p>Decimal; scale is preserved on the wire. Example: <code>"1250.00"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ReceivePaymentUpdateInput totalAmount(BigDecimal value) {
        setOptional("totalAmount", Wire.decimalText(value));
        return this;
    }

    /**
     * The {@code totalAmount} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public BigDecimal totalAmount() {
        return Wire.decimalOrNull(stored("totalAmount"));
    }

    /**
     * Exchange rate from this received payment's currency to the home currency.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ReceivePaymentUpdateInput exchangeRate(Double value) {
        setOptional("exchangeRate", value);
        return this;
    }

    /**
     * Exchange rate from this received payment's currency to the home currency.
     *
     * @param value the value
     * @return this object
     */
    public ReceivePaymentUpdateInput exchangeRate(double value) {
        setOptional("exchangeRate", value);
        return this;
    }

    /**
     * The {@code exchangeRate} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Double exchangeRate() {
        return stored("exchangeRate");
    }

    /**
     * ID of the payment method for this received payment.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ReceivePaymentUpdateInput paymentMethodId(String value) {
        setOptional("paymentMethodId", value);
        return this;
    }

    /**
     * The {@code paymentMethodId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String paymentMethodId() {
        return stored("paymentMethodId");
    }

    /**
     * Internal memo for this received payment; shown in reports, not on printed forms.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public ReceivePaymentUpdateInput memo(String value) {
        setNullable("memo", value);
        return this;
    }

    /**
     * The {@code memo} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String memo() {
        return stored("memo");
    }

    /**
     * ID of the deposit to account for this received payment.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ReceivePaymentUpdateInput depositToAccountId(String value) {
        setOptional("depositToAccountId", value);
        return this;
    }

    /**
     * The {@code depositToAccountId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String depositToAccountId() {
        return stored("depositToAccountId");
    }

    /**
     * The {@code creditCardTransaction} field.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ReceivePaymentUpdateInput creditCardTransaction(CreditCardTransactionUpdateInput value) {
        setOptional("creditCardTransaction", value);
        return this;
    }

    /**
     * The {@code creditCardTransaction} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public CreditCardTransactionUpdateInput creditCardTransaction() {
        return stored("creditCardTransaction");
    }

    /**
     * Apply to transactions entries for this received payment.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ReceivePaymentUpdateInput applyToTransactions(List<ApplyToTransactionInput> value) {
        setOptional("applyToTransactions", value);
        return this;
    }

    /**
     * The {@code applyToTransactions} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public List<ApplyToTransactionInput> applyToTransactions() {
        return stored("applyToTransactions");
    }
}
