// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:6f5ac28d7c33ac90aa7e2c15d88efd50e8e41c808bcc5489f0c8b1cb7833326a
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.Json;
import com.desktopaccountingapi.quickbooksdesktop.core.JsonWritable;
import com.desktopaccountingapi.quickbooksdesktop.core.Wire;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;

/**
 * Reference to another QuickBooks object.
 *
 * <p>Parsed tolerantly: unknown members go to {@link #additionalProperties()} and missing members read as null. {@link #toJson()} writes the wire form back.
 */
public final class Reference implements JsonWritable {
    private static final Set<String> KNOWN = new HashSet<>(Arrays.asList("id", "fullName"));

    private String id;
    private String fullName;
    private Map<String, Object> additionalProperties = Collections.emptyMap();

    private Reference() {}

    /**
     * Reads the object from parsed JSON (see {@code Json.parse}).
     *
     * @param json parsed JSON object
     * @return the object
     * @throws com.desktopaccountingapi.quickbooksdesktop.core.Json.JsonException if a member has the wrong JSON type
     */
    public static Reference fromJson(Object json) {
        Map<String, Object> o = Wire.object(json, "Reference");
        Reference m = new Reference();
        m.id = Wire.get(o, "id", Wire::asString);
        m.fullName = Wire.get(o, "fullName", Wire::asString);
        m.additionalProperties = Wire.extra(o, KNOWN);
        return m;
    }

    /**
     * Parses the object from JSON text.
     *
     * @param json JSON text
     * @return the object
     */
    public static Reference parse(String json) {
        return fromJson(Json.parse(json));
    }

    /**
     * QuickBooks ID of the referenced object.
     *
     * @return the value, or null
     */
    public String id() {
        return id;
    }

    /**
     * Full name of the referenced object at the time of the response.
     *
     * @return the value, or null
     */
    public String fullName() {
        return fullName;
    }

    /**
     * Members the API sent that this SDK version does not know.
     *
     * @return unmodifiable map, in wire order
     */
    public Map<String, Object> additionalProperties() {
        return additionalProperties;
    }

    @Override
    public Map<String, Object> toWire() {
        Map<String, Object> w = new LinkedHashMap<>();
        w.put("id", this.id);
        w.put("fullName", this.fullName);
        w.putAll(this.additionalProperties);
        return w;
    }

    @Override
    public String toString() {
        return "Reference" + toJson();
    }
}
