// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:1fc5496cc47b442606ea78c818f94a29798b32785dc14c59e7986e24f10bf332
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.InputObject;
import com.desktopaccountingapi.quickbooksdesktop.core.Wire;
import java.math.BigDecimal;

/**
 * Fields for creating a refund applied to transaction.
 *
 * <p>Fluent setters return this object. Fields you never set are not sent; on clearable fields, null is sent to clear the value.
 */
public final class RefundAppliedToTransactionCreateInput extends InputObject {
    /**
     * Creates an empty object. Set the required fields {@code transactionId}, {@code refundAmount} before sending.
     */
    public RefundAppliedToTransactionCreateInput() {
        super("transactionId", "refundAmount");
    }

    /**
     * Creates the object with its required fields.
     *
     * @param transactionId ID of the transaction.
     * @param refundAmount Refund amount of this refund applied to transaction. Decimal string with up to 2 decimal places.
     */
    public RefundAppliedToTransactionCreateInput(String transactionId, BigDecimal refundAmount) {
        this();
        transactionId(transactionId);
        refundAmount(refundAmount);
    }

    /**
     * ID of the transaction.
     *
     * <p>Required. Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public RefundAppliedToTransactionCreateInput transactionId(String value) {
        setOptional("transactionId", value);
        return this;
    }

    /**
     * The {@code transactionId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String transactionId() {
        return stored("transactionId");
    }

    /**
     * Refund amount of this refund applied to transaction. Decimal string with up to 2 decimal places.
     *
     * <p>Decimal; scale is preserved on the wire. Required. Example: <code>"1250.00"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public RefundAppliedToTransactionCreateInput refundAmount(BigDecimal value) {
        setOptional("refundAmount", Wire.decimalText(value));
        return this;
    }

    /**
     * The {@code refundAmount} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public BigDecimal refundAmount() {
        return Wire.decimalOrNull(stored("refundAmount"));
    }
}
