// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:d4adaec794b6cf028d0f87bcaed3668ec305d5e364a02008e8a22258ee3a7d59
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code ReportCategory} values.
 *
 * <p>Known values of an open set. The API may return values not listed here; treat unknown values as valid.
 */
public final class ReportCategory {
    private ReportCategory() {}

    /** {@code general_summary} */
    public static final String GENERAL_SUMMARY = "general_summary";

    /** {@code general_detail} */
    public static final String GENERAL_DETAIL = "general_detail";

    /** {@code aging} */
    public static final String AGING = "aging";

    /** {@code budget_summary} */
    public static final String BUDGET_SUMMARY = "budget_summary";

    /** {@code job} */
    public static final String JOB = "job";

    /** {@code time} */
    public static final String TIME = "time";

    /** {@code custom_detail} */
    public static final String CUSTOM_DETAIL = "custom_detail";

    /** {@code custom_summary} */
    public static final String CUSTOM_SUMMARY = "custom_summary";

    /** {@code payroll_detail} */
    public static final String PAYROLL_DETAIL = "payroll_detail";

    /** {@code payroll_summary} */
    public static final String PAYROLL_SUMMARY = "payroll_summary";
}
