// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:79b06eb2008381661d24d3bd5e23643483ec1bf9b70d5f4cdff2a2a71e22fe94
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code RequestOutcome} values.
 *
 * <p>Known values of an open set. The API may return values not listed here; treat unknown values as valid.
 */
public final class RequestOutcome {
    private RequestOutcome() {}

    /** {@code applied} */
    public static final String APPLIED = "applied";

    /** {@code not_applied} */
    public static final String NOT_APPLIED = "not_applied";

    /** {@code pending} */
    public static final String PENDING = "pending";

    /** {@code unknown} */
    public static final String UNKNOWN = "unknown";

    /** {@code not_applicable} */
    public static final String NOT_APPLICABLE = "not_applicable";
}
