// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:1cc3058cecb557ce1cc724d5236d36860df6bec39636e2d427c8a408bf5f2ca2
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code RequestSummaryOutcome} values.
 *
 * <p>Known values of an open set. The API may return values not listed here; treat unknown values as valid.
 */
public final class RequestSummaryOutcome {
    private RequestSummaryOutcome() {}

    /** {@code applied} */
    public static final String APPLIED = "applied";

    /** {@code not_applied} */
    public static final String NOT_APPLIED = "not_applied";

    /** {@code pending} */
    public static final String PENDING = "pending";

    /** {@code unknown} */
    public static final String UNKNOWN = "unknown";

    /** {@code not_applicable} */
    public static final String NOT_APPLICABLE = "not_applicable";
}
