// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:1cc3058cecb557ce1cc724d5236d36860df6bec39636e2d427c8a408bf5f2ca2
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code RequestWarningCode} values.
 *
 * <p>Known values of an open set. The API may return values not listed here; treat unknown values as valid.
 */
public final class RequestWarningCode {
    private RequestWarningCode() {}

    /** {@code QBD_WARNING} */
    public static final String QBD_WARNING = "QBD_WARNING";

    /** {@code QBD_VALUE_UNREADABLE} */
    public static final String QBD_VALUE_UNREADABLE = "QBD_VALUE_UNREADABLE";

    /** {@code QBD_MARKUP_REPAIRED} */
    public static final String QBD_MARKUP_REPAIRED = "QBD_MARKUP_REPAIRED";
}
