// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:b5774d24bc8154ccc2acb85370ae27581a072c3f5070a529111ee2dd26f103b9
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code RequestWarningCode} values.
 *
 * <p>Known values of an open set. The API may return values not listed here; treat unknown values as valid.
 */
public final class RequestWarningCode {
    private RequestWarningCode() {}

    /** {@code QBD_WARNING} */
    public static final String QBD_WARNING = "QBD_WARNING";

    /** {@code QBD_VALUE_UNREADABLE} */
    public static final String QBD_VALUE_UNREADABLE = "QBD_VALUE_UNREADABLE";

    /** {@code QBD_MARKUP_REPAIRED} */
    public static final String QBD_MARKUP_REPAIRED = "QBD_MARKUP_REPAIRED";
}
