// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:1cc3058cecb557ce1cc724d5236d36860df6bec39636e2d427c8a408bf5f2ca2
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code RequestUpdateInputTransactionMode} values.
 *
 * <p>Allowed values.
 */
public final class RequestUpdateInputTransactionMode {
    private RequestUpdateInputTransactionMode() {}

    /** {@code card_not_present} */
    public static final String CARD_NOT_PRESENT = "card_not_present";

    /** {@code card_present} */
    public static final String CARD_PRESENT = "card_present";
}
