// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:09aa9517f466027d023798abdf939204d057d808cb4eb15566deed6b960adcec
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code ResponseUpdateInputPaymentStatus} values.
 *
 * <p>Allowed values.
 */
public final class ResponseUpdateInputPaymentStatus {
    private ResponseUpdateInputPaymentStatus() {}

    /** {@code unknown} */
    public static final String UNKNOWN = "unknown";

    /** {@code completed} */
    public static final String COMPLETED = "completed";
}
