// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:1cc3058cecb557ce1cc724d5236d36860df6bec39636e2d427c8a408bf5f2ca2
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.InputObject;

/**
 * Fields for creating a sales tax code.
 *
 * <p>Fluent setters return this object. Fields you never set are not sent; on clearable fields, null is sent to clear the value.
 */
public final class SalesTaxCodeCreateInput extends InputObject {
    /**
     * Creates an empty object. Set the required fields {@code name}, {@code isTaxable} before sending.
     */
    public SalesTaxCodeCreateInput() {
        super("name", "isTaxable");
    }

    /**
     * Creates the object with its required fields.
     *
     * @param name Name of this sales tax code, unique within its parent level.
     * @param isTaxable Whether this sales tax code is taxable.
     */
    public SalesTaxCodeCreateInput(String name, Boolean isTaxable) {
        this();
        name(name);
        isTaxable(isTaxable);
    }

    /**
     * Name of this sales tax code, unique within its parent level.
     *
     * <p>Required.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesTaxCodeCreateInput name(String value) {
        setOptional("name", value);
        return this;
    }

    /**
     * The {@code name} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String name() {
        return value("name");
    }

    /**
     * Whether this sales tax code is active. Inactive objects stay in QuickBooks but are hidden from most lists.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesTaxCodeCreateInput isActive(Boolean value) {
        setOptional("isActive", value);
        return this;
    }

    /**
     * The {@code isActive} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Boolean isActive() {
        return value("isActive");
    }

    /**
     * Whether this sales tax code is taxable.
     *
     * <p>Required.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesTaxCodeCreateInput isTaxable(Boolean value) {
        setOptional("isTaxable", value);
        return this;
    }

    /**
     * The {@code isTaxable} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Boolean isTaxable() {
        return value("isTaxable");
    }

    /**
     * Description of this sales tax code.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesTaxCodeCreateInput description(String value) {
        setOptional("description", value);
        return this;
    }

    /**
     * The {@code description} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String description() {
        return value("description");
    }
}
