// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:d4adaec794b6cf028d0f87bcaed3668ec305d5e364a02008e8a22258ee3a7d59
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.InputObject;
import java.time.LocalDate;
import java.util.List;

/**
 * Fields for creating a sales receipt. Requires at least one of: lines or lineGroups.
 *
 * <p>Fluent setters return this object. Fields you never set are not sent; on clearable fields, null is sent to clear the value.
 */
public final class SalesReceiptCreateInput extends InputObject {
    /**
     * Creates an empty object.
     */
    public SalesReceiptCreateInput() {
        super();
    }

    /**
     * ID of the customer for this sales receipt.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptCreateInput customerId(String value) {
        setOptional("customerId", value);
        return this;
    }

    /**
     * The {@code customerId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String customerId() {
        return stored("customerId");
    }

    /**
     * ID of the class for this sales receipt.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptCreateInput classId(String value) {
        setOptional("classId", value);
        return this;
    }

    /**
     * The {@code classId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String classId() {
        return stored("classId");
    }

    /**
     * ID of the document template for this sales receipt.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptCreateInput documentTemplateId(String value) {
        setOptional("documentTemplateId", value);
        return this;
    }

    /**
     * The {@code documentTemplateId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String documentTemplateId() {
        return stored("documentTemplateId");
    }

    /**
     * Date of this sales receipt (YYYY-MM-DD).
     *
     * <p>Example: <code>"2026-10-05"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptCreateInput transactionDate(LocalDate value) {
        setOptional("transactionDate", value);
        return this;
    }

    /**
     * The {@code transactionDate} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public LocalDate transactionDate() {
        return stored("transactionDate");
    }

    /**
     * Reference number of this sales receipt, such as an invoice or check number. Case-sensitive.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptCreateInput refNumber(String value) {
        setOptional("refNumber", value);
        return this;
    }

    /**
     * The {@code refNumber} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String refNumber() {
        return stored("refNumber");
    }

    /**
     * Billing address for this sales receipt.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptCreateInput billingAddress(AddressCreateInput value) {
        setOptional("billingAddress", value);
        return this;
    }

    /**
     * The {@code billingAddress} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public AddressCreateInput billingAddress() {
        return stored("billingAddress");
    }

    /**
     * Shipping address for this sales receipt.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptCreateInput shippingAddress(AddressCreateInput value) {
        setOptional("shippingAddress", value);
        return this;
    }

    /**
     * The {@code shippingAddress} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public AddressCreateInput shippingAddress() {
        return stored("shippingAddress");
    }

    /**
     * Whether this sales receipt is pending (not yet final) and does not post to accounts.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptCreateInput isPending(Boolean value) {
        setOptional("isPending", value);
        return this;
    }

    /**
     * The {@code isPending} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Boolean isPending() {
        return stored("isPending");
    }

    /**
     * Check number of this sales receipt.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptCreateInput checkNumber(String value) {
        setOptional("checkNumber", value);
        return this;
    }

    /**
     * The {@code checkNumber} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String checkNumber() {
        return stored("checkNumber");
    }

    /**
     * ID of the payment method for this sales receipt.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptCreateInput paymentMethodId(String value) {
        setOptional("paymentMethodId", value);
        return this;
    }

    /**
     * The {@code paymentMethodId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String paymentMethodId() {
        return stored("paymentMethodId");
    }

    /**
     * Date payment of this sales receipt is due (YYYY-MM-DD).
     *
     * <p>Example: <code>"2026-10-05"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptCreateInput dueDate(LocalDate value) {
        setOptional("dueDate", value);
        return this;
    }

    /**
     * The {@code dueDate} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public LocalDate dueDate() {
        return stored("dueDate");
    }

    /**
     * ID of the sales representative for this sales receipt.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptCreateInput salesRepresentativeId(String value) {
        setOptional("salesRepresentativeId", value);
        return this;
    }

    /**
     * The {@code salesRepresentativeId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String salesRepresentativeId() {
        return stored("salesRepresentativeId");
    }

    /**
     * Date the goods on this sales receipt were or will be shipped (YYYY-MM-DD).
     *
     * <p>Example: <code>"2026-10-05"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptCreateInput shippingDate(LocalDate value) {
        setOptional("shippingDate", value);
        return this;
    }

    /**
     * The {@code shippingDate} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public LocalDate shippingDate() {
        return stored("shippingDate");
    }

    /**
     * ID of the shipping method for this sales receipt.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptCreateInput shippingMethodId(String value) {
        setOptional("shippingMethodId", value);
        return this;
    }

    /**
     * The {@code shippingMethodId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String shippingMethodId() {
        return stored("shippingMethodId");
    }

    /**
     * Shipment origin of this sales receipt.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptCreateInput shipmentOrigin(String value) {
        setOptional("shipmentOrigin", value);
        return this;
    }

    /**
     * The {@code shipmentOrigin} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String shipmentOrigin() {
        return stored("shipmentOrigin");
    }

    /**
     * ID of the sales tax item for this sales receipt.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptCreateInput salesTaxItemId(String value) {
        setOptional("salesTaxItemId", value);
        return this;
    }

    /**
     * The {@code salesTaxItemId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String salesTaxItemId() {
        return stored("salesTaxItemId");
    }

    /**
     * Internal memo for this sales receipt; shown in reports, not on printed forms.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptCreateInput memo(String value) {
        setOptional("memo", value);
        return this;
    }

    /**
     * The {@code memo} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String memo() {
        return stored("memo");
    }

    /**
     * ID of the customer message for this sales receipt.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptCreateInput customerMessageId(String value) {
        setOptional("customerMessageId", value);
        return this;
    }

    /**
     * The {@code customerMessageId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String customerMessageId() {
        return stored("customerMessageId");
    }

    /**
     * Whether this sales receipt is in the queue of forms to print.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptCreateInput isQueuedForPrint(Boolean value) {
        setOptional("isQueuedForPrint", value);
        return this;
    }

    /**
     * The {@code isQueuedForPrint} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Boolean isQueuedForPrint() {
        return stored("isQueuedForPrint");
    }

    /**
     * Whether this sales receipt is in the queue of forms to email.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptCreateInput isQueuedForEmail(Boolean value) {
        setOptional("isQueuedForEmail", value);
        return this;
    }

    /**
     * The {@code isQueuedForEmail} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Boolean isQueuedForEmail() {
        return stored("isQueuedForEmail");
    }

    /**
     * ID of the sales tax code for this sales receipt.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptCreateInput salesTaxCodeId(String value) {
        setOptional("salesTaxCodeId", value);
        return this;
    }

    /**
     * The {@code salesTaxCodeId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String salesTaxCodeId() {
        return stored("salesTaxCodeId");
    }

    /**
     * ID of the deposit to account for this sales receipt.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptCreateInput depositToAccountId(String value) {
        setOptional("depositToAccountId", value);
        return this;
    }

    /**
     * The {@code depositToAccountId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String depositToAccountId() {
        return stored("depositToAccountId");
    }

    /**
     * Credit card transaction details for this sales receipt.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptCreateInput creditCardTransaction(CreditCardTransactionCreateInput value) {
        setOptional("creditCardTransaction", value);
        return this;
    }

    /**
     * The {@code creditCardTransaction} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public CreditCardTransactionCreateInput creditCardTransaction() {
        return stored("creditCardTransaction");
    }

    /**
     * Built-in "Other" text field on this sales receipt.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptCreateInput otherCustomField(String value) {
        setOptional("otherCustomField", value);
        return this;
    }

    /**
     * The {@code otherCustomField} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String otherCustomField() {
        return stored("otherCustomField");
    }

    /**
     * Exchange rate from this sales receipt's currency to the home currency.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptCreateInput exchangeRate(Double value) {
        setOptional("exchangeRate", value);
        return this;
    }

    /**
     * Exchange rate from this sales receipt's currency to the home currency.
     *
     * @param value the value
     * @return this object
     */
    public SalesReceiptCreateInput exchangeRate(double value) {
        setOptional("exchangeRate", value);
        return this;
    }

    /**
     * The {@code exchangeRate} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Double exchangeRate() {
        return stored("exchangeRate");
    }

    /**
     * Your own UUID for this sales receipt, stored by QuickBooks so you can match records with your system.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptCreateInput externalId(String value) {
        setOptional("externalId", value);
        return this;
    }

    /**
     * The {@code externalId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String externalId() {
        return stored("externalId");
    }

    /**
     * Line items of this sales receipt.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptCreateInput lines(List<SalesReceiptLineCreateInput> value) {
        setOptional("lines", value);
        return this;
    }

    /**
     * The {@code lines} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public List<SalesReceiptLineCreateInput> lines() {
        return stored("lines");
    }

    /**
     * Group lines of this sales receipt: each expands an item group into its component lines.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptCreateInput lineGroups(List<SalesReceiptLineGroupCreateInput> value) {
        setOptional("lineGroups", value);
        return this;
    }

    /**
     * The {@code lineGroups} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public List<SalesReceiptLineGroupCreateInput> lineGroups() {
        return stored("lineGroups");
    }
}
