// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:b5774d24bc8154ccc2acb85370ae27581a072c3f5070a529111ee2dd26f103b9
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.InputObject;
import com.desktopaccountingapi.quickbooksdesktop.core.Wire;
import java.math.BigDecimal;

/**
 * Fields for updating a sales tax item.
 *
 * <p>Fluent setters return this object. Fields you never set are not sent; on clearable fields, null is sent to clear the value.
 */
public final class SalesTaxItemUpdateInput extends InputObject {
    /**
     * Creates an empty object. Set the required field {@code revisionNumber} before sending.
     */
    public SalesTaxItemUpdateInput() {
        super("revisionNumber");
    }

    /**
     * Creates the object with its required fields.
     *
     * @param revisionNumber Current revision of this sales tax item. Send it unchanged when updating; a stale value is rejected. QuickBooks changes it at most once per second, so a second edit within the same second keeps the same value. This API spaces its own consecutive writes to one object by over a second; edits made elsewhere in the same second are not detected.
     */
    public SalesTaxItemUpdateInput(String revisionNumber) {
        this();
        revisionNumber(revisionNumber);
    }

    /**
     * Current revision of this sales tax item. Send it unchanged when updating; a stale value is rejected. QuickBooks changes it at most once per second, so a second edit within the same second keeps the same value. This API spaces its own consecutive writes to one object by over a second; edits made elsewhere in the same second are not detected.
     *
     * <p>Required.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesTaxItemUpdateInput revisionNumber(String value) {
        setOptional("revisionNumber", value);
        return this;
    }

    /**
     * The {@code revisionNumber} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String revisionNumber() {
        return value("revisionNumber");
    }

    /**
     * Name of this sales tax item, unique within its parent level.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesTaxItemUpdateInput name(String value) {
        setOptional("name", value);
        return this;
    }

    /**
     * The {@code name} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String name() {
        return value("name");
    }

    /**
     * Barcode details for this sales tax item.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesTaxItemUpdateInput barcode(BarcodeUpdateInput value) {
        setOptional("barcode", value);
        return this;
    }

    /**
     * The {@code barcode} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public BarcodeUpdateInput barcode() {
        return value("barcode");
    }

    /**
     * Whether this sales tax item is active. Inactive objects stay in QuickBooks but are hidden from most lists.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesTaxItemUpdateInput isActive(Boolean value) {
        setOptional("isActive", value);
        return this;
    }

    /**
     * The {@code isActive} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Boolean isActive() {
        return value("isActive");
    }

    /**
     * ID of the class for this sales tax item.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesTaxItemUpdateInput classId(String value) {
        setOptional("classId", value);
        return this;
    }

    /**
     * The {@code classId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String classId() {
        return value("classId");
    }

    /**
     * Description of this sales tax item.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public SalesTaxItemUpdateInput description(String value) {
        setNullable("description", value);
        return this;
    }

    /**
     * The {@code description} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String description() {
        return value("description");
    }

    /**
     * Tax rate of this sales tax item. Percentage as a decimal string: "7.5" means 7.5 %.
     *
     * <p>Decimal; scale is preserved on the wire. Example: <code>"7.5"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesTaxItemUpdateInput taxRate(BigDecimal value) {
        setOptional("taxRate", Wire.decimalText(value));
        return this;
    }

    /**
     * The {@code taxRate} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public BigDecimal taxRate() {
        return Wire.decimalOrNull(value("taxRate"));
    }

    /**
     * ID of the tax vendor for this sales tax item.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesTaxItemUpdateInput taxVendorId(String value) {
        setOptional("taxVendorId", value);
        return this;
    }

    /**
     * The {@code taxVendorId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String taxVendorId() {
        return value("taxVendorId");
    }
}
