// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:b5774d24bc8154ccc2acb85370ae27581a072c3f5070a529111ee2dd26f103b9
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.InputObject;

/**
 * Fields for creating a sales representative.
 *
 * <p>Fluent setters return this object. Fields you never set are not sent; on clearable fields, null is sent to clear the value.
 */
public final class SalesRepresentativeCreateInput extends InputObject {
    /**
     * Creates an empty object. Set the required fields {@code initial}, {@code entityId} before sending.
     */
    public SalesRepresentativeCreateInput() {
        super("initial", "entityId");
    }

    /**
     * Creates the object with its required fields.
     *
     * @param initial Initial of this sales representative.
     * @param entityId ID of the entity for this sales representative.
     */
    public SalesRepresentativeCreateInput(String initial, String entityId) {
        this();
        initial(initial);
        entityId(entityId);
    }

    /**
     * Initial of this sales representative.
     *
     * <p>Required.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesRepresentativeCreateInput initial(String value) {
        setOptional("initial", value);
        return this;
    }

    /**
     * The {@code initial} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String initial() {
        return value("initial");
    }

    /**
     * Whether this sales representative is active. Inactive objects stay in QuickBooks but are hidden from most lists.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesRepresentativeCreateInput isActive(Boolean value) {
        setOptional("isActive", value);
        return this;
    }

    /**
     * The {@code isActive} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Boolean isActive() {
        return value("isActive");
    }

    /**
     * ID of the entity for this sales representative.
     *
     * <p>Required. Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesRepresentativeCreateInput entityId(String value) {
        setOptional("entityId", value);
        return this;
    }

    /**
     * The {@code entityId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String entityId() {
        return value("entityId");
    }
}
