// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:6f5ac28d7c33ac90aa7e2c15d88efd50e8e41c808bcc5489f0c8b1cb7833326a
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code SalesOrderCreateInputSalesChannelName} values.
 *
 * <p>Allowed values.
 */
public final class SalesOrderCreateInputSalesChannelName {
    private SalesOrderCreateInputSalesChannelName() {}

    /** {@code blank} */
    public static final String BLANK = "blank";

    /** {@code ecommerce} */
    public static final String ECOMMERCE = "ecommerce";
}
