// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:68a0d76d6b51187adfc66d768eae8e30675b5093f4ae538b0d9c32c905b9bb2d
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.InputObject;
import com.desktopaccountingapi.quickbooksdesktop.core.Wire;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

/**
 * Fields for creating a sales receipt line.
 *
 * <p>Fluent setters return this object. Fields you never set are not sent; on clearable fields, null is sent to clear the value.
 */
public final class SalesReceiptLineCreateInput extends InputObject {
    /**
     * Creates an empty object.
     */
    public SalesReceiptLineCreateInput() {
        super();
    }

    /**
     * ID of the item for this sales receipt line.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptLineCreateInput itemId(String value) {
        setOptional("itemId", value);
        return this;
    }

    /**
     * The {@code itemId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String itemId() {
        return value("itemId");
    }

    /**
     * Description of this sales receipt line.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptLineCreateInput description(String value) {
        setOptional("description", value);
        return this;
    }

    /**
     * The {@code description} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String description() {
        return value("description");
    }

    /**
     * Quantity of the item.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptLineCreateInput quantity(Double value) {
        setOptional("quantity", value);
        return this;
    }

    /**
     * Quantity of the item.
     *
     * @param value the value
     * @return this object
     */
    public SalesReceiptLineCreateInput quantity(double value) {
        setOptional("quantity", value);
        return this;
    }

    /**
     * The {@code quantity} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Double quantity() {
        return value("quantity");
    }

    /**
     * Unit of measure for the quantity.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptLineCreateInput unitOfMeasure(String value) {
        setOptional("unitOfMeasure", value);
        return this;
    }

    /**
     * The {@code unitOfMeasure} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String unitOfMeasure() {
        return value("unitOfMeasure");
    }

    /**
     * Price per unit, as a decimal string. Cannot be combined with ratePercent, priceLevelId.
     *
     * <p>Decimal; scale is preserved on the wire. Example: <code>"19.99"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptLineCreateInput rate(BigDecimal value) {
        setOptional("rate", Wire.decimalText(value));
        return this;
    }

    /**
     * The {@code rate} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public BigDecimal rate() {
        return Wire.decimalOrNull(value("rate"));
    }

    /**
     * Price as a percentage, for percentage-based items. Percentage as a decimal string: "7.5" means 7.5 %. Cannot be combined with rate, priceLevelId.
     *
     * <p>Decimal; scale is preserved on the wire. Example: <code>"7.5"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptLineCreateInput ratePercent(BigDecimal value) {
        setOptional("ratePercent", Wire.decimalText(value));
        return this;
    }

    /**
     * The {@code ratePercent} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public BigDecimal ratePercent() {
        return Wire.decimalOrNull(value("ratePercent"));
    }

    /**
     * ID of the price level for this sales receipt line. Cannot be combined with rate, ratePercent.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptLineCreateInput priceLevelId(String value) {
        setOptional("priceLevelId", value);
        return this;
    }

    /**
     * The {@code priceLevelId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String priceLevelId() {
        return value("priceLevelId");
    }

    /**
     * ID of the class for this sales receipt line.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptLineCreateInput classId(String value) {
        setOptional("classId", value);
        return this;
    }

    /**
     * The {@code classId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String classId() {
        return value("classId");
    }

    /**
     * Amount as a decimal string.
     *
     * <p>Decimal; scale is preserved on the wire. Example: <code>"1250.00"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptLineCreateInput amount(BigDecimal value) {
        setOptional("amount", Wire.decimalText(value));
        return this;
    }

    /**
     * The {@code amount} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public BigDecimal amount() {
        return Wire.decimalOrNull(value("amount"));
    }

    /**
     * Price rule conflict strategy of this sales receipt line.
     *
     * <p>Allowed values are in {@link SalesReceiptLineCreateInputPriceRuleConflictStrategy}.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptLineCreateInput priceRuleConflictStrategy(String value) {
        setOptional("priceRuleConflictStrategy", value);
        return this;
    }

    /**
     * The {@code priceRuleConflictStrategy} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String priceRuleConflictStrategy() {
        return value("priceRuleConflictStrategy");
    }

    /**
     * ID of the inventory site for this sales receipt line.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptLineCreateInput inventorySiteId(String value) {
        setOptional("inventorySiteId", value);
        return this;
    }

    /**
     * The {@code inventorySiteId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String inventorySiteId() {
        return value("inventorySiteId");
    }

    /**
     * ID of the inventory site location for this sales receipt line.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptLineCreateInput inventorySiteLocationId(String value) {
        setOptional("inventorySiteLocationId", value);
        return this;
    }

    /**
     * The {@code inventorySiteLocationId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String inventorySiteLocationId() {
        return value("inventorySiteLocationId");
    }

    /**
     * Serial number of this sales receipt line. Cannot be combined with lotNumber.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptLineCreateInput serialNumber(String value) {
        setOptional("serialNumber", value);
        return this;
    }

    /**
     * The {@code serialNumber} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String serialNumber() {
        return value("serialNumber");
    }

    /**
     * Lot number of this sales receipt line. Cannot be combined with serialNumber.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptLineCreateInput lotNumber(String value) {
        setOptional("lotNumber", value);
        return this;
    }

    /**
     * The {@code lotNumber} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String lotNumber() {
        return value("lotNumber");
    }

    /**
     * Date the service was performed (YYYY-MM-DD).
     *
     * <p>Example: <code>"2026-10-05"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptLineCreateInput serviceDate(LocalDate value) {
        setOptional("serviceDate", value);
        return this;
    }

    /**
     * The {@code serviceDate} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public LocalDate serviceDate() {
        return value("serviceDate");
    }

    /**
     * ID of the sales tax code for this sales receipt line.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptLineCreateInput salesTaxCodeId(String value) {
        setOptional("salesTaxCodeId", value);
        return this;
    }

    /**
     * The {@code salesTaxCodeId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String salesTaxCodeId() {
        return value("salesTaxCodeId");
    }

    /**
     * ID of the override item account for this sales receipt line.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptLineCreateInput overrideItemAccountId(String value) {
        setOptional("overrideItemAccountId", value);
        return this;
    }

    /**
     * The {@code overrideItemAccountId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String overrideItemAccountId() {
        return value("overrideItemAccountId");
    }

    /**
     * Built-in "Other 1" text field on this sales receipt line.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptLineCreateInput otherCustomField1(String value) {
        setOptional("otherCustomField1", value);
        return this;
    }

    /**
     * The {@code otherCustomField1} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String otherCustomField1() {
        return value("otherCustomField1");
    }

    /**
     * Built-in "Other 2" text field on this sales receipt line.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptLineCreateInput otherCustomField2(String value) {
        setOptional("otherCustomField2", value);
        return this;
    }

    /**
     * The {@code otherCustomField2} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String otherCustomField2() {
        return value("otherCustomField2");
    }

    /**
     * Credit card transaction details for this sales receipt line.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptLineCreateInput creditCardTransaction(CreditCardTransactionCreateInput value) {
        setOptional("creditCardTransaction", value);
        return this;
    }

    /**
     * The {@code creditCardTransaction} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public CreditCardTransactionCreateInput creditCardTransaction() {
        return value("creditCardTransaction");
    }

    /**
     * Custom field values QuickBooks stores on this sales receipt line.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SalesReceiptLineCreateInput customFields(List<CustomFieldCreateInput> value) {
        setOptional("customFields", value);
        return this;
    }

    /**
     * The {@code customFields} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public List<CustomFieldCreateInput> customFields() {
        return value("customFields");
    }
}
