// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:79b06eb2008381661d24d3bd5e23643483ec1bf9b70d5f4cdff2a2a71e22fe94
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.InputObject;

/**
 * Secondary contact details for this emergency contacts.
 *
 * <p>Fluent setters return this object. Fields you never set are not sent; on clearable fields, null is sent to clear the value.
 */
public final class SecondaryContactInput extends InputObject {
    /**
     * Creates an empty object. Set the required fields {@code name}, {@code valueValue} before sending.
     */
    public SecondaryContactInput() {
        super("name", "value");
    }

    /**
     * Creates the object with its required fields.
     *
     * @param name Name of this secondary contact, unique within its parent level.
     * @param valueValue Value.
     */
    public SecondaryContactInput(String name, String valueValue) {
        this();
        name(name);
        valueValue(valueValue);
    }

    /**
     * Name of this secondary contact, unique within its parent level.
     *
     * <p>Required.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SecondaryContactInput name(String value) {
        setOptional("name", value);
        return this;
    }

    /**
     * The {@code name} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String name() {
        return value("name");
    }

    /**
     * Value.
     *
     * <p>Required.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SecondaryContactInput valueValue(String value) {
        setOptional("value", value);
        return this;
    }

    /**
     * The {@code value} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String valueValue() {
        return value("value");
    }

    /**
     * Relation of this secondary contact.
     *
     * <p>Allowed values are in {@link SecondaryContactInputRelation}.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public SecondaryContactInput relation(String value) {
        setOptional("relation", value);
        return this;
    }

    /**
     * The {@code relation} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String relation() {
        return value("relation");
    }
}
