// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:6f5ac28d7c33ac90aa7e2c15d88efd50e8e41c808bcc5489f0c8b1cb7833326a
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.InputObject;

/**
 * Fields for updating a service item.
 *
 * <p>Fluent setters return this object. Fields you never set are not sent; on clearable fields, null is sent to clear the value.
 */
public final class ServiceItemUpdateInput extends InputObject {
    /**
     * Creates an empty object. Set the required field {@code revisionNumber} before sending.
     */
    public ServiceItemUpdateInput() {
        super("revisionNumber");
    }

    /**
     * Creates the object with its required fields.
     *
     * @param revisionNumber Current revision of this service item. Send it unchanged when updating; a stale value is rejected.
     */
    public ServiceItemUpdateInput(String revisionNumber) {
        this();
        revisionNumber(revisionNumber);
    }

    /**
     * Current revision of this service item. Send it unchanged when updating; a stale value is rejected.
     *
     * <p>Required.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ServiceItemUpdateInput revisionNumber(String value) {
        setOptional("revisionNumber", value);
        return this;
    }

    /**
     * The {@code revisionNumber} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String revisionNumber() {
        return value("revisionNumber");
    }

    /**
     * Name of this service item, unique within its parent level.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ServiceItemUpdateInput name(String value) {
        setOptional("name", value);
        return this;
    }

    /**
     * The {@code name} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String name() {
        return value("name");
    }

    /**
     * Barcode details for this service item.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ServiceItemUpdateInput barcode(BarcodeUpdateInput value) {
        setOptional("barcode", value);
        return this;
    }

    /**
     * The {@code barcode} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public BarcodeUpdateInput barcode() {
        return value("barcode");
    }

    /**
     * Whether this service item is active. Inactive objects stay in QuickBooks but are hidden from most lists.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ServiceItemUpdateInput isActive(Boolean value) {
        setOptional("isActive", value);
        return this;
    }

    /**
     * The {@code isActive} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Boolean isActive() {
        return value("isActive");
    }

    /**
     * ID of the class for this service item.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ServiceItemUpdateInput classId(String value) {
        setOptional("classId", value);
        return this;
    }

    /**
     * The {@code classId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String classId() {
        return value("classId");
    }

    /**
     * ID of the parent object, making this service item a child in the hierarchy.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ServiceItemUpdateInput parentId(String value) {
        setOptional("parentId", value);
        return this;
    }

    /**
     * The {@code parentId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String parentId() {
        return value("parentId");
    }

    /**
     * ID of the unit of measure set for this service item.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ServiceItemUpdateInput unitOfMeasureSetId(String value) {
        setOptional("unitOfMeasureSetId", value);
        return this;
    }

    /**
     * The {@code unitOfMeasureSetId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String unitOfMeasureSetId() {
        return value("unitOfMeasureSetId");
    }

    /**
     * Force unit of measure change of this service item.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ServiceItemUpdateInput forceUnitOfMeasureChange(Boolean value) {
        setOptional("forceUnitOfMeasureChange", value);
        return this;
    }

    /**
     * The {@code forceUnitOfMeasureChange} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Boolean forceUnitOfMeasureChange() {
        return value("forceUnitOfMeasureChange");
    }

    /**
     * ID of the sales tax code for this service item.
     *
     * <p>Example: <code>"80000001-1234567890"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ServiceItemUpdateInput salesTaxCodeId(String value) {
        setOptional("salesTaxCodeId", value);
        return this;
    }

    /**
     * The {@code salesTaxCodeId} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String salesTaxCodeId() {
        return value("salesTaxCodeId");
    }

    /**
     * Sales or purchase details details for this service item. Cannot be combined with salesAndPurchaseDetails.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ServiceItemUpdateInput salesOrPurchaseDetails(SalesOrPurchaseDetailUpdateInput value) {
        setOptional("salesOrPurchaseDetails", value);
        return this;
    }

    /**
     * The {@code salesOrPurchaseDetails} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public SalesOrPurchaseDetailUpdateInput salesOrPurchaseDetails() {
        return value("salesOrPurchaseDetails");
    }

    /**
     * Sales and purchase details details for this service item. Cannot be combined with salesOrPurchaseDetails.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ServiceItemUpdateInput salesAndPurchaseDetails(SalesAndPurchaseDetailUpdateInput value) {
        setOptional("salesAndPurchaseDetails", value);
        return this;
    }

    /**
     * The {@code salesAndPurchaseDetails} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public SalesAndPurchaseDetailUpdateInput salesAndPurchaseDetails() {
        return value("salesAndPurchaseDetails");
    }
}
