// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:09aa9517f466027d023798abdf939204d057d808cb4eb15566deed6b960adcec
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.InputObject;

/**
 * Fields for updating a ship to address.
 *
 * <p>Fluent setters return this object. Fields you never set are not sent; on clearable fields, null is sent to clear the value.
 */
public final class ShippingAddressUpdateInput extends InputObject {
    /**
     * Creates an empty object. Set the required field {@code name} before sending.
     */
    public ShippingAddressUpdateInput() {
        super("name");
    }

    /**
     * Creates the object with its required fields.
     *
     * @param name Name of this ship to address, unique within its parent level.
     */
    public ShippingAddressUpdateInput(String name) {
        this();
        name(name);
    }

    /**
     * Name of this ship to address, unique within its parent level.
     *
     * <p>Required.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ShippingAddressUpdateInput name(String value) {
        setOptional("name", value);
        return this;
    }

    /**
     * The {@code name} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String name() {
        return stored("name");
    }

    /**
     * First address line.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public ShippingAddressUpdateInput line1(String value) {
        setNullable("line1", value);
        return this;
    }

    /**
     * The {@code line1} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String line1() {
        return stored("line1");
    }

    /**
     * Second address line.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public ShippingAddressUpdateInput line2(String value) {
        setNullable("line2", value);
        return this;
    }

    /**
     * The {@code line2} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String line2() {
        return stored("line2");
    }

    /**
     * Third address line.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public ShippingAddressUpdateInput line3(String value) {
        setNullable("line3", value);
        return this;
    }

    /**
     * The {@code line3} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String line3() {
        return stored("line3");
    }

    /**
     * Fourth address line.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public ShippingAddressUpdateInput line4(String value) {
        setNullable("line4", value);
        return this;
    }

    /**
     * The {@code line4} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String line4() {
        return stored("line4");
    }

    /**
     * Fifth address line.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public ShippingAddressUpdateInput line5(String value) {
        setNullable("line5", value);
        return this;
    }

    /**
     * The {@code line5} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String line5() {
        return stored("line5");
    }

    /**
     * City or locality.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public ShippingAddressUpdateInput city(String value) {
        setNullable("city", value);
        return this;
    }

    /**
     * The {@code city} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String city() {
        return stored("city");
    }

    /**
     * State, province or region.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public ShippingAddressUpdateInput state(String value) {
        setNullable("state", value);
        return this;
    }

    /**
     * The {@code state} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String state() {
        return stored("state");
    }

    /**
     * Postal or ZIP code.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public ShippingAddressUpdateInput postalCode(String value) {
        setNullable("postalCode", value);
        return this;
    }

    /**
     * The {@code postalCode} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String postalCode() {
        return stored("postalCode");
    }

    /**
     * Country.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public ShippingAddressUpdateInput country(String value) {
        setNullable("country", value);
        return this;
    }

    /**
     * The {@code country} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String country() {
        return stored("country");
    }

    /**
     * Note for this ship to address.
     *
     * <p>Pass null to clear the value in QuickBooks.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public ShippingAddressUpdateInput note(String value) {
        setNullable("note", value);
        return this;
    }

    /**
     * The {@code note} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String note() {
        return stored("note");
    }

    /**
     * Whether this ship to address is default shipping address.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public ShippingAddressUpdateInput isDefaultShippingAddress(Boolean value) {
        setOptional("isDefaultShippingAddress", value);
        return this;
    }

    /**
     * The {@code isDefaultShippingAddress} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Boolean isDefaultShippingAddress() {
        return stored("isDefaultShippingAddress");
    }
}
