// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:09aa9517f466027d023798abdf939204d057d808cb4eb15566deed6b960adcec
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code SickHourInputAccrualPeriod} values.
 *
 * <p>Allowed values.
 */
public final class SickHourInputAccrualPeriod {
    private SickHourInputAccrualPeriod() {}

    /** {@code accrues_annually} */
    public static final String ACCRUES_ANNUALLY = "accrues_annually";

    /** {@code accrues_hourly} */
    public static final String ACCRUES_HOURLY = "accrues_hourly";

    /** {@code accrues_per_paycheck} */
    public static final String ACCRUES_PER_PAYCHECK = "accrues_per_paycheck";
}
