// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:68a0d76d6b51187adfc66d768eae8e30675b5093f4ae538b0d9c32c905b9bb2d
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code TemplateTemplateType} values.
 *
 * <p>Known values of an open set. The API may return values not listed here; treat unknown values as valid.
 */
public final class TemplateTemplateType {
    private TemplateTemplateType() {}

    /** {@code build_assembly} */
    public static final String BUILD_ASSEMBLY = "build_assembly";

    /** {@code credit_memo} */
    public static final String CREDIT_MEMO = "credit_memo";

    /** {@code estimate} */
    public static final String ESTIMATE = "estimate";

    /** {@code invoice} */
    public static final String INVOICE = "invoice";

    /** {@code purchase_order} */
    public static final String PURCHASE_ORDER = "purchase_order";

    /** {@code sales_order} */
    public static final String SALES_ORDER = "sales_order";

    /** {@code sales_receipt} */
    public static final String SALES_RECEIPT = "sales_receipt";

    /** {@code payment_receipt} */
    public static final String PAYMENT_RECEIPT = "payment_receipt";

    /** {@code bill_payment} */
    public static final String BILL_PAYMENT = "bill_payment";
}
