// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:6f5ac28d7c33ac90aa7e2c15d88efd50e8e41c808bcc5489f0c8b1cb7833326a
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code TimeReportType} values.
 *
 * <p>Allowed values.
 */
public final class TimeReportType {
    private TimeReportType() {}

    /** {@code time_by_item} */
    public static final String TIME_BY_ITEM = "time_by_item";

    /** {@code time_by_job_detail} */
    public static final String TIME_BY_JOB_DETAIL = "time_by_job_detail";

    /** {@code time_by_job_summary} */
    public static final String TIME_BY_JOB_SUMMARY = "time_by_job_summary";

    /** {@code time_by_name} */
    public static final String TIME_BY_NAME = "time_by_name";
}
