// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:68a0d76d6b51187adfc66d768eae8e30675b5093f4ae538b0d9c32c905b9bb2d
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code TransactionDetailLevel} values.
 *
 * <p>Allowed values.
 */
public final class TransactionDetailLevel {
    private TransactionDetailLevel() {}

    /** {@code all} */
    public static final String ALL = "all";

    /** {@code transactions_without_lines} */
    public static final String TRANSACTIONS_WITHOUT_LINES = "transactions_without_lines";

    /** {@code transaction_lines_only} */
    public static final String TRANSACTION_LINES_ONLY = "transaction_lines_only";
}
