// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:b5774d24bc8154ccc2acb85370ae27581a072c3f5070a529111ee2dd26f103b9
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code UnitOfMeasureSetCreateInputUnitOfMeasureType} values.
 *
 * <p>Allowed values.
 */
public final class UnitOfMeasureSetCreateInputUnitOfMeasureType {
    private UnitOfMeasureSetCreateInputUnitOfMeasureType() {}

    /** {@code area} */
    public static final String AREA = "area";

    /** {@code count} */
    public static final String COUNT = "count";

    /** {@code length} */
    public static final String LENGTH = "length";

    /** {@code other} */
    public static final String OTHER = "other";

    /** {@code time} */
    public static final String TIME = "time";

    /** {@code volume} */
    public static final String VOLUME = "volume";

    /** {@code weight} */
    public static final String WEIGHT = "weight";
}
