// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:79b06eb2008381661d24d3bd5e23643483ec1bf9b70d5f4cdff2a2a71e22fe94
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.InputObject;
import com.desktopaccountingapi.quickbooksdesktop.core.Json;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.List;

/**
 * Parameters for {@code qbd.unitOfMeasureSets.list query}.
 *
 * <p>Fluent setters return this object. Fields you never set are not sent; on clearable fields, null is sent to clear the value.
 */
public final class UnitOfMeasureSetListParams extends InputObject {
    /**
     * Creates an empty object.
     */
    public UnitOfMeasureSetListParams() {
        super();
    }

    /**
     * Return only the unit of measure sets with these QuickBooks IDs. Cannot be combined with names, limit, status, updatedAfter, updatedBefore, nameStartsWith, nameContains, nameEndsWith, nameFrom, nameTo.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public UnitOfMeasureSetListParams ids(List<String> value) {
        setOptional("ids", value);
        return this;
    }

    /**
     * The {@code ids} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public List<String> ids() {
        return value("ids");
    }

    /**
     * Return only the unit of measure sets with these names (case-insensitive). Cannot be combined with ids, limit, status, updatedAfter, updatedBefore, nameStartsWith, nameContains, nameEndsWith, nameFrom, nameTo.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public UnitOfMeasureSetListParams names(List<String> value) {
        setOptional("names", value);
        return this;
    }

    /**
     * The {@code names} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public List<String> names() {
        return value("names");
    }

    /**
     * Maximum number of unit of measure sets to return. Cannot be combined with ids, names.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public UnitOfMeasureSetListParams limit(Integer value) {
        setOptional("limit", value);
        return this;
    }

    /**
     * The {@code limit} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Integer limit() {
        return value("limit");
    }

    /**
     * Filter unit of measure sets by active state. Defaults to active ones only. Cannot be combined with ids, names.
     *
     * <p>Allowed values are in {@link ActiveStatus}.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public UnitOfMeasureSetListParams status(String value) {
        setOptional("status", value);
        return this;
    }

    /**
     * The {@code status} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String status() {
        return value("status");
    }

    /**
     * Return unit of measure sets changed on or after this date or date-time (QuickBooks local time unless an offset is given). Cannot be combined with ids, names.
     *
     * <p>Accepts a date ({@code YYYY-MM-DD}) or an ISO 8601 date-time. Example: <code>"2026-10-05T09:14:03-07:00"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public UnitOfMeasureSetListParams updatedAfter(String value) {
        setOptional("updatedAfter", value);
        return this;
    }

    /**
     * Return unit of measure sets changed on or after this date or date-time (QuickBooks local time unless an offset is given). Cannot be combined with ids, names.
     *
     * <p>Sent as {@code YYYY-MM-DD}.
     *
     * @param value the date
     * @return this object
     */
    public UnitOfMeasureSetListParams updatedAfter(LocalDate value) {
        setOptional("updatedAfter", value == null ? null : value.toString());
        return this;
    }

    /**
     * Return unit of measure sets changed on or after this date or date-time (QuickBooks local time unless an offset is given). Cannot be combined with ids, names.
     *
     * <p>Sent as an ISO 8601 date-time with seconds and offset.
     *
     * @param value the timestamp
     * @return this object
     */
    public UnitOfMeasureSetListParams updatedAfter(OffsetDateTime value) {
        setOptional("updatedAfter", value == null ? null : Json.formatDateTime(value));
        return this;
    }

    /**
     * The {@code updatedAfter} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String updatedAfter() {
        return value("updatedAfter");
    }

    /**
     * Return unit of measure sets changed on or before this date or date-time (QuickBooks local time unless an offset is given). Cannot be combined with ids, names.
     *
     * <p>Accepts a date ({@code YYYY-MM-DD}) or an ISO 8601 date-time. Example: <code>"2026-10-05T09:14:03-07:00"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public UnitOfMeasureSetListParams updatedBefore(String value) {
        setOptional("updatedBefore", value);
        return this;
    }

    /**
     * Return unit of measure sets changed on or before this date or date-time (QuickBooks local time unless an offset is given). Cannot be combined with ids, names.
     *
     * <p>Sent as {@code YYYY-MM-DD}.
     *
     * @param value the date
     * @return this object
     */
    public UnitOfMeasureSetListParams updatedBefore(LocalDate value) {
        setOptional("updatedBefore", value == null ? null : value.toString());
        return this;
    }

    /**
     * Return unit of measure sets changed on or before this date or date-time (QuickBooks local time unless an offset is given). Cannot be combined with ids, names.
     *
     * <p>Sent as an ISO 8601 date-time with seconds and offset.
     *
     * @param value the timestamp
     * @return this object
     */
    public UnitOfMeasureSetListParams updatedBefore(OffsetDateTime value) {
        setOptional("updatedBefore", value == null ? null : Json.formatDateTime(value));
        return this;
    }

    /**
     * The {@code updatedBefore} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String updatedBefore() {
        return value("updatedBefore");
    }

    /**
     * Return unit of measure sets whose name starts with this text (case-insensitive). Cannot be combined with ids, names, nameFrom, nameTo.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public UnitOfMeasureSetListParams nameStartsWith(String value) {
        setOptional("nameStartsWith", value);
        return this;
    }

    /**
     * The {@code nameStartsWith} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String nameStartsWith() {
        return value("nameStartsWith");
    }

    /**
     * Return unit of measure sets whose name contains this text (case-insensitive). Cannot be combined with ids, names, nameFrom, nameTo.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public UnitOfMeasureSetListParams nameContains(String value) {
        setOptional("nameContains", value);
        return this;
    }

    /**
     * The {@code nameContains} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String nameContains() {
        return value("nameContains");
    }

    /**
     * Return unit of measure sets whose name ends with this text (case-insensitive). Cannot be combined with ids, names, nameFrom, nameTo.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public UnitOfMeasureSetListParams nameEndsWith(String value) {
        setOptional("nameEndsWith", value);
        return this;
    }

    /**
     * The {@code nameEndsWith} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String nameEndsWith() {
        return value("nameEndsWith");
    }

    /**
     * Return unit of measure sets whose name sorts at or after this value. Cannot be combined with ids, names, nameStartsWith, nameContains, nameEndsWith.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public UnitOfMeasureSetListParams nameFrom(String value) {
        setOptional("nameFrom", value);
        return this;
    }

    /**
     * The {@code nameFrom} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String nameFrom() {
        return value("nameFrom");
    }

    /**
     * Return unit of measure sets whose name sorts at or before this value. Cannot be combined with ids, names, nameStartsWith, nameContains, nameEndsWith.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public UnitOfMeasureSetListParams nameTo(String value) {
        setOptional("nameTo", value);
        return this;
    }

    /**
     * The {@code nameTo} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String nameTo() {
        return value("nameTo");
    }
}
