// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:79b06eb2008381661d24d3bd5e23643483ec1bf9b70d5f4cdff2a2a71e22fe94
package com.desktopaccountingapi.quickbooksdesktop.models;

import com.desktopaccountingapi.quickbooksdesktop.core.InputObject;
import java.util.List;

/**
 * Parameters for {@code WebhookEndpointUpdateInput}.
 *
 * <p>Fluent setters return this object. Fields you never set are not sent; on clearable fields, null is sent to clear the value.
 */
public final class WebhookEndpointUpdateInput extends InputObject {
    /**
     * Creates an empty object.
     */
    public WebhookEndpointUpdateInput() {
        super();
    }

    /**
     * HTTPS URL on a public DNS name and the default port. IP addresses, internal names and redirects are not allowed.
     *
     * <p>Example: <code>"https://example.com/webhooks/desktop-accounting"</code>.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public WebhookEndpointUpdateInput url(String value) {
        setOptional("url", value);
        return this;
    }

    /**
     * The {@code url} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String url() {
        return value("url");
    }

    /**
     * Event types to deliver. At least one.
     *
     * <p>Values: see {@link WebhookEndpointUpdateInputEventType}.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public WebhookEndpointUpdateInput eventTypes(List<String> value) {
        setOptional("eventTypes", value);
        return this;
    }

    /**
     * The {@code eventTypes} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public List<String> eventTypes() {
        return value("eventTypes");
    }

    /**
     * Your note about the endpoint, up to 500 characters.
     *
     * <p>Pass null to clear the value in QuickBooks. Example: <code>"Production sync worker"</code>.
     *
     * @param value the value, or null to clear
     * @return this object
     */
    public WebhookEndpointUpdateInput description(String value) {
        setNullable("description", value);
        return this;
    }

    /**
     * The {@code description} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public String description() {
        return value("description");
    }

    /**
     * Turn delivery on or off. Enabling clears `disabledReason`.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public WebhookEndpointUpdateInput enabled(Boolean value) {
        setOptional("enabled", value);
        return this;
    }

    /**
     * The {@code enabled} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Boolean enabled() {
        return value("enabled");
    }

    /**
     * Also deliver request events for synchronous calls whose caller already received the result. Default `false`: synchronous requests produce events only when the caller did not get the final result (timeout after sending, disconnect) or the outcome is unknown.
     *
     * @param value the value, or null to unset
     * @return this object
     */
    public WebhookEndpointUpdateInput includeSyncRequests(Boolean value) {
        setOptional("includeSyncRequests", value);
        return this;
    }

    /**
     * The {@code includeSyncRequests} value set on this object.
     *
     * @return the value, or null if unset or set to null
     */
    public Boolean includeSyncRequests() {
        return value("includeSyncRequests");
    }
}
