// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:d4adaec794b6cf028d0f87bcaed3668ec305d5e364a02008e8a22258ee3a7d59
package com.desktopaccountingapi.quickbooksdesktop.models;

/**
 * Constants for {@code WebhookEndpointWithSecretEventType} values.
 *
 * <p>Known values of an open set. The API may return values not listed here; treat unknown values as valid.
 */
public final class WebhookEndpointWithSecretEventType {
    private WebhookEndpointWithSecretEventType() {}

    /** {@code request.succeeded} */
    public static final String REQUEST_SUCCEEDED = "request.succeeded";

    /** {@code request.failed} */
    public static final String REQUEST_FAILED = "request.failed";

    /** {@code request.canceled} */
    public static final String REQUEST_CANCELED = "request.canceled";

    /** {@code request.outcome_unknown} */
    public static final String REQUEST_OUTCOME_UNKNOWN = "request.outcome_unknown";

    /** {@code request.outcome_resolved} */
    public static final String REQUEST_OUTCOME_RESOLVED = "request.outcome_resolved";

    /** {@code connection.setup_completed} */
    public static final String CONNECTION_SETUP_COMPLETED = "connection.setup_completed";

    /** {@code connection.status_changed} */
    public static final String CONNECTION_STATUS_CHANGED = "connection.status_changed";

    /** {@code connection.company_file_remarked} */
    public static final String CONNECTION_COMPANY_FILE_REMARKED = "connection.company_file_remarked";
}
