// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:1cc3058cecb557ce1cc724d5236d36860df6bec39636e2d427c8a408bf5f2ca2
package com.desktopaccountingapi.quickbooksdesktop.services;

import com.desktopaccountingapi.quickbooksdesktop.core.ApiResponse;
import com.desktopaccountingapi.quickbooksdesktop.core.ClientCore;
import com.desktopaccountingapi.quickbooksdesktop.core.OperationSpec;
import com.desktopaccountingapi.quickbooksdesktop.core.Page;
import com.desktopaccountingapi.quickbooksdesktop.core.Pager;
import com.desktopaccountingapi.quickbooksdesktop.core.RequestHandle;
import com.desktopaccountingapi.quickbooksdesktop.core.RequestOptions;
import com.desktopaccountingapi.quickbooksdesktop.models.BuildAssembly;
import com.desktopaccountingapi.quickbooksdesktop.models.BuildAssemblyCreateInput;
import com.desktopaccountingapi.quickbooksdesktop.models.BuildAssemblyDeleted;
import com.desktopaccountingapi.quickbooksdesktop.models.BuildAssemblyListParams;
import com.desktopaccountingapi.quickbooksdesktop.models.BuildAssemblyUpdateInput;

/**
 * Operations under {@code client.qbd().buildAssemblies()} (Build assemblies).
 */
public final class QbdBuildAssembliesService {
    private static final OperationSpec OP_CREATE = OperationSpec.of("qbd.buildAssemblies.create", "POST", OperationSpec.WRITE | OperationSpec.END_USER | OperationSpec.SERVER_TIMEOUT | OperationSpec.ASYNC | OperationSpec.QUEUE_TTL);
    private static final OperationSpec OP_DELETE = OperationSpec.of("qbd.buildAssemblies.delete", "DELETE", OperationSpec.WRITE | OperationSpec.END_USER | OperationSpec.SERVER_TIMEOUT | OperationSpec.ASYNC | OperationSpec.QUEUE_TTL);
    private static final OperationSpec OP_LIST = OperationSpec.of("qbd.buildAssemblies.list", "GET", OperationSpec.END_USER | OperationSpec.SERVER_TIMEOUT | OperationSpec.ASYNC | OperationSpec.QUEUE_TTL);
    private static final OperationSpec OP_RETRIEVE = OperationSpec.of("qbd.buildAssemblies.retrieve", "GET", OperationSpec.END_USER | OperationSpec.SERVER_TIMEOUT | OperationSpec.ASYNC | OperationSpec.QUEUE_TTL);
    private static final OperationSpec OP_UPDATE = OperationSpec.of("qbd.buildAssemblies.update", "POST", OperationSpec.WRITE | OperationSpec.END_USER | OperationSpec.SERVER_TIMEOUT | OperationSpec.ASYNC | OperationSpec.QUEUE_TTL);

    private final ClientCore core;
    private final Enqueue enqueue;

    /**
     * Creates the service. Use the client's accessor instead of calling this.
     *
     * @param core the client engine
     */
    public QbdBuildAssembliesService(ClientCore core) {
        this.core = core;
        this.enqueue = new Enqueue();
    }

    /**
     * Async-mode variants of this resource's methods. Each returns a {@link RequestHandle} as soon as the API queued the request.
     *
     * @return the async-mode methods
     */
    public Enqueue enqueue() {
        return enqueue;
    }

    /**
     * Create a build assembly.
     *
     * <p>Creates a build assembly in QuickBooks Desktop and returns it. Send an `Idempotency-Key` header so a retry after a network error never creates a second build assembly (the SDKs do this for you). See [Idempotency and safe retries](https://www.desktopaccountingapi.com/docs/guides/idempotency/).
     *
     * <p>A write: the SDK sends an {@code Idempotency-Key} (yours, or a UUID generated once per call) and reuses it on every retry.
     *
     * <p>Runs against the end user's QuickBooks company file (client default end user, {@code forEndUser}, or {@code RequestOptions.endUserId}).
     *
     * <p>{@code POST /v1/quickbooks-desktop/build-assemblies} (operation {@code qbd.buildAssemblies.create}).
     *
     * @param params the request body
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link BuildAssembly}
     */
    public BuildAssembly create(BuildAssemblyCreateInput params, RequestOptions options) {
        return core.call(OP_CREATE, "/v1/quickbooks-desktop/build-assemblies", null, params, options, BuildAssembly::fromJson);
    }

    /**
     * Create a build assembly.
     *
     * <p>{@code POST /v1/quickbooks-desktop/build-assemblies} (operation {@code qbd.buildAssemblies.create}).
     *
     * @param params the request body
     * @return the {@link BuildAssembly}
     */
    public BuildAssembly create(BuildAssemblyCreateInput params) {
        return create(params, RequestOptions.NONE);
    }

    /**
     * Create a build assembly.
     *
     * <p>Creates a build assembly in QuickBooks Desktop and returns it. Send an `Idempotency-Key` header so a retry after a network error never creates a second build assembly (the SDKs do this for you). See [Idempotency and safe retries](https://www.desktopaccountingapi.com/docs/guides/idempotency/).
     *
     * <p>Like {@code create(...)}, but also returns the HTTP status and headers ({@code Daapi-Request-Id}, {@code Daapi-Warnings}).
     *
     * <p>{@code POST /v1/quickbooks-desktop/build-assemblies} (operation {@code qbd.buildAssemblies.create}).
     *
     * @param params the request body
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link BuildAssembly} with HTTP status and headers
     */
    public ApiResponse<BuildAssembly> createWithResponse(BuildAssemblyCreateInput params, RequestOptions options) {
        return core.callWithResponse(OP_CREATE, "/v1/quickbooks-desktop/build-assemblies", null, params, options, BuildAssembly::fromJson);
    }

    /**
     * Create a build assembly.
     *
     * <p>{@code POST /v1/quickbooks-desktop/build-assemblies} (operation {@code qbd.buildAssemblies.create}).
     *
     * @param params the request body
     * @return the {@link BuildAssembly} with HTTP status and headers
     */
    public ApiResponse<BuildAssembly> createWithResponse(BuildAssemblyCreateInput params) {
        return createWithResponse(params, RequestOptions.NONE);
    }

    /**
     * Delete a build assembly.
     *
     * <p>Permanently deletes a build assembly. Deleting cannot be undone. Deleted transactions remain visible for 90 days through the deleted-transactions list. Send an `Idempotency-Key` to make retries safe.
     *
     * <p>A write: the SDK sends an {@code Idempotency-Key} (yours, or a UUID generated once per call) and reuses it on every retry.
     *
     * <p>Runs against the end user's QuickBooks company file (client default end user, {@code forEndUser}, or {@code RequestOptions.endUserId}).
     *
     * <p>{@code DELETE /v1/quickbooks-desktop/build-assemblies/{id}} (operation {@code qbd.buildAssemblies.delete}).
     *
     * @param id QuickBooks ID of the build assembly.
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link BuildAssemblyDeleted}
     */
    public BuildAssemblyDeleted delete(String id, RequestOptions options) {
        return core.call(OP_DELETE, "/v1/quickbooks-desktop/build-assemblies/" + ClientCore.pathParam("id", id), null, null, options, BuildAssemblyDeleted::fromJson);
    }

    /**
     * Delete a build assembly.
     *
     * <p>{@code DELETE /v1/quickbooks-desktop/build-assemblies/{id}} (operation {@code qbd.buildAssemblies.delete}).
     *
     * @param id QuickBooks ID of the build assembly.
     * @return the {@link BuildAssemblyDeleted}
     */
    public BuildAssemblyDeleted delete(String id) {
        return delete(id, RequestOptions.NONE);
    }

    /**
     * Delete a build assembly.
     *
     * <p>Permanently deletes a build assembly. Deleting cannot be undone. Deleted transactions remain visible for 90 days through the deleted-transactions list. Send an `Idempotency-Key` to make retries safe.
     *
     * <p>Like {@code delete(...)}, but also returns the HTTP status and headers ({@code Daapi-Request-Id}, {@code Daapi-Warnings}).
     *
     * <p>{@code DELETE /v1/quickbooks-desktop/build-assemblies/{id}} (operation {@code qbd.buildAssemblies.delete}).
     *
     * @param id QuickBooks ID of the build assembly.
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link BuildAssemblyDeleted} with HTTP status and headers
     */
    public ApiResponse<BuildAssemblyDeleted> deleteWithResponse(String id, RequestOptions options) {
        return core.callWithResponse(OP_DELETE, "/v1/quickbooks-desktop/build-assemblies/" + ClientCore.pathParam("id", id), null, null, options, BuildAssemblyDeleted::fromJson);
    }

    /**
     * Delete a build assembly.
     *
     * <p>{@code DELETE /v1/quickbooks-desktop/build-assemblies/{id}} (operation {@code qbd.buildAssemblies.delete}).
     *
     * @param id QuickBooks ID of the build assembly.
     * @return the {@link BuildAssemblyDeleted} with HTTP status and headers
     */
    public ApiResponse<BuildAssemblyDeleted> deleteWithResponse(String id) {
        return deleteWithResponse(id, RequestOptions.NONE);
    }

    /**
     * List build assemblies.
     *
     * <p>Returns the build assemblies that match your filters. Results are paged: pass `nextCursor` as `cursor` until `hasMore` is false. A cursor lives only inside the current QuickBooks session, so request the next page promptly; an expired cursor returns `410 CURSOR_EXPIRED`. See [Pagination](https://www.desktopaccountingapi.com/docs/guides/pagination/).
     *
     * <p>Returns a lazy {@link Pager}: iterate it for every item (one page of read-ahead) or call {@code firstPage()}.
     *
     * <p>Runs against the end user's QuickBooks company file (client default end user, {@code forEndUser}, or {@code RequestOptions.endUserId}).
     *
     * <p>{@code GET /v1/quickbooks-desktop/build-assemblies} (operation {@code qbd.buildAssemblies.list}).
     *
     * @param params the query parameters
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return a lazy pager over {@link BuildAssembly} items
     */
    public Pager<BuildAssembly> list(BuildAssemblyListParams params, RequestOptions options) {
        return core.paginate(OP_LIST, "/v1/quickbooks-desktop/build-assemblies", params, options, BuildAssembly::fromJson);
    }

    /**
     * List build assemblies.
     *
     * <p>{@code GET /v1/quickbooks-desktop/build-assemblies} (operation {@code qbd.buildAssemblies.list}).
     *
     * @param params the query parameters
     * @return a lazy pager over {@link BuildAssembly} items
     */
    public Pager<BuildAssembly> list(BuildAssemblyListParams params) {
        return list(params, RequestOptions.NONE);
    }

    /**
     * List build assemblies.
     *
     * <p>{@code GET /v1/quickbooks-desktop/build-assemblies} (operation {@code qbd.buildAssemblies.list}).
     *
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return a lazy pager over {@link BuildAssembly} items
     */
    public Pager<BuildAssembly> list(RequestOptions options) {
        return list(new BuildAssemblyListParams(), options);
    }

    /**
     * List build assemblies.
     *
     * <p>{@code GET /v1/quickbooks-desktop/build-assemblies} (operation {@code qbd.buildAssemblies.list}).
     *
     * @return a lazy pager over {@link BuildAssembly} items
     */
    public Pager<BuildAssembly> list() {
        return list(new BuildAssemblyListParams(), RequestOptions.NONE);
    }

    /**
     * Retrieve a build assembly.
     *
     * <p>Returns one build assembly by its QuickBooks ID. An unknown ID returns `404 QBD_OBJECT_NOT_FOUND`.
     *
     * <p>Runs against the end user's QuickBooks company file (client default end user, {@code forEndUser}, or {@code RequestOptions.endUserId}).
     *
     * <p>{@code GET /v1/quickbooks-desktop/build-assemblies/{id}} (operation {@code qbd.buildAssemblies.retrieve}).
     *
     * @param id QuickBooks ID of the build assembly.
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link BuildAssembly}
     */
    public BuildAssembly retrieve(String id, RequestOptions options) {
        return core.call(OP_RETRIEVE, "/v1/quickbooks-desktop/build-assemblies/" + ClientCore.pathParam("id", id), null, null, options, BuildAssembly::fromJson);
    }

    /**
     * Retrieve a build assembly.
     *
     * <p>{@code GET /v1/quickbooks-desktop/build-assemblies/{id}} (operation {@code qbd.buildAssemblies.retrieve}).
     *
     * @param id QuickBooks ID of the build assembly.
     * @return the {@link BuildAssembly}
     */
    public BuildAssembly retrieve(String id) {
        return retrieve(id, RequestOptions.NONE);
    }

    /**
     * Retrieve a build assembly.
     *
     * <p>Returns one build assembly by its QuickBooks ID. An unknown ID returns `404 QBD_OBJECT_NOT_FOUND`.
     *
     * <p>Like {@code retrieve(...)}, but also returns the HTTP status and headers ({@code Daapi-Request-Id}, {@code Daapi-Warnings}).
     *
     * <p>{@code GET /v1/quickbooks-desktop/build-assemblies/{id}} (operation {@code qbd.buildAssemblies.retrieve}).
     *
     * @param id QuickBooks ID of the build assembly.
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link BuildAssembly} with HTTP status and headers
     */
    public ApiResponse<BuildAssembly> retrieveWithResponse(String id, RequestOptions options) {
        return core.callWithResponse(OP_RETRIEVE, "/v1/quickbooks-desktop/build-assemblies/" + ClientCore.pathParam("id", id), null, null, options, BuildAssembly::fromJson);
    }

    /**
     * Retrieve a build assembly.
     *
     * <p>{@code GET /v1/quickbooks-desktop/build-assemblies/{id}} (operation {@code qbd.buildAssemblies.retrieve}).
     *
     * @param id QuickBooks ID of the build assembly.
     * @return the {@link BuildAssembly} with HTTP status and headers
     */
    public ApiResponse<BuildAssembly> retrieveWithResponse(String id) {
        return retrieveWithResponse(id, RequestOptions.NONE);
    }

    /**
     * Update a build assembly.
     *
     * <p>Changes the fields you send on an existing build assembly and leaves omitted fields unchanged. Requires the current `revisionNumber`. A stale `revisionNumber` returns `409 QBD_REVISION_NUMBER_STALE`: retrieve the build assembly, reapply your change and send the new revision. See [Updates and line items](https://www.desktopaccountingapi.com/docs/quickbooks/updates-and-line-items/).
     *
     * <p>A write: the SDK sends an {@code Idempotency-Key} (yours, or a UUID generated once per call) and reuses it on every retry.
     *
     * <p>Runs against the end user's QuickBooks company file (client default end user, {@code forEndUser}, or {@code RequestOptions.endUserId}).
     *
     * <p>{@code POST /v1/quickbooks-desktop/build-assemblies/{id}} (operation {@code qbd.buildAssemblies.update}).
     *
     * @param id QuickBooks ID of the build assembly.
     * @param params the request body
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link BuildAssembly}
     */
    public BuildAssembly update(String id, BuildAssemblyUpdateInput params, RequestOptions options) {
        return core.call(OP_UPDATE, "/v1/quickbooks-desktop/build-assemblies/" + ClientCore.pathParam("id", id), null, params, options, BuildAssembly::fromJson);
    }

    /**
     * Update a build assembly.
     *
     * <p>{@code POST /v1/quickbooks-desktop/build-assemblies/{id}} (operation {@code qbd.buildAssemblies.update}).
     *
     * @param id QuickBooks ID of the build assembly.
     * @param params the request body
     * @return the {@link BuildAssembly}
     */
    public BuildAssembly update(String id, BuildAssemblyUpdateInput params) {
        return update(id, params, RequestOptions.NONE);
    }

    /**
     * Update a build assembly.
     *
     * <p>Changes the fields you send on an existing build assembly and leaves omitted fields unchanged. Requires the current `revisionNumber`. A stale `revisionNumber` returns `409 QBD_REVISION_NUMBER_STALE`: retrieve the build assembly, reapply your change and send the new revision. See [Updates and line items](https://www.desktopaccountingapi.com/docs/quickbooks/updates-and-line-items/).
     *
     * <p>Like {@code update(...)}, but also returns the HTTP status and headers ({@code Daapi-Request-Id}, {@code Daapi-Warnings}).
     *
     * <p>{@code POST /v1/quickbooks-desktop/build-assemblies/{id}} (operation {@code qbd.buildAssemblies.update}).
     *
     * @param id QuickBooks ID of the build assembly.
     * @param params the request body
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link BuildAssembly} with HTTP status and headers
     */
    public ApiResponse<BuildAssembly> updateWithResponse(String id, BuildAssemblyUpdateInput params, RequestOptions options) {
        return core.callWithResponse(OP_UPDATE, "/v1/quickbooks-desktop/build-assemblies/" + ClientCore.pathParam("id", id), null, params, options, BuildAssembly::fromJson);
    }

    /**
     * Update a build assembly.
     *
     * <p>{@code POST /v1/quickbooks-desktop/build-assemblies/{id}} (operation {@code qbd.buildAssemblies.update}).
     *
     * @param id QuickBooks ID of the build assembly.
     * @param params the request body
     * @return the {@link BuildAssembly} with HTTP status and headers
     */
    public ApiResponse<BuildAssembly> updateWithResponse(String id, BuildAssemblyUpdateInput params) {
        return updateWithResponse(id, params, RequestOptions.NONE);
    }

    /**
     * Async-mode ({@code Prefer: respond-async}) variants of the methods of {@link QbdBuildAssembliesService}.
     */
    public final class Enqueue {
        private Enqueue() {}

        /**
         * Create a build assembly.
         *
         * <p>Creates a build assembly in QuickBooks Desktop and returns it. Send an `Idempotency-Key` header so a retry after a network error never creates a second build assembly (the SDKs do this for you). See [Idempotency and safe retries](https://www.desktopaccountingapi.com/docs/guides/idempotency/).
         *
         * <p>Async mode: sends {@code Prefer: respond-async} and returns as soon as the API queued the request ({@code 202}). Use the handle's {@code await()} or {@code result()} to get the outcome.
         *
         * <p>{@code POST /v1/quickbooks-desktop/build-assemblies} (operation {@code qbd.buildAssemblies.create}).
         *
         * @param params the request body
         * @param options per-call options (end user, idempotency key, timeouts, retries)
         * @return a handle on the queued request
         */
        public RequestHandle<BuildAssembly> create(BuildAssemblyCreateInput params, RequestOptions options) {
            return core.enqueue(OP_CREATE, "/v1/quickbooks-desktop/build-assemblies", null, params, options, BuildAssembly::fromJson);
        }

        /**
         * Create a build assembly.
         *
         * <p>{@code POST /v1/quickbooks-desktop/build-assemblies} (operation {@code qbd.buildAssemblies.create}).
         *
         * @param params the request body
         * @return a handle on the queued request
         */
        public RequestHandle<BuildAssembly> create(BuildAssemblyCreateInput params) {
            return create(params, RequestOptions.NONE);
        }

        /**
         * Delete a build assembly.
         *
         * <p>Permanently deletes a build assembly. Deleting cannot be undone. Deleted transactions remain visible for 90 days through the deleted-transactions list. Send an `Idempotency-Key` to make retries safe.
         *
         * <p>Async mode: sends {@code Prefer: respond-async} and returns as soon as the API queued the request ({@code 202}). Use the handle's {@code await()} or {@code result()} to get the outcome.
         *
         * <p>{@code DELETE /v1/quickbooks-desktop/build-assemblies/{id}} (operation {@code qbd.buildAssemblies.delete}).
         *
         * @param id QuickBooks ID of the build assembly.
         * @param options per-call options (end user, idempotency key, timeouts, retries)
         * @return a handle on the queued request
         */
        public RequestHandle<BuildAssemblyDeleted> delete(String id, RequestOptions options) {
            return core.enqueue(OP_DELETE, "/v1/quickbooks-desktop/build-assemblies/" + ClientCore.pathParam("id", id), null, null, options, BuildAssemblyDeleted::fromJson);
        }

        /**
         * Delete a build assembly.
         *
         * <p>{@code DELETE /v1/quickbooks-desktop/build-assemblies/{id}} (operation {@code qbd.buildAssemblies.delete}).
         *
         * @param id QuickBooks ID of the build assembly.
         * @return a handle on the queued request
         */
        public RequestHandle<BuildAssemblyDeleted> delete(String id) {
            return delete(id, RequestOptions.NONE);
        }

        /**
         * List build assemblies.
         *
         * <p>Returns the build assemblies that match your filters. Results are paged: pass `nextCursor` as `cursor` until `hasMore` is false. A cursor lives only inside the current QuickBooks session, so request the next page promptly; an expired cursor returns `410 CURSOR_EXPIRED`. See [Pagination](https://www.desktopaccountingapi.com/docs/guides/pagination/).
         *
         * <p>Async mode: sends {@code Prefer: respond-async} and returns as soon as the API queued the request ({@code 202}). Use the handle's {@code await()} or {@code result()} to get the outcome.
         *
         * <p>{@code GET /v1/quickbooks-desktop/build-assemblies} (operation {@code qbd.buildAssemblies.list}).
         *
         * @param params the query parameters
         * @param options per-call options (end user, idempotency key, timeouts, retries)
         * @return a handle on the queued request
         */
        public RequestHandle<Page<BuildAssembly>> list(BuildAssemblyListParams params, RequestOptions options) {
            return core.enqueue(OP_LIST, "/v1/quickbooks-desktop/build-assemblies", params, null, options, Page.parser(BuildAssembly::fromJson));
        }

        /**
         * List build assemblies.
         *
         * <p>{@code GET /v1/quickbooks-desktop/build-assemblies} (operation {@code qbd.buildAssemblies.list}).
         *
         * @param params the query parameters
         * @return a handle on the queued request
         */
        public RequestHandle<Page<BuildAssembly>> list(BuildAssemblyListParams params) {
            return list(params, RequestOptions.NONE);
        }

        /**
         * List build assemblies.
         *
         * <p>{@code GET /v1/quickbooks-desktop/build-assemblies} (operation {@code qbd.buildAssemblies.list}).
         *
         * @param options per-call options (end user, idempotency key, timeouts, retries)
         * @return a handle on the queued request
         */
        public RequestHandle<Page<BuildAssembly>> list(RequestOptions options) {
            return list(new BuildAssemblyListParams(), options);
        }

        /**
         * List build assemblies.
         *
         * <p>{@code GET /v1/quickbooks-desktop/build-assemblies} (operation {@code qbd.buildAssemblies.list}).
         *
         * @return a handle on the queued request
         */
        public RequestHandle<Page<BuildAssembly>> list() {
            return list(new BuildAssemblyListParams(), RequestOptions.NONE);
        }

        /**
         * Retrieve a build assembly.
         *
         * <p>Returns one build assembly by its QuickBooks ID. An unknown ID returns `404 QBD_OBJECT_NOT_FOUND`.
         *
         * <p>Async mode: sends {@code Prefer: respond-async} and returns as soon as the API queued the request ({@code 202}). Use the handle's {@code await()} or {@code result()} to get the outcome.
         *
         * <p>{@code GET /v1/quickbooks-desktop/build-assemblies/{id}} (operation {@code qbd.buildAssemblies.retrieve}).
         *
         * @param id QuickBooks ID of the build assembly.
         * @param options per-call options (end user, idempotency key, timeouts, retries)
         * @return a handle on the queued request
         */
        public RequestHandle<BuildAssembly> retrieve(String id, RequestOptions options) {
            return core.enqueue(OP_RETRIEVE, "/v1/quickbooks-desktop/build-assemblies/" + ClientCore.pathParam("id", id), null, null, options, BuildAssembly::fromJson);
        }

        /**
         * Retrieve a build assembly.
         *
         * <p>{@code GET /v1/quickbooks-desktop/build-assemblies/{id}} (operation {@code qbd.buildAssemblies.retrieve}).
         *
         * @param id QuickBooks ID of the build assembly.
         * @return a handle on the queued request
         */
        public RequestHandle<BuildAssembly> retrieve(String id) {
            return retrieve(id, RequestOptions.NONE);
        }

        /**
         * Update a build assembly.
         *
         * <p>Changes the fields you send on an existing build assembly and leaves omitted fields unchanged. Requires the current `revisionNumber`. A stale `revisionNumber` returns `409 QBD_REVISION_NUMBER_STALE`: retrieve the build assembly, reapply your change and send the new revision. See [Updates and line items](https://www.desktopaccountingapi.com/docs/quickbooks/updates-and-line-items/).
         *
         * <p>Async mode: sends {@code Prefer: respond-async} and returns as soon as the API queued the request ({@code 202}). Use the handle's {@code await()} or {@code result()} to get the outcome.
         *
         * <p>{@code POST /v1/quickbooks-desktop/build-assemblies/{id}} (operation {@code qbd.buildAssemblies.update}).
         *
         * @param id QuickBooks ID of the build assembly.
         * @param params the request body
         * @param options per-call options (end user, idempotency key, timeouts, retries)
         * @return a handle on the queued request
         */
        public RequestHandle<BuildAssembly> update(String id, BuildAssemblyUpdateInput params, RequestOptions options) {
            return core.enqueue(OP_UPDATE, "/v1/quickbooks-desktop/build-assemblies/" + ClientCore.pathParam("id", id), null, params, options, BuildAssembly::fromJson);
        }

        /**
         * Update a build assembly.
         *
         * <p>{@code POST /v1/quickbooks-desktop/build-assemblies/{id}} (operation {@code qbd.buildAssemblies.update}).
         *
         * @param id QuickBooks ID of the build assembly.
         * @param params the request body
         * @return a handle on the queued request
         */
        public RequestHandle<BuildAssembly> update(String id, BuildAssemblyUpdateInput params) {
            return update(id, params, RequestOptions.NONE);
        }
    }
}
