// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:b5774d24bc8154ccc2acb85370ae27581a072c3f5070a529111ee2dd26f103b9
package com.desktopaccountingapi.quickbooksdesktop.services;

import com.desktopaccountingapi.quickbooksdesktop.core.ApiResponse;
import com.desktopaccountingapi.quickbooksdesktop.core.ClientCore;
import com.desktopaccountingapi.quickbooksdesktop.core.OperationSpec;
import com.desktopaccountingapi.quickbooksdesktop.core.Page;
import com.desktopaccountingapi.quickbooksdesktop.core.Pager;
import com.desktopaccountingapi.quickbooksdesktop.core.RequestHandle;
import com.desktopaccountingapi.quickbooksdesktop.core.RequestOptions;
import com.desktopaccountingapi.quickbooksdesktop.models.CreditCardCredit;
import com.desktopaccountingapi.quickbooksdesktop.models.CreditCardCreditCreateInput;
import com.desktopaccountingapi.quickbooksdesktop.models.CreditCardCreditDeleted;
import com.desktopaccountingapi.quickbooksdesktop.models.CreditCardCreditListParams;
import com.desktopaccountingapi.quickbooksdesktop.models.CreditCardCreditUpdateInput;
import com.desktopaccountingapi.quickbooksdesktop.models.CreditCardCreditVoided;

/**
 * Operations under {@code client.qbd().creditCardCredits()} (Credit card credits).
 */
public final class QbdCreditCardCreditsService {
    private static final OperationSpec OP_CREATE = OperationSpec.of("qbd.creditCardCredits.create", "POST", OperationSpec.WRITE | OperationSpec.END_USER | OperationSpec.SERVER_TIMEOUT | OperationSpec.ASYNC | OperationSpec.QUEUE_TTL);
    private static final OperationSpec OP_DELETE = OperationSpec.of("qbd.creditCardCredits.delete", "DELETE", OperationSpec.WRITE | OperationSpec.END_USER | OperationSpec.SERVER_TIMEOUT | OperationSpec.ASYNC | OperationSpec.QUEUE_TTL);
    private static final OperationSpec OP_LIST = OperationSpec.of("qbd.creditCardCredits.list", "GET", OperationSpec.END_USER | OperationSpec.SERVER_TIMEOUT | OperationSpec.ASYNC | OperationSpec.QUEUE_TTL);
    private static final OperationSpec OP_RETRIEVE = OperationSpec.of("qbd.creditCardCredits.retrieve", "GET", OperationSpec.END_USER | OperationSpec.SERVER_TIMEOUT | OperationSpec.ASYNC | OperationSpec.QUEUE_TTL);
    private static final OperationSpec OP_UPDATE = OperationSpec.of("qbd.creditCardCredits.update", "POST", OperationSpec.WRITE | OperationSpec.END_USER | OperationSpec.SERVER_TIMEOUT | OperationSpec.ASYNC | OperationSpec.QUEUE_TTL);
    private static final OperationSpec OP_VOID = OperationSpec.of("qbd.creditCardCredits.void", "POST", OperationSpec.WRITE | OperationSpec.END_USER | OperationSpec.SERVER_TIMEOUT | OperationSpec.ASYNC | OperationSpec.QUEUE_TTL);

    private final ClientCore core;
    private final Enqueue enqueue;

    /**
     * Creates the service. Use the client's accessor instead of calling this.
     *
     * @param core the client engine
     */
    public QbdCreditCardCreditsService(ClientCore core) {
        this.core = core;
        this.enqueue = new Enqueue();
    }

    /**
     * Async-mode variants of this resource's methods. Each returns a {@link RequestHandle} as soon as the API queued the request.
     *
     * @return the async-mode methods
     */
    public Enqueue enqueue() {
        return enqueue;
    }

    /**
     * Create a credit card credit.
     *
     * <p>Creates a credit card credit in QuickBooks Desktop and returns it. Send an `Idempotency-Key` header so a retry after a network error never creates a second credit card credit (the SDKs do this for you). See [Idempotency and safe retries](https://www.desktopaccountingapi.com/docs/guides/idempotency/).
     *
     * <p>A write: the SDK sends an {@code Idempotency-Key} (yours, or a UUID generated once per call) and reuses it on every retry.
     *
     * <p>Runs against the end user's QuickBooks company file (client default end user, {@code forEndUser}, or {@code RequestOptions.endUserId}).
     *
     * <p>{@code POST /v1/quickbooks-desktop/credit-card-credits} (operation {@code qbd.creditCardCredits.create}).
     *
     * @param params the request body
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link CreditCardCredit}
     */
    public CreditCardCredit create(CreditCardCreditCreateInput params, RequestOptions options) {
        return core.call(OP_CREATE, "/v1/quickbooks-desktop/credit-card-credits", null, params, options, CreditCardCredit::fromJson);
    }

    /**
     * Create a credit card credit.
     *
     * <p>{@code POST /v1/quickbooks-desktop/credit-card-credits} (operation {@code qbd.creditCardCredits.create}).
     *
     * @param params the request body
     * @return the {@link CreditCardCredit}
     */
    public CreditCardCredit create(CreditCardCreditCreateInput params) {
        return create(params, RequestOptions.NONE);
    }

    /**
     * Create a credit card credit.
     *
     * <p>Creates a credit card credit in QuickBooks Desktop and returns it. Send an `Idempotency-Key` header so a retry after a network error never creates a second credit card credit (the SDKs do this for you). See [Idempotency and safe retries](https://www.desktopaccountingapi.com/docs/guides/idempotency/).
     *
     * <p>Like {@code create(...)}, but also returns the HTTP status and headers ({@code Daapi-Request-Id}, {@code Daapi-Warnings}).
     *
     * <p>{@code POST /v1/quickbooks-desktop/credit-card-credits} (operation {@code qbd.creditCardCredits.create}).
     *
     * @param params the request body
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link CreditCardCredit} with HTTP status and headers
     */
    public ApiResponse<CreditCardCredit> createWithResponse(CreditCardCreditCreateInput params, RequestOptions options) {
        return core.callWithResponse(OP_CREATE, "/v1/quickbooks-desktop/credit-card-credits", null, params, options, CreditCardCredit::fromJson);
    }

    /**
     * Create a credit card credit.
     *
     * <p>{@code POST /v1/quickbooks-desktop/credit-card-credits} (operation {@code qbd.creditCardCredits.create}).
     *
     * @param params the request body
     * @return the {@link CreditCardCredit} with HTTP status and headers
     */
    public ApiResponse<CreditCardCredit> createWithResponse(CreditCardCreditCreateInput params) {
        return createWithResponse(params, RequestOptions.NONE);
    }

    /**
     * Delete a credit card credit.
     *
     * <p>Permanently deletes a credit card credit. Deleting cannot be undone. Deleted transactions remain visible for 90 days through the deleted-transactions list. Send an `Idempotency-Key` to make retries safe.
     *
     * <p>A write: the SDK sends an {@code Idempotency-Key} (yours, or a UUID generated once per call) and reuses it on every retry.
     *
     * <p>Runs against the end user's QuickBooks company file (client default end user, {@code forEndUser}, or {@code RequestOptions.endUserId}).
     *
     * <p>{@code DELETE /v1/quickbooks-desktop/credit-card-credits/{id}} (operation {@code qbd.creditCardCredits.delete}).
     *
     * @param id QuickBooks ID of the credit card credit.
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link CreditCardCreditDeleted}
     */
    public CreditCardCreditDeleted delete(String id, RequestOptions options) {
        return core.call(OP_DELETE, "/v1/quickbooks-desktop/credit-card-credits/" + ClientCore.pathParam("id", id), null, null, options, CreditCardCreditDeleted::fromJson);
    }

    /**
     * Delete a credit card credit.
     *
     * <p>{@code DELETE /v1/quickbooks-desktop/credit-card-credits/{id}} (operation {@code qbd.creditCardCredits.delete}).
     *
     * @param id QuickBooks ID of the credit card credit.
     * @return the {@link CreditCardCreditDeleted}
     */
    public CreditCardCreditDeleted delete(String id) {
        return delete(id, RequestOptions.NONE);
    }

    /**
     * Delete a credit card credit.
     *
     * <p>Permanently deletes a credit card credit. Deleting cannot be undone. Deleted transactions remain visible for 90 days through the deleted-transactions list. Send an `Idempotency-Key` to make retries safe.
     *
     * <p>Like {@code delete(...)}, but also returns the HTTP status and headers ({@code Daapi-Request-Id}, {@code Daapi-Warnings}).
     *
     * <p>{@code DELETE /v1/quickbooks-desktop/credit-card-credits/{id}} (operation {@code qbd.creditCardCredits.delete}).
     *
     * @param id QuickBooks ID of the credit card credit.
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link CreditCardCreditDeleted} with HTTP status and headers
     */
    public ApiResponse<CreditCardCreditDeleted> deleteWithResponse(String id, RequestOptions options) {
        return core.callWithResponse(OP_DELETE, "/v1/quickbooks-desktop/credit-card-credits/" + ClientCore.pathParam("id", id), null, null, options, CreditCardCreditDeleted::fromJson);
    }

    /**
     * Delete a credit card credit.
     *
     * <p>{@code DELETE /v1/quickbooks-desktop/credit-card-credits/{id}} (operation {@code qbd.creditCardCredits.delete}).
     *
     * @param id QuickBooks ID of the credit card credit.
     * @return the {@link CreditCardCreditDeleted} with HTTP status and headers
     */
    public ApiResponse<CreditCardCreditDeleted> deleteWithResponse(String id) {
        return deleteWithResponse(id, RequestOptions.NONE);
    }

    /**
     * List credit card credits.
     *
     * <p>Returns the credit card credits that match your filters. Results are paged: pass `nextCursor` as `cursor` until `hasMore` is false. A cursor lives only inside the current QuickBooks session, so request the next page promptly; an expired cursor returns `410 CURSOR_EXPIRED`. See [Pagination](https://www.desktopaccountingapi.com/docs/guides/pagination/).
     *
     * <p>Returns a lazy {@link Pager}: iterate it for every item (each next page is requested when the loop needs it) or call {@code firstPage()}.
     *
     * <p>Runs against the end user's QuickBooks company file (client default end user, {@code forEndUser}, or {@code RequestOptions.endUserId}).
     *
     * <p>{@code GET /v1/quickbooks-desktop/credit-card-credits} (operation {@code qbd.creditCardCredits.list}).
     *
     * @param params the query parameters
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return a lazy pager over {@link CreditCardCredit} items
     */
    public Pager<CreditCardCredit> list(CreditCardCreditListParams params, RequestOptions options) {
        return core.paginate(OP_LIST, "/v1/quickbooks-desktop/credit-card-credits", params, options, CreditCardCredit::fromJson);
    }

    /**
     * List credit card credits.
     *
     * <p>{@code GET /v1/quickbooks-desktop/credit-card-credits} (operation {@code qbd.creditCardCredits.list}).
     *
     * @param params the query parameters
     * @return a lazy pager over {@link CreditCardCredit} items
     */
    public Pager<CreditCardCredit> list(CreditCardCreditListParams params) {
        return list(params, RequestOptions.NONE);
    }

    /**
     * List credit card credits.
     *
     * <p>{@code GET /v1/quickbooks-desktop/credit-card-credits} (operation {@code qbd.creditCardCredits.list}).
     *
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return a lazy pager over {@link CreditCardCredit} items
     */
    public Pager<CreditCardCredit> list(RequestOptions options) {
        return list(new CreditCardCreditListParams(), options);
    }

    /**
     * List credit card credits.
     *
     * <p>{@code GET /v1/quickbooks-desktop/credit-card-credits} (operation {@code qbd.creditCardCredits.list}).
     *
     * @return a lazy pager over {@link CreditCardCredit} items
     */
    public Pager<CreditCardCredit> list() {
        return list(new CreditCardCreditListParams(), RequestOptions.NONE);
    }

    /**
     * Retrieve a credit card credit.
     *
     * <p>Returns one credit card credit by its QuickBooks ID. An unknown ID returns `404 QBD_OBJECT_NOT_FOUND`.
     *
     * <p>Runs against the end user's QuickBooks company file (client default end user, {@code forEndUser}, or {@code RequestOptions.endUserId}).
     *
     * <p>{@code GET /v1/quickbooks-desktop/credit-card-credits/{id}} (operation {@code qbd.creditCardCredits.retrieve}).
     *
     * @param id QuickBooks ID of the credit card credit.
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link CreditCardCredit}
     */
    public CreditCardCredit retrieve(String id, RequestOptions options) {
        return core.call(OP_RETRIEVE, "/v1/quickbooks-desktop/credit-card-credits/" + ClientCore.pathParam("id", id), null, null, options, CreditCardCredit::fromJson);
    }

    /**
     * Retrieve a credit card credit.
     *
     * <p>{@code GET /v1/quickbooks-desktop/credit-card-credits/{id}} (operation {@code qbd.creditCardCredits.retrieve}).
     *
     * @param id QuickBooks ID of the credit card credit.
     * @return the {@link CreditCardCredit}
     */
    public CreditCardCredit retrieve(String id) {
        return retrieve(id, RequestOptions.NONE);
    }

    /**
     * Retrieve a credit card credit.
     *
     * <p>Returns one credit card credit by its QuickBooks ID. An unknown ID returns `404 QBD_OBJECT_NOT_FOUND`.
     *
     * <p>Like {@code retrieve(...)}, but also returns the HTTP status and headers ({@code Daapi-Request-Id}, {@code Daapi-Warnings}).
     *
     * <p>{@code GET /v1/quickbooks-desktop/credit-card-credits/{id}} (operation {@code qbd.creditCardCredits.retrieve}).
     *
     * @param id QuickBooks ID of the credit card credit.
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link CreditCardCredit} with HTTP status and headers
     */
    public ApiResponse<CreditCardCredit> retrieveWithResponse(String id, RequestOptions options) {
        return core.callWithResponse(OP_RETRIEVE, "/v1/quickbooks-desktop/credit-card-credits/" + ClientCore.pathParam("id", id), null, null, options, CreditCardCredit::fromJson);
    }

    /**
     * Retrieve a credit card credit.
     *
     * <p>{@code GET /v1/quickbooks-desktop/credit-card-credits/{id}} (operation {@code qbd.creditCardCredits.retrieve}).
     *
     * @param id QuickBooks ID of the credit card credit.
     * @return the {@link CreditCardCredit} with HTTP status and headers
     */
    public ApiResponse<CreditCardCredit> retrieveWithResponse(String id) {
        return retrieveWithResponse(id, RequestOptions.NONE);
    }

    /**
     * Update a credit card credit.
     *
     * <p>Changes the fields you send on an existing credit card credit and leaves omitted fields unchanged. Requires the current `revisionNumber`. A stale `revisionNumber` returns `409 QBD_REVISION_NUMBER_STALE`: retrieve the credit card credit, reapply your change and send the new revision. Sending a line array replaces all existing lines of that kind. Line arrays you omit stay unchanged: when you send only some of them, the API first reads the transaction (a separate read in the request log) and keeps the omitted lines by ID, because QuickBooks would otherwise delete them. See [Updates and line items](https://www.desktopaccountingapi.com/docs/quickbooks/updates-and-line-items/).
     *
     * <p>A write: the SDK sends an {@code Idempotency-Key} (yours, or a UUID generated once per call) and reuses it on every retry.
     *
     * <p>Runs against the end user's QuickBooks company file (client default end user, {@code forEndUser}, or {@code RequestOptions.endUserId}).
     *
     * <p>{@code POST /v1/quickbooks-desktop/credit-card-credits/{id}} (operation {@code qbd.creditCardCredits.update}).
     *
     * @param id QuickBooks ID of the credit card credit.
     * @param params the request body
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link CreditCardCredit}
     */
    public CreditCardCredit update(String id, CreditCardCreditUpdateInput params, RequestOptions options) {
        return core.call(OP_UPDATE, "/v1/quickbooks-desktop/credit-card-credits/" + ClientCore.pathParam("id", id), null, params, options, CreditCardCredit::fromJson);
    }

    /**
     * Update a credit card credit.
     *
     * <p>{@code POST /v1/quickbooks-desktop/credit-card-credits/{id}} (operation {@code qbd.creditCardCredits.update}).
     *
     * @param id QuickBooks ID of the credit card credit.
     * @param params the request body
     * @return the {@link CreditCardCredit}
     */
    public CreditCardCredit update(String id, CreditCardCreditUpdateInput params) {
        return update(id, params, RequestOptions.NONE);
    }

    /**
     * Update a credit card credit.
     *
     * <p>Changes the fields you send on an existing credit card credit and leaves omitted fields unchanged. Requires the current `revisionNumber`. A stale `revisionNumber` returns `409 QBD_REVISION_NUMBER_STALE`: retrieve the credit card credit, reapply your change and send the new revision. Sending a line array replaces all existing lines of that kind. Line arrays you omit stay unchanged: when you send only some of them, the API first reads the transaction (a separate read in the request log) and keeps the omitted lines by ID, because QuickBooks would otherwise delete them. See [Updates and line items](https://www.desktopaccountingapi.com/docs/quickbooks/updates-and-line-items/).
     *
     * <p>Like {@code update(...)}, but also returns the HTTP status and headers ({@code Daapi-Request-Id}, {@code Daapi-Warnings}).
     *
     * <p>{@code POST /v1/quickbooks-desktop/credit-card-credits/{id}} (operation {@code qbd.creditCardCredits.update}).
     *
     * @param id QuickBooks ID of the credit card credit.
     * @param params the request body
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link CreditCardCredit} with HTTP status and headers
     */
    public ApiResponse<CreditCardCredit> updateWithResponse(String id, CreditCardCreditUpdateInput params, RequestOptions options) {
        return core.callWithResponse(OP_UPDATE, "/v1/quickbooks-desktop/credit-card-credits/" + ClientCore.pathParam("id", id), null, params, options, CreditCardCredit::fromJson);
    }

    /**
     * Update a credit card credit.
     *
     * <p>{@code POST /v1/quickbooks-desktop/credit-card-credits/{id}} (operation {@code qbd.creditCardCredits.update}).
     *
     * @param id QuickBooks ID of the credit card credit.
     * @param params the request body
     * @return the {@link CreditCardCredit} with HTTP status and headers
     */
    public ApiResponse<CreditCardCredit> updateWithResponse(String id, CreditCardCreditUpdateInput params) {
        return updateWithResponse(id, params, RequestOptions.NONE);
    }

    /**
     * Void a credit card credit.
     *
     * <p>Voids a credit card credit: QuickBooks keeps the record but sets its amounts to zero. Use void instead of delete when the credit card credit must stay in the audit trail. Send an `Idempotency-Key` to make retries safe.
     *
     * <p>A write: the SDK sends an {@code Idempotency-Key} (yours, or a UUID generated once per call) and reuses it on every retry.
     *
     * <p>Runs against the end user's QuickBooks company file (client default end user, {@code forEndUser}, or {@code RequestOptions.endUserId}).
     *
     * <p>{@code POST /v1/quickbooks-desktop/credit-card-credits/{id}/void} (operation {@code qbd.creditCardCredits.void}).
     *
     * @param id QuickBooks ID of the credit card credit.
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link CreditCardCreditVoided}
     */
    public CreditCardCreditVoided voidTransaction(String id, RequestOptions options) {
        return core.call(OP_VOID, "/v1/quickbooks-desktop/credit-card-credits/" + ClientCore.pathParam("id", id) + "/void", null, null, options, CreditCardCreditVoided::fromJson);
    }

    /**
     * Void a credit card credit.
     *
     * <p>{@code POST /v1/quickbooks-desktop/credit-card-credits/{id}/void} (operation {@code qbd.creditCardCredits.void}).
     *
     * @param id QuickBooks ID of the credit card credit.
     * @return the {@link CreditCardCreditVoided}
     */
    public CreditCardCreditVoided voidTransaction(String id) {
        return voidTransaction(id, RequestOptions.NONE);
    }

    /**
     * Void a credit card credit.
     *
     * <p>Voids a credit card credit: QuickBooks keeps the record but sets its amounts to zero. Use void instead of delete when the credit card credit must stay in the audit trail. Send an `Idempotency-Key` to make retries safe.
     *
     * <p>Like {@code voidTransaction(...)}, but also returns the HTTP status and headers ({@code Daapi-Request-Id}, {@code Daapi-Warnings}).
     *
     * <p>{@code POST /v1/quickbooks-desktop/credit-card-credits/{id}/void} (operation {@code qbd.creditCardCredits.void}).
     *
     * @param id QuickBooks ID of the credit card credit.
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link CreditCardCreditVoided} with HTTP status and headers
     */
    public ApiResponse<CreditCardCreditVoided> voidTransactionWithResponse(String id, RequestOptions options) {
        return core.callWithResponse(OP_VOID, "/v1/quickbooks-desktop/credit-card-credits/" + ClientCore.pathParam("id", id) + "/void", null, null, options, CreditCardCreditVoided::fromJson);
    }

    /**
     * Void a credit card credit.
     *
     * <p>{@code POST /v1/quickbooks-desktop/credit-card-credits/{id}/void} (operation {@code qbd.creditCardCredits.void}).
     *
     * @param id QuickBooks ID of the credit card credit.
     * @return the {@link CreditCardCreditVoided} with HTTP status and headers
     */
    public ApiResponse<CreditCardCreditVoided> voidTransactionWithResponse(String id) {
        return voidTransactionWithResponse(id, RequestOptions.NONE);
    }

    /**
     * Async-mode ({@code Prefer: respond-async}) variants of the methods of {@link QbdCreditCardCreditsService}.
     */
    public final class Enqueue {
        private Enqueue() {}

        /**
         * Create a credit card credit.
         *
         * <p>Creates a credit card credit in QuickBooks Desktop and returns it. Send an `Idempotency-Key` header so a retry after a network error never creates a second credit card credit (the SDKs do this for you). See [Idempotency and safe retries](https://www.desktopaccountingapi.com/docs/guides/idempotency/).
         *
         * <p>Async mode: sends {@code Prefer: respond-async} and returns as soon as the API queued the request ({@code 202}). Use the handle's {@code await()} or {@code result()} to get the outcome.
         *
         * <p>{@code POST /v1/quickbooks-desktop/credit-card-credits} (operation {@code qbd.creditCardCredits.create}).
         *
         * @param params the request body
         * @param options per-call options (end user, idempotency key, timeouts, retries)
         * @return a handle on the queued request
         */
        public RequestHandle<CreditCardCredit> create(CreditCardCreditCreateInput params, RequestOptions options) {
            return core.enqueue(OP_CREATE, "/v1/quickbooks-desktop/credit-card-credits", null, params, options, CreditCardCredit::fromJson);
        }

        /**
         * Create a credit card credit.
         *
         * <p>{@code POST /v1/quickbooks-desktop/credit-card-credits} (operation {@code qbd.creditCardCredits.create}).
         *
         * @param params the request body
         * @return a handle on the queued request
         */
        public RequestHandle<CreditCardCredit> create(CreditCardCreditCreateInput params) {
            return create(params, RequestOptions.NONE);
        }

        /**
         * Delete a credit card credit.
         *
         * <p>Permanently deletes a credit card credit. Deleting cannot be undone. Deleted transactions remain visible for 90 days through the deleted-transactions list. Send an `Idempotency-Key` to make retries safe.
         *
         * <p>Async mode: sends {@code Prefer: respond-async} and returns as soon as the API queued the request ({@code 202}). Use the handle's {@code await()} or {@code result()} to get the outcome.
         *
         * <p>{@code DELETE /v1/quickbooks-desktop/credit-card-credits/{id}} (operation {@code qbd.creditCardCredits.delete}).
         *
         * @param id QuickBooks ID of the credit card credit.
         * @param options per-call options (end user, idempotency key, timeouts, retries)
         * @return a handle on the queued request
         */
        public RequestHandle<CreditCardCreditDeleted> delete(String id, RequestOptions options) {
            return core.enqueue(OP_DELETE, "/v1/quickbooks-desktop/credit-card-credits/" + ClientCore.pathParam("id", id), null, null, options, CreditCardCreditDeleted::fromJson);
        }

        /**
         * Delete a credit card credit.
         *
         * <p>{@code DELETE /v1/quickbooks-desktop/credit-card-credits/{id}} (operation {@code qbd.creditCardCredits.delete}).
         *
         * @param id QuickBooks ID of the credit card credit.
         * @return a handle on the queued request
         */
        public RequestHandle<CreditCardCreditDeleted> delete(String id) {
            return delete(id, RequestOptions.NONE);
        }

        /**
         * List credit card credits.
         *
         * <p>Returns the credit card credits that match your filters. Results are paged: pass `nextCursor` as `cursor` until `hasMore` is false. A cursor lives only inside the current QuickBooks session, so request the next page promptly; an expired cursor returns `410 CURSOR_EXPIRED`. See [Pagination](https://www.desktopaccountingapi.com/docs/guides/pagination/).
         *
         * <p>Async mode: sends {@code Prefer: respond-async} and returns as soon as the API queued the request ({@code 202}). Use the handle's {@code await()} or {@code result()} to get the outcome.
         *
         * <p>{@code GET /v1/quickbooks-desktop/credit-card-credits} (operation {@code qbd.creditCardCredits.list}).
         *
         * @param params the query parameters
         * @param options per-call options (end user, idempotency key, timeouts, retries)
         * @return a handle on the queued request
         */
        public RequestHandle<Page<CreditCardCredit>> list(CreditCardCreditListParams params, RequestOptions options) {
            return core.enqueue(OP_LIST, "/v1/quickbooks-desktop/credit-card-credits", params, null, options, Page.parser(CreditCardCredit::fromJson));
        }

        /**
         * List credit card credits.
         *
         * <p>{@code GET /v1/quickbooks-desktop/credit-card-credits} (operation {@code qbd.creditCardCredits.list}).
         *
         * @param params the query parameters
         * @return a handle on the queued request
         */
        public RequestHandle<Page<CreditCardCredit>> list(CreditCardCreditListParams params) {
            return list(params, RequestOptions.NONE);
        }

        /**
         * List credit card credits.
         *
         * <p>{@code GET /v1/quickbooks-desktop/credit-card-credits} (operation {@code qbd.creditCardCredits.list}).
         *
         * @param options per-call options (end user, idempotency key, timeouts, retries)
         * @return a handle on the queued request
         */
        public RequestHandle<Page<CreditCardCredit>> list(RequestOptions options) {
            return list(new CreditCardCreditListParams(), options);
        }

        /**
         * List credit card credits.
         *
         * <p>{@code GET /v1/quickbooks-desktop/credit-card-credits} (operation {@code qbd.creditCardCredits.list}).
         *
         * @return a handle on the queued request
         */
        public RequestHandle<Page<CreditCardCredit>> list() {
            return list(new CreditCardCreditListParams(), RequestOptions.NONE);
        }

        /**
         * Retrieve a credit card credit.
         *
         * <p>Returns one credit card credit by its QuickBooks ID. An unknown ID returns `404 QBD_OBJECT_NOT_FOUND`.
         *
         * <p>Async mode: sends {@code Prefer: respond-async} and returns as soon as the API queued the request ({@code 202}). Use the handle's {@code await()} or {@code result()} to get the outcome.
         *
         * <p>{@code GET /v1/quickbooks-desktop/credit-card-credits/{id}} (operation {@code qbd.creditCardCredits.retrieve}).
         *
         * @param id QuickBooks ID of the credit card credit.
         * @param options per-call options (end user, idempotency key, timeouts, retries)
         * @return a handle on the queued request
         */
        public RequestHandle<CreditCardCredit> retrieve(String id, RequestOptions options) {
            return core.enqueue(OP_RETRIEVE, "/v1/quickbooks-desktop/credit-card-credits/" + ClientCore.pathParam("id", id), null, null, options, CreditCardCredit::fromJson);
        }

        /**
         * Retrieve a credit card credit.
         *
         * <p>{@code GET /v1/quickbooks-desktop/credit-card-credits/{id}} (operation {@code qbd.creditCardCredits.retrieve}).
         *
         * @param id QuickBooks ID of the credit card credit.
         * @return a handle on the queued request
         */
        public RequestHandle<CreditCardCredit> retrieve(String id) {
            return retrieve(id, RequestOptions.NONE);
        }

        /**
         * Update a credit card credit.
         *
         * <p>Changes the fields you send on an existing credit card credit and leaves omitted fields unchanged. Requires the current `revisionNumber`. A stale `revisionNumber` returns `409 QBD_REVISION_NUMBER_STALE`: retrieve the credit card credit, reapply your change and send the new revision. Sending a line array replaces all existing lines of that kind. Line arrays you omit stay unchanged: when you send only some of them, the API first reads the transaction (a separate read in the request log) and keeps the omitted lines by ID, because QuickBooks would otherwise delete them. See [Updates and line items](https://www.desktopaccountingapi.com/docs/quickbooks/updates-and-line-items/).
         *
         * <p>Async mode: sends {@code Prefer: respond-async} and returns as soon as the API queued the request ({@code 202}). Use the handle's {@code await()} or {@code result()} to get the outcome.
         *
         * <p>{@code POST /v1/quickbooks-desktop/credit-card-credits/{id}} (operation {@code qbd.creditCardCredits.update}).
         *
         * @param id QuickBooks ID of the credit card credit.
         * @param params the request body
         * @param options per-call options (end user, idempotency key, timeouts, retries)
         * @return a handle on the queued request
         */
        public RequestHandle<CreditCardCredit> update(String id, CreditCardCreditUpdateInput params, RequestOptions options) {
            return core.enqueue(OP_UPDATE, "/v1/quickbooks-desktop/credit-card-credits/" + ClientCore.pathParam("id", id), null, params, options, CreditCardCredit::fromJson);
        }

        /**
         * Update a credit card credit.
         *
         * <p>{@code POST /v1/quickbooks-desktop/credit-card-credits/{id}} (operation {@code qbd.creditCardCredits.update}).
         *
         * @param id QuickBooks ID of the credit card credit.
         * @param params the request body
         * @return a handle on the queued request
         */
        public RequestHandle<CreditCardCredit> update(String id, CreditCardCreditUpdateInput params) {
            return update(id, params, RequestOptions.NONE);
        }

        /**
         * Void a credit card credit.
         *
         * <p>Voids a credit card credit: QuickBooks keeps the record but sets its amounts to zero. Use void instead of delete when the credit card credit must stay in the audit trail. Send an `Idempotency-Key` to make retries safe.
         *
         * <p>Async mode: sends {@code Prefer: respond-async} and returns as soon as the API queued the request ({@code 202}). Use the handle's {@code await()} or {@code result()} to get the outcome.
         *
         * <p>{@code POST /v1/quickbooks-desktop/credit-card-credits/{id}/void} (operation {@code qbd.creditCardCredits.void}).
         *
         * @param id QuickBooks ID of the credit card credit.
         * @param options per-call options (end user, idempotency key, timeouts, retries)
         * @return a handle on the queued request
         */
        public RequestHandle<CreditCardCreditVoided> voidTransaction(String id, RequestOptions options) {
            return core.enqueue(OP_VOID, "/v1/quickbooks-desktop/credit-card-credits/" + ClientCore.pathParam("id", id) + "/void", null, null, options, CreditCardCreditVoided::fromJson);
        }

        /**
         * Void a credit card credit.
         *
         * <p>{@code POST /v1/quickbooks-desktop/credit-card-credits/{id}/void} (operation {@code qbd.creditCardCredits.void}).
         *
         * @param id QuickBooks ID of the credit card credit.
         * @return a handle on the queued request
         */
        public RequestHandle<CreditCardCreditVoided> voidTransaction(String id) {
            return voidTransaction(id, RequestOptions.NONE);
        }
    }
}
