// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:79b06eb2008381661d24d3bd5e23643483ec1bf9b70d5f4cdff2a2a71e22fe94
package com.desktopaccountingapi.quickbooksdesktop.services;

import com.desktopaccountingapi.quickbooksdesktop.core.ApiResponse;
import com.desktopaccountingapi.quickbooksdesktop.core.ClientCore;
import com.desktopaccountingapi.quickbooksdesktop.core.OperationSpec;
import com.desktopaccountingapi.quickbooksdesktop.core.Page;
import com.desktopaccountingapi.quickbooksdesktop.core.Pager;
import com.desktopaccountingapi.quickbooksdesktop.core.RequestHandle;
import com.desktopaccountingapi.quickbooksdesktop.core.RequestOptions;
import com.desktopaccountingapi.quickbooksdesktop.models.Estimate;
import com.desktopaccountingapi.quickbooksdesktop.models.EstimateCreateInput;
import com.desktopaccountingapi.quickbooksdesktop.models.EstimateDeleted;
import com.desktopaccountingapi.quickbooksdesktop.models.EstimateListParams;
import com.desktopaccountingapi.quickbooksdesktop.models.EstimateUpdateInput;

/**
 * Operations under {@code client.qbd().estimates()} (Estimates).
 */
public final class QbdEstimatesService {
    private static final OperationSpec OP_CREATE = OperationSpec.of("qbd.estimates.create", "POST", OperationSpec.WRITE | OperationSpec.END_USER | OperationSpec.SERVER_TIMEOUT | OperationSpec.ASYNC | OperationSpec.QUEUE_TTL);
    private static final OperationSpec OP_DELETE = OperationSpec.of("qbd.estimates.delete", "DELETE", OperationSpec.WRITE | OperationSpec.END_USER | OperationSpec.SERVER_TIMEOUT | OperationSpec.ASYNC | OperationSpec.QUEUE_TTL);
    private static final OperationSpec OP_LIST = OperationSpec.of("qbd.estimates.list", "GET", OperationSpec.END_USER | OperationSpec.SERVER_TIMEOUT | OperationSpec.ASYNC | OperationSpec.QUEUE_TTL);
    private static final OperationSpec OP_RETRIEVE = OperationSpec.of("qbd.estimates.retrieve", "GET", OperationSpec.END_USER | OperationSpec.SERVER_TIMEOUT | OperationSpec.ASYNC | OperationSpec.QUEUE_TTL);
    private static final OperationSpec OP_UPDATE = OperationSpec.of("qbd.estimates.update", "POST", OperationSpec.WRITE | OperationSpec.END_USER | OperationSpec.SERVER_TIMEOUT | OperationSpec.ASYNC | OperationSpec.QUEUE_TTL);

    private final ClientCore core;
    private final Enqueue enqueue;

    /**
     * Creates the service. Use the client's accessor instead of calling this.
     *
     * @param core the client engine
     */
    public QbdEstimatesService(ClientCore core) {
        this.core = core;
        this.enqueue = new Enqueue();
    }

    /**
     * Async-mode variants of this resource's methods. Each returns a {@link RequestHandle} as soon as the API queued the request.
     *
     * @return the async-mode methods
     */
    public Enqueue enqueue() {
        return enqueue;
    }

    /**
     * Create an estimate.
     *
     * <p>Creates an estimate in QuickBooks Desktop and returns it. Send an `Idempotency-Key` header so a retry after a network error never creates a second estimate (the SDKs do this for you). See [Idempotency and safe retries](https://www.desktopaccountingapi.com/docs/guides/idempotency/).
     *
     * <p>A write: the SDK sends an {@code Idempotency-Key} (yours, or a UUID generated once per call) and reuses it on every retry.
     *
     * <p>Runs against the end user's QuickBooks company file (client default end user, {@code forEndUser}, or {@code RequestOptions.endUserId}).
     *
     * <p>{@code POST /v1/quickbooks-desktop/estimates} (operation {@code qbd.estimates.create}).
     *
     * @param params the request body
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link Estimate}
     */
    public Estimate create(EstimateCreateInput params, RequestOptions options) {
        return core.call(OP_CREATE, "/v1/quickbooks-desktop/estimates", null, params, options, Estimate::fromJson);
    }

    /**
     * Create an estimate.
     *
     * <p>{@code POST /v1/quickbooks-desktop/estimates} (operation {@code qbd.estimates.create}).
     *
     * @param params the request body
     * @return the {@link Estimate}
     */
    public Estimate create(EstimateCreateInput params) {
        return create(params, RequestOptions.NONE);
    }

    /**
     * Create an estimate.
     *
     * <p>Creates an estimate in QuickBooks Desktop and returns it. Send an `Idempotency-Key` header so a retry after a network error never creates a second estimate (the SDKs do this for you). See [Idempotency and safe retries](https://www.desktopaccountingapi.com/docs/guides/idempotency/).
     *
     * <p>Like {@code create(...)}, but also returns the HTTP status and headers ({@code Daapi-Request-Id}, {@code Daapi-Warnings}).
     *
     * <p>{@code POST /v1/quickbooks-desktop/estimates} (operation {@code qbd.estimates.create}).
     *
     * @param params the request body
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link Estimate} with HTTP status and headers
     */
    public ApiResponse<Estimate> createWithResponse(EstimateCreateInput params, RequestOptions options) {
        return core.callWithResponse(OP_CREATE, "/v1/quickbooks-desktop/estimates", null, params, options, Estimate::fromJson);
    }

    /**
     * Create an estimate.
     *
     * <p>{@code POST /v1/quickbooks-desktop/estimates} (operation {@code qbd.estimates.create}).
     *
     * @param params the request body
     * @return the {@link Estimate} with HTTP status and headers
     */
    public ApiResponse<Estimate> createWithResponse(EstimateCreateInput params) {
        return createWithResponse(params, RequestOptions.NONE);
    }

    /**
     * Delete an estimate.
     *
     * <p>Permanently deletes an estimate. Deleting cannot be undone. Deleted transactions remain visible for 90 days through the deleted-transactions list. Send an `Idempotency-Key` to make retries safe.
     *
     * <p>A write: the SDK sends an {@code Idempotency-Key} (yours, or a UUID generated once per call) and reuses it on every retry.
     *
     * <p>Runs against the end user's QuickBooks company file (client default end user, {@code forEndUser}, or {@code RequestOptions.endUserId}).
     *
     * <p>{@code DELETE /v1/quickbooks-desktop/estimates/{id}} (operation {@code qbd.estimates.delete}).
     *
     * @param id QuickBooks ID of the estimate.
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link EstimateDeleted}
     */
    public EstimateDeleted delete(String id, RequestOptions options) {
        return core.call(OP_DELETE, "/v1/quickbooks-desktop/estimates/" + ClientCore.pathParam("id", id), null, null, options, EstimateDeleted::fromJson);
    }

    /**
     * Delete an estimate.
     *
     * <p>{@code DELETE /v1/quickbooks-desktop/estimates/{id}} (operation {@code qbd.estimates.delete}).
     *
     * @param id QuickBooks ID of the estimate.
     * @return the {@link EstimateDeleted}
     */
    public EstimateDeleted delete(String id) {
        return delete(id, RequestOptions.NONE);
    }

    /**
     * Delete an estimate.
     *
     * <p>Permanently deletes an estimate. Deleting cannot be undone. Deleted transactions remain visible for 90 days through the deleted-transactions list. Send an `Idempotency-Key` to make retries safe.
     *
     * <p>Like {@code delete(...)}, but also returns the HTTP status and headers ({@code Daapi-Request-Id}, {@code Daapi-Warnings}).
     *
     * <p>{@code DELETE /v1/quickbooks-desktop/estimates/{id}} (operation {@code qbd.estimates.delete}).
     *
     * @param id QuickBooks ID of the estimate.
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link EstimateDeleted} with HTTP status and headers
     */
    public ApiResponse<EstimateDeleted> deleteWithResponse(String id, RequestOptions options) {
        return core.callWithResponse(OP_DELETE, "/v1/quickbooks-desktop/estimates/" + ClientCore.pathParam("id", id), null, null, options, EstimateDeleted::fromJson);
    }

    /**
     * Delete an estimate.
     *
     * <p>{@code DELETE /v1/quickbooks-desktop/estimates/{id}} (operation {@code qbd.estimates.delete}).
     *
     * @param id QuickBooks ID of the estimate.
     * @return the {@link EstimateDeleted} with HTTP status and headers
     */
    public ApiResponse<EstimateDeleted> deleteWithResponse(String id) {
        return deleteWithResponse(id, RequestOptions.NONE);
    }

    /**
     * List estimates.
     *
     * <p>Returns the estimates that match your filters. Results are paged: pass `nextCursor` as `cursor` until `hasMore` is false. A cursor lives only inside the current QuickBooks session, so request the next page promptly; an expired cursor returns `410 CURSOR_EXPIRED`. See [Pagination](https://www.desktopaccountingapi.com/docs/guides/pagination/).
     *
     * <p>Returns a lazy {@link Pager}: iterate it for every item (each next page is requested when the loop needs it) or call {@code firstPage()}.
     *
     * <p>Runs against the end user's QuickBooks company file (client default end user, {@code forEndUser}, or {@code RequestOptions.endUserId}).
     *
     * <p>{@code GET /v1/quickbooks-desktop/estimates} (operation {@code qbd.estimates.list}).
     *
     * @param params the query parameters
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return a lazy pager over {@link Estimate} items
     */
    public Pager<Estimate> list(EstimateListParams params, RequestOptions options) {
        return core.paginate(OP_LIST, "/v1/quickbooks-desktop/estimates", params, options, Estimate::fromJson);
    }

    /**
     * List estimates.
     *
     * <p>{@code GET /v1/quickbooks-desktop/estimates} (operation {@code qbd.estimates.list}).
     *
     * @param params the query parameters
     * @return a lazy pager over {@link Estimate} items
     */
    public Pager<Estimate> list(EstimateListParams params) {
        return list(params, RequestOptions.NONE);
    }

    /**
     * List estimates.
     *
     * <p>{@code GET /v1/quickbooks-desktop/estimates} (operation {@code qbd.estimates.list}).
     *
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return a lazy pager over {@link Estimate} items
     */
    public Pager<Estimate> list(RequestOptions options) {
        return list(new EstimateListParams(), options);
    }

    /**
     * List estimates.
     *
     * <p>{@code GET /v1/quickbooks-desktop/estimates} (operation {@code qbd.estimates.list}).
     *
     * @return a lazy pager over {@link Estimate} items
     */
    public Pager<Estimate> list() {
        return list(new EstimateListParams(), RequestOptions.NONE);
    }

    /**
     * Retrieve an estimate.
     *
     * <p>Returns one estimate by its QuickBooks ID. An unknown ID returns `404 QBD_OBJECT_NOT_FOUND`.
     *
     * <p>Runs against the end user's QuickBooks company file (client default end user, {@code forEndUser}, or {@code RequestOptions.endUserId}).
     *
     * <p>{@code GET /v1/quickbooks-desktop/estimates/{id}} (operation {@code qbd.estimates.retrieve}).
     *
     * @param id QuickBooks ID of the estimate.
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link Estimate}
     */
    public Estimate retrieve(String id, RequestOptions options) {
        return core.call(OP_RETRIEVE, "/v1/quickbooks-desktop/estimates/" + ClientCore.pathParam("id", id), null, null, options, Estimate::fromJson);
    }

    /**
     * Retrieve an estimate.
     *
     * <p>{@code GET /v1/quickbooks-desktop/estimates/{id}} (operation {@code qbd.estimates.retrieve}).
     *
     * @param id QuickBooks ID of the estimate.
     * @return the {@link Estimate}
     */
    public Estimate retrieve(String id) {
        return retrieve(id, RequestOptions.NONE);
    }

    /**
     * Retrieve an estimate.
     *
     * <p>Returns one estimate by its QuickBooks ID. An unknown ID returns `404 QBD_OBJECT_NOT_FOUND`.
     *
     * <p>Like {@code retrieve(...)}, but also returns the HTTP status and headers ({@code Daapi-Request-Id}, {@code Daapi-Warnings}).
     *
     * <p>{@code GET /v1/quickbooks-desktop/estimates/{id}} (operation {@code qbd.estimates.retrieve}).
     *
     * @param id QuickBooks ID of the estimate.
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link Estimate} with HTTP status and headers
     */
    public ApiResponse<Estimate> retrieveWithResponse(String id, RequestOptions options) {
        return core.callWithResponse(OP_RETRIEVE, "/v1/quickbooks-desktop/estimates/" + ClientCore.pathParam("id", id), null, null, options, Estimate::fromJson);
    }

    /**
     * Retrieve an estimate.
     *
     * <p>{@code GET /v1/quickbooks-desktop/estimates/{id}} (operation {@code qbd.estimates.retrieve}).
     *
     * @param id QuickBooks ID of the estimate.
     * @return the {@link Estimate} with HTTP status and headers
     */
    public ApiResponse<Estimate> retrieveWithResponse(String id) {
        return retrieveWithResponse(id, RequestOptions.NONE);
    }

    /**
     * Update an estimate.
     *
     * <p>Changes the fields you send on an existing estimate and leaves omitted fields unchanged. Requires the current `revisionNumber`. A stale `revisionNumber` returns `409 QBD_REVISION_NUMBER_STALE`: retrieve the estimate, reapply your change and send the new revision. Sending a line array replaces all existing lines of that kind. Line arrays you omit stay unchanged: when you send only some of them, the API first reads the transaction (a separate read in the request log) and keeps the omitted lines by ID, because QuickBooks would otherwise delete them. See [Updates and line items](https://www.desktopaccountingapi.com/docs/quickbooks/updates-and-line-items/).
     *
     * <p>A write: the SDK sends an {@code Idempotency-Key} (yours, or a UUID generated once per call) and reuses it on every retry.
     *
     * <p>Runs against the end user's QuickBooks company file (client default end user, {@code forEndUser}, or {@code RequestOptions.endUserId}).
     *
     * <p>{@code POST /v1/quickbooks-desktop/estimates/{id}} (operation {@code qbd.estimates.update}).
     *
     * @param id QuickBooks ID of the estimate.
     * @param params the request body
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link Estimate}
     */
    public Estimate update(String id, EstimateUpdateInput params, RequestOptions options) {
        return core.call(OP_UPDATE, "/v1/quickbooks-desktop/estimates/" + ClientCore.pathParam("id", id), null, params, options, Estimate::fromJson);
    }

    /**
     * Update an estimate.
     *
     * <p>{@code POST /v1/quickbooks-desktop/estimates/{id}} (operation {@code qbd.estimates.update}).
     *
     * @param id QuickBooks ID of the estimate.
     * @param params the request body
     * @return the {@link Estimate}
     */
    public Estimate update(String id, EstimateUpdateInput params) {
        return update(id, params, RequestOptions.NONE);
    }

    /**
     * Update an estimate.
     *
     * <p>Changes the fields you send on an existing estimate and leaves omitted fields unchanged. Requires the current `revisionNumber`. A stale `revisionNumber` returns `409 QBD_REVISION_NUMBER_STALE`: retrieve the estimate, reapply your change and send the new revision. Sending a line array replaces all existing lines of that kind. Line arrays you omit stay unchanged: when you send only some of them, the API first reads the transaction (a separate read in the request log) and keeps the omitted lines by ID, because QuickBooks would otherwise delete them. See [Updates and line items](https://www.desktopaccountingapi.com/docs/quickbooks/updates-and-line-items/).
     *
     * <p>Like {@code update(...)}, but also returns the HTTP status and headers ({@code Daapi-Request-Id}, {@code Daapi-Warnings}).
     *
     * <p>{@code POST /v1/quickbooks-desktop/estimates/{id}} (operation {@code qbd.estimates.update}).
     *
     * @param id QuickBooks ID of the estimate.
     * @param params the request body
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link Estimate} with HTTP status and headers
     */
    public ApiResponse<Estimate> updateWithResponse(String id, EstimateUpdateInput params, RequestOptions options) {
        return core.callWithResponse(OP_UPDATE, "/v1/quickbooks-desktop/estimates/" + ClientCore.pathParam("id", id), null, params, options, Estimate::fromJson);
    }

    /**
     * Update an estimate.
     *
     * <p>{@code POST /v1/quickbooks-desktop/estimates/{id}} (operation {@code qbd.estimates.update}).
     *
     * @param id QuickBooks ID of the estimate.
     * @param params the request body
     * @return the {@link Estimate} with HTTP status and headers
     */
    public ApiResponse<Estimate> updateWithResponse(String id, EstimateUpdateInput params) {
        return updateWithResponse(id, params, RequestOptions.NONE);
    }

    /**
     * Async-mode ({@code Prefer: respond-async}) variants of the methods of {@link QbdEstimatesService}.
     */
    public final class Enqueue {
        private Enqueue() {}

        /**
         * Create an estimate.
         *
         * <p>Creates an estimate in QuickBooks Desktop and returns it. Send an `Idempotency-Key` header so a retry after a network error never creates a second estimate (the SDKs do this for you). See [Idempotency and safe retries](https://www.desktopaccountingapi.com/docs/guides/idempotency/).
         *
         * <p>Async mode: sends {@code Prefer: respond-async} and returns as soon as the API queued the request ({@code 202}). Use the handle's {@code await()} or {@code result()} to get the outcome.
         *
         * <p>{@code POST /v1/quickbooks-desktop/estimates} (operation {@code qbd.estimates.create}).
         *
         * @param params the request body
         * @param options per-call options (end user, idempotency key, timeouts, retries)
         * @return a handle on the queued request
         */
        public RequestHandle<Estimate> create(EstimateCreateInput params, RequestOptions options) {
            return core.enqueue(OP_CREATE, "/v1/quickbooks-desktop/estimates", null, params, options, Estimate::fromJson);
        }

        /**
         * Create an estimate.
         *
         * <p>{@code POST /v1/quickbooks-desktop/estimates} (operation {@code qbd.estimates.create}).
         *
         * @param params the request body
         * @return a handle on the queued request
         */
        public RequestHandle<Estimate> create(EstimateCreateInput params) {
            return create(params, RequestOptions.NONE);
        }

        /**
         * Delete an estimate.
         *
         * <p>Permanently deletes an estimate. Deleting cannot be undone. Deleted transactions remain visible for 90 days through the deleted-transactions list. Send an `Idempotency-Key` to make retries safe.
         *
         * <p>Async mode: sends {@code Prefer: respond-async} and returns as soon as the API queued the request ({@code 202}). Use the handle's {@code await()} or {@code result()} to get the outcome.
         *
         * <p>{@code DELETE /v1/quickbooks-desktop/estimates/{id}} (operation {@code qbd.estimates.delete}).
         *
         * @param id QuickBooks ID of the estimate.
         * @param options per-call options (end user, idempotency key, timeouts, retries)
         * @return a handle on the queued request
         */
        public RequestHandle<EstimateDeleted> delete(String id, RequestOptions options) {
            return core.enqueue(OP_DELETE, "/v1/quickbooks-desktop/estimates/" + ClientCore.pathParam("id", id), null, null, options, EstimateDeleted::fromJson);
        }

        /**
         * Delete an estimate.
         *
         * <p>{@code DELETE /v1/quickbooks-desktop/estimates/{id}} (operation {@code qbd.estimates.delete}).
         *
         * @param id QuickBooks ID of the estimate.
         * @return a handle on the queued request
         */
        public RequestHandle<EstimateDeleted> delete(String id) {
            return delete(id, RequestOptions.NONE);
        }

        /**
         * List estimates.
         *
         * <p>Returns the estimates that match your filters. Results are paged: pass `nextCursor` as `cursor` until `hasMore` is false. A cursor lives only inside the current QuickBooks session, so request the next page promptly; an expired cursor returns `410 CURSOR_EXPIRED`. See [Pagination](https://www.desktopaccountingapi.com/docs/guides/pagination/).
         *
         * <p>Async mode: sends {@code Prefer: respond-async} and returns as soon as the API queued the request ({@code 202}). Use the handle's {@code await()} or {@code result()} to get the outcome.
         *
         * <p>{@code GET /v1/quickbooks-desktop/estimates} (operation {@code qbd.estimates.list}).
         *
         * @param params the query parameters
         * @param options per-call options (end user, idempotency key, timeouts, retries)
         * @return a handle on the queued request
         */
        public RequestHandle<Page<Estimate>> list(EstimateListParams params, RequestOptions options) {
            return core.enqueue(OP_LIST, "/v1/quickbooks-desktop/estimates", params, null, options, Page.parser(Estimate::fromJson));
        }

        /**
         * List estimates.
         *
         * <p>{@code GET /v1/quickbooks-desktop/estimates} (operation {@code qbd.estimates.list}).
         *
         * @param params the query parameters
         * @return a handle on the queued request
         */
        public RequestHandle<Page<Estimate>> list(EstimateListParams params) {
            return list(params, RequestOptions.NONE);
        }

        /**
         * List estimates.
         *
         * <p>{@code GET /v1/quickbooks-desktop/estimates} (operation {@code qbd.estimates.list}).
         *
         * @param options per-call options (end user, idempotency key, timeouts, retries)
         * @return a handle on the queued request
         */
        public RequestHandle<Page<Estimate>> list(RequestOptions options) {
            return list(new EstimateListParams(), options);
        }

        /**
         * List estimates.
         *
         * <p>{@code GET /v1/quickbooks-desktop/estimates} (operation {@code qbd.estimates.list}).
         *
         * @return a handle on the queued request
         */
        public RequestHandle<Page<Estimate>> list() {
            return list(new EstimateListParams(), RequestOptions.NONE);
        }

        /**
         * Retrieve an estimate.
         *
         * <p>Returns one estimate by its QuickBooks ID. An unknown ID returns `404 QBD_OBJECT_NOT_FOUND`.
         *
         * <p>Async mode: sends {@code Prefer: respond-async} and returns as soon as the API queued the request ({@code 202}). Use the handle's {@code await()} or {@code result()} to get the outcome.
         *
         * <p>{@code GET /v1/quickbooks-desktop/estimates/{id}} (operation {@code qbd.estimates.retrieve}).
         *
         * @param id QuickBooks ID of the estimate.
         * @param options per-call options (end user, idempotency key, timeouts, retries)
         * @return a handle on the queued request
         */
        public RequestHandle<Estimate> retrieve(String id, RequestOptions options) {
            return core.enqueue(OP_RETRIEVE, "/v1/quickbooks-desktop/estimates/" + ClientCore.pathParam("id", id), null, null, options, Estimate::fromJson);
        }

        /**
         * Retrieve an estimate.
         *
         * <p>{@code GET /v1/quickbooks-desktop/estimates/{id}} (operation {@code qbd.estimates.retrieve}).
         *
         * @param id QuickBooks ID of the estimate.
         * @return a handle on the queued request
         */
        public RequestHandle<Estimate> retrieve(String id) {
            return retrieve(id, RequestOptions.NONE);
        }

        /**
         * Update an estimate.
         *
         * <p>Changes the fields you send on an existing estimate and leaves omitted fields unchanged. Requires the current `revisionNumber`. A stale `revisionNumber` returns `409 QBD_REVISION_NUMBER_STALE`: retrieve the estimate, reapply your change and send the new revision. Sending a line array replaces all existing lines of that kind. Line arrays you omit stay unchanged: when you send only some of them, the API first reads the transaction (a separate read in the request log) and keeps the omitted lines by ID, because QuickBooks would otherwise delete them. See [Updates and line items](https://www.desktopaccountingapi.com/docs/quickbooks/updates-and-line-items/).
         *
         * <p>Async mode: sends {@code Prefer: respond-async} and returns as soon as the API queued the request ({@code 202}). Use the handle's {@code await()} or {@code result()} to get the outcome.
         *
         * <p>{@code POST /v1/quickbooks-desktop/estimates/{id}} (operation {@code qbd.estimates.update}).
         *
         * @param id QuickBooks ID of the estimate.
         * @param params the request body
         * @param options per-call options (end user, idempotency key, timeouts, retries)
         * @return a handle on the queued request
         */
        public RequestHandle<Estimate> update(String id, EstimateUpdateInput params, RequestOptions options) {
            return core.enqueue(OP_UPDATE, "/v1/quickbooks-desktop/estimates/" + ClientCore.pathParam("id", id), null, params, options, Estimate::fromJson);
        }

        /**
         * Update an estimate.
         *
         * <p>{@code POST /v1/quickbooks-desktop/estimates/{id}} (operation {@code qbd.estimates.update}).
         *
         * @param id QuickBooks ID of the estimate.
         * @param params the request body
         * @return a handle on the queued request
         */
        public RequestHandle<Estimate> update(String id, EstimateUpdateInput params) {
            return update(id, params, RequestOptions.NONE);
        }
    }
}
