// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:09aa9517f466027d023798abdf939204d057d808cb4eb15566deed6b960adcec
package com.desktopaccountingapi.quickbooksdesktop.services;

import com.desktopaccountingapi.quickbooksdesktop.core.ApiResponse;
import com.desktopaccountingapi.quickbooksdesktop.core.ClientCore;
import com.desktopaccountingapi.quickbooksdesktop.core.OperationSpec;
import com.desktopaccountingapi.quickbooksdesktop.core.Page;
import com.desktopaccountingapi.quickbooksdesktop.core.Pager;
import com.desktopaccountingapi.quickbooksdesktop.core.RequestHandle;
import com.desktopaccountingapi.quickbooksdesktop.core.RequestOptions;
import com.desktopaccountingapi.quickbooksdesktop.models.ItemSite;
import com.desktopaccountingapi.quickbooksdesktop.models.ItemSiteListParams;

/**
 * Operations under {@code client.qbd().itemSites()} (Item sites).
 */
public final class QbdItemSitesService {
    private static final OperationSpec OP_LIST = OperationSpec.of("qbd.itemSites.list", "GET", OperationSpec.END_USER | OperationSpec.SERVER_TIMEOUT | OperationSpec.ASYNC | OperationSpec.QUEUE_TTL);
    private static final OperationSpec OP_RETRIEVE = OperationSpec.of("qbd.itemSites.retrieve", "GET", OperationSpec.END_USER | OperationSpec.SERVER_TIMEOUT | OperationSpec.ASYNC | OperationSpec.QUEUE_TTL);

    private final ClientCore core;
    private final Enqueue enqueue;

    /**
     * Creates the service. Use the client's accessor instead of calling this.
     *
     * @param core the client engine
     */
    public QbdItemSitesService(ClientCore core) {
        this.core = core;
        this.enqueue = new Enqueue();
    }

    /**
     * Async-mode variants of this resource's methods. Each returns a {@link RequestHandle} as soon as the API queued the request.
     *
     * @return the async-mode methods
     */
    public Enqueue enqueue() {
        return enqueue;
    }

    /**
     * List item sites.
     *
     * <p>Returns the item sites that match your filters. Results are paged: pass `nextCursor` as `cursor` until `hasMore` is false. A cursor lives only inside the current QuickBooks session, so request the next page promptly; an expired cursor returns `410 CURSOR_EXPIRED`. See [Pagination](https://www.desktopaccountingapi.com/docs/guides/pagination/).
     *
     * <p>Returns a lazy {@link Pager}: iterate it for every item (each next page is requested when the loop needs it) or call {@code firstPage()}.
     *
     * <p>Runs against the end user's QuickBooks company file (client default end user, {@code forEndUser}, or {@code RequestOptions.endUserId}).
     *
     * <p>{@code GET /v1/quickbooks-desktop/item-sites} (operation {@code qbd.itemSites.list}).
     *
     * @param params the query parameters
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return a lazy pager over {@link ItemSite} items
     */
    public Pager<ItemSite> list(ItemSiteListParams params, RequestOptions options) {
        return core.paginate(OP_LIST, "/v1/quickbooks-desktop/item-sites", params, options, ItemSite::fromJson);
    }

    /**
     * List item sites.
     *
     * <p>{@code GET /v1/quickbooks-desktop/item-sites} (operation {@code qbd.itemSites.list}).
     *
     * @param params the query parameters
     * @return a lazy pager over {@link ItemSite} items
     */
    public Pager<ItemSite> list(ItemSiteListParams params) {
        return list(params, RequestOptions.NONE);
    }

    /**
     * List item sites.
     *
     * <p>{@code GET /v1/quickbooks-desktop/item-sites} (operation {@code qbd.itemSites.list}).
     *
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return a lazy pager over {@link ItemSite} items
     */
    public Pager<ItemSite> list(RequestOptions options) {
        return list(new ItemSiteListParams(), options);
    }

    /**
     * List item sites.
     *
     * <p>{@code GET /v1/quickbooks-desktop/item-sites} (operation {@code qbd.itemSites.list}).
     *
     * @return a lazy pager over {@link ItemSite} items
     */
    public Pager<ItemSite> list() {
        return list(new ItemSiteListParams(), RequestOptions.NONE);
    }

    /**
     * Retrieve an item site.
     *
     * <p>Returns one item site by its QuickBooks ID. An unknown ID returns `404 QBD_OBJECT_NOT_FOUND`.
     *
     * <p>Runs against the end user's QuickBooks company file (client default end user, {@code forEndUser}, or {@code RequestOptions.endUserId}).
     *
     * <p>{@code GET /v1/quickbooks-desktop/item-sites/{id}} (operation {@code qbd.itemSites.retrieve}).
     *
     * @param id QuickBooks ID of the item site.
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link ItemSite}
     */
    public ItemSite retrieve(String id, RequestOptions options) {
        return core.call(OP_RETRIEVE, "/v1/quickbooks-desktop/item-sites/" + ClientCore.pathParam("id", id), null, null, options, ItemSite::fromJson);
    }

    /**
     * Retrieve an item site.
     *
     * <p>{@code GET /v1/quickbooks-desktop/item-sites/{id}} (operation {@code qbd.itemSites.retrieve}).
     *
     * @param id QuickBooks ID of the item site.
     * @return the {@link ItemSite}
     */
    public ItemSite retrieve(String id) {
        return retrieve(id, RequestOptions.NONE);
    }

    /**
     * Retrieve an item site.
     *
     * <p>Returns one item site by its QuickBooks ID. An unknown ID returns `404 QBD_OBJECT_NOT_FOUND`.
     *
     * <p>Like {@code retrieve(...)}, but also returns the HTTP status and headers ({@code Daapi-Request-Id}, {@code Daapi-Warnings}).
     *
     * <p>{@code GET /v1/quickbooks-desktop/item-sites/{id}} (operation {@code qbd.itemSites.retrieve}).
     *
     * @param id QuickBooks ID of the item site.
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link ItemSite} with HTTP status and headers
     */
    public ApiResponse<ItemSite> retrieveWithResponse(String id, RequestOptions options) {
        return core.callWithResponse(OP_RETRIEVE, "/v1/quickbooks-desktop/item-sites/" + ClientCore.pathParam("id", id), null, null, options, ItemSite::fromJson);
    }

    /**
     * Retrieve an item site.
     *
     * <p>{@code GET /v1/quickbooks-desktop/item-sites/{id}} (operation {@code qbd.itemSites.retrieve}).
     *
     * @param id QuickBooks ID of the item site.
     * @return the {@link ItemSite} with HTTP status and headers
     */
    public ApiResponse<ItemSite> retrieveWithResponse(String id) {
        return retrieveWithResponse(id, RequestOptions.NONE);
    }

    /**
     * Async-mode ({@code Prefer: respond-async}) variants of the methods of {@link QbdItemSitesService}.
     */
    public final class Enqueue {
        private Enqueue() {}

        /**
         * List item sites.
         *
         * <p>Returns the item sites that match your filters. Results are paged: pass `nextCursor` as `cursor` until `hasMore` is false. A cursor lives only inside the current QuickBooks session, so request the next page promptly; an expired cursor returns `410 CURSOR_EXPIRED`. See [Pagination](https://www.desktopaccountingapi.com/docs/guides/pagination/).
         *
         * <p>Async mode: sends {@code Prefer: respond-async} and returns as soon as the API queued the request ({@code 202}). Use the handle's {@code await()} or {@code result()} to get the outcome.
         *
         * <p>{@code GET /v1/quickbooks-desktop/item-sites} (operation {@code qbd.itemSites.list}).
         *
         * @param params the query parameters
         * @param options per-call options (end user, idempotency key, timeouts, retries)
         * @return a handle on the queued request
         */
        public RequestHandle<Page<ItemSite>> list(ItemSiteListParams params, RequestOptions options) {
            return core.enqueue(OP_LIST, "/v1/quickbooks-desktop/item-sites", params, null, options, Page.parser(ItemSite::fromJson));
        }

        /**
         * List item sites.
         *
         * <p>{@code GET /v1/quickbooks-desktop/item-sites} (operation {@code qbd.itemSites.list}).
         *
         * @param params the query parameters
         * @return a handle on the queued request
         */
        public RequestHandle<Page<ItemSite>> list(ItemSiteListParams params) {
            return list(params, RequestOptions.NONE);
        }

        /**
         * List item sites.
         *
         * <p>{@code GET /v1/quickbooks-desktop/item-sites} (operation {@code qbd.itemSites.list}).
         *
         * @param options per-call options (end user, idempotency key, timeouts, retries)
         * @return a handle on the queued request
         */
        public RequestHandle<Page<ItemSite>> list(RequestOptions options) {
            return list(new ItemSiteListParams(), options);
        }

        /**
         * List item sites.
         *
         * <p>{@code GET /v1/quickbooks-desktop/item-sites} (operation {@code qbd.itemSites.list}).
         *
         * @return a handle on the queued request
         */
        public RequestHandle<Page<ItemSite>> list() {
            return list(new ItemSiteListParams(), RequestOptions.NONE);
        }

        /**
         * Retrieve an item site.
         *
         * <p>Returns one item site by its QuickBooks ID. An unknown ID returns `404 QBD_OBJECT_NOT_FOUND`.
         *
         * <p>Async mode: sends {@code Prefer: respond-async} and returns as soon as the API queued the request ({@code 202}). Use the handle's {@code await()} or {@code result()} to get the outcome.
         *
         * <p>{@code GET /v1/quickbooks-desktop/item-sites/{id}} (operation {@code qbd.itemSites.retrieve}).
         *
         * @param id QuickBooks ID of the item site.
         * @param options per-call options (end user, idempotency key, timeouts, retries)
         * @return a handle on the queued request
         */
        public RequestHandle<ItemSite> retrieve(String id, RequestOptions options) {
            return core.enqueue(OP_RETRIEVE, "/v1/quickbooks-desktop/item-sites/" + ClientCore.pathParam("id", id), null, null, options, ItemSite::fromJson);
        }

        /**
         * Retrieve an item site.
         *
         * <p>{@code GET /v1/quickbooks-desktop/item-sites/{id}} (operation {@code qbd.itemSites.retrieve}).
         *
         * @param id QuickBooks ID of the item site.
         * @return a handle on the queued request
         */
        public RequestHandle<ItemSite> retrieve(String id) {
            return retrieve(id, RequestOptions.NONE);
        }
    }
}
