// Code generated by packages/sdk-generator. DO NOT EDIT.
// Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:09aa9517f466027d023798abdf939204d057d808cb4eb15566deed6b960adcec
package com.desktopaccountingapi.quickbooksdesktop.services;

import com.desktopaccountingapi.quickbooksdesktop.core.ApiResponse;
import com.desktopaccountingapi.quickbooksdesktop.core.ClientCore;
import com.desktopaccountingapi.quickbooksdesktop.core.OperationSpec;
import com.desktopaccountingapi.quickbooksdesktop.core.RequestHandle;
import com.desktopaccountingapi.quickbooksdesktop.core.RequestOptions;
import com.desktopaccountingapi.quickbooksdesktop.models.PriceLevel;
import com.desktopaccountingapi.quickbooksdesktop.models.PriceLevelCreateInput;
import com.desktopaccountingapi.quickbooksdesktop.models.PriceLevelList;
import com.desktopaccountingapi.quickbooksdesktop.models.PriceLevelListParams;
import com.desktopaccountingapi.quickbooksdesktop.models.PriceLevelUpdateInput;

/**
 * Operations under {@code client.qbd().priceLevels()} (Price levels).
 */
public final class QbdPriceLevelsService {
    private static final OperationSpec OP_CREATE = OperationSpec.of("qbd.priceLevels.create", "POST", OperationSpec.WRITE | OperationSpec.END_USER | OperationSpec.SERVER_TIMEOUT | OperationSpec.ASYNC | OperationSpec.QUEUE_TTL);
    private static final OperationSpec OP_LIST = OperationSpec.of("qbd.priceLevels.list", "GET", OperationSpec.END_USER | OperationSpec.SERVER_TIMEOUT | OperationSpec.ASYNC | OperationSpec.QUEUE_TTL);
    private static final OperationSpec OP_RETRIEVE = OperationSpec.of("qbd.priceLevels.retrieve", "GET", OperationSpec.END_USER | OperationSpec.SERVER_TIMEOUT | OperationSpec.ASYNC | OperationSpec.QUEUE_TTL);
    private static final OperationSpec OP_UPDATE = OperationSpec.of("qbd.priceLevels.update", "POST", OperationSpec.WRITE | OperationSpec.END_USER | OperationSpec.SERVER_TIMEOUT | OperationSpec.ASYNC | OperationSpec.QUEUE_TTL);

    private final ClientCore core;
    private final Enqueue enqueue;

    /**
     * Creates the service. Use the client's accessor instead of calling this.
     *
     * @param core the client engine
     */
    public QbdPriceLevelsService(ClientCore core) {
        this.core = core;
        this.enqueue = new Enqueue();
    }

    /**
     * Async-mode variants of this resource's methods. Each returns a {@link RequestHandle} as soon as the API queued the request.
     *
     * @return the async-mode methods
     */
    public Enqueue enqueue() {
        return enqueue;
    }

    /**
     * Create a price level.
     *
     * <p>Creates a price level in QuickBooks Desktop and returns it. Send an `Idempotency-Key` header so a retry after a network error never creates a second price level (the SDKs do this for you). See [Idempotency and safe retries](https://www.desktopaccountingapi.com/docs/guides/idempotency/).
     *
     * <p>A write: the SDK sends an {@code Idempotency-Key} (yours, or a UUID generated once per call) and reuses it on every retry.
     *
     * <p>Runs against the end user's QuickBooks company file (client default end user, {@code forEndUser}, or {@code RequestOptions.endUserId}).
     *
     * <p>{@code POST /v1/quickbooks-desktop/price-levels} (operation {@code qbd.priceLevels.create}).
     *
     * @param params the request body
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link PriceLevel}
     */
    public PriceLevel create(PriceLevelCreateInput params, RequestOptions options) {
        return core.call(OP_CREATE, "/v1/quickbooks-desktop/price-levels", null, params, options, PriceLevel::fromJson);
    }

    /**
     * Create a price level.
     *
     * <p>{@code POST /v1/quickbooks-desktop/price-levels} (operation {@code qbd.priceLevels.create}).
     *
     * @param params the request body
     * @return the {@link PriceLevel}
     */
    public PriceLevel create(PriceLevelCreateInput params) {
        return create(params, RequestOptions.NONE);
    }

    /**
     * Create a price level.
     *
     * <p>Creates a price level in QuickBooks Desktop and returns it. Send an `Idempotency-Key` header so a retry after a network error never creates a second price level (the SDKs do this for you). See [Idempotency and safe retries](https://www.desktopaccountingapi.com/docs/guides/idempotency/).
     *
     * <p>Like {@code create(...)}, but also returns the HTTP status and headers ({@code Daapi-Request-Id}, {@code Daapi-Warnings}).
     *
     * <p>{@code POST /v1/quickbooks-desktop/price-levels} (operation {@code qbd.priceLevels.create}).
     *
     * @param params the request body
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link PriceLevel} with HTTP status and headers
     */
    public ApiResponse<PriceLevel> createWithResponse(PriceLevelCreateInput params, RequestOptions options) {
        return core.callWithResponse(OP_CREATE, "/v1/quickbooks-desktop/price-levels", null, params, options, PriceLevel::fromJson);
    }

    /**
     * Create a price level.
     *
     * <p>{@code POST /v1/quickbooks-desktop/price-levels} (operation {@code qbd.priceLevels.create}).
     *
     * @param params the request body
     * @return the {@link PriceLevel} with HTTP status and headers
     */
    public ApiResponse<PriceLevel> createWithResponse(PriceLevelCreateInput params) {
        return createWithResponse(params, RequestOptions.NONE);
    }

    /**
     * List price levels.
     *
     * <p>Returns the price levels that match your filters. QuickBooks has no cursor for this list, so the response contains every matching price level at once.
     *
     * <p>Runs against the end user's QuickBooks company file (client default end user, {@code forEndUser}, or {@code RequestOptions.endUserId}).
     *
     * <p>{@code GET /v1/quickbooks-desktop/price-levels} (operation {@code qbd.priceLevels.list}).
     *
     * @param params the query parameters
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link PriceLevelList}
     */
    public PriceLevelList list(PriceLevelListParams params, RequestOptions options) {
        return core.call(OP_LIST, "/v1/quickbooks-desktop/price-levels", params, null, options, PriceLevelList::fromJson);
    }

    /**
     * List price levels.
     *
     * <p>{@code GET /v1/quickbooks-desktop/price-levels} (operation {@code qbd.priceLevels.list}).
     *
     * @param params the query parameters
     * @return the {@link PriceLevelList}
     */
    public PriceLevelList list(PriceLevelListParams params) {
        return list(params, RequestOptions.NONE);
    }

    /**
     * List price levels.
     *
     * <p>{@code GET /v1/quickbooks-desktop/price-levels} (operation {@code qbd.priceLevels.list}).
     *
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link PriceLevelList}
     */
    public PriceLevelList list(RequestOptions options) {
        return list(new PriceLevelListParams(), options);
    }

    /**
     * List price levels.
     *
     * <p>{@code GET /v1/quickbooks-desktop/price-levels} (operation {@code qbd.priceLevels.list}).
     *
     * @return the {@link PriceLevelList}
     */
    public PriceLevelList list() {
        return list(new PriceLevelListParams(), RequestOptions.NONE);
    }

    /**
     * List price levels.
     *
     * <p>Returns the price levels that match your filters. QuickBooks has no cursor for this list, so the response contains every matching price level at once.
     *
     * <p>Like {@code list(...)}, but also returns the HTTP status and headers ({@code Daapi-Request-Id}, {@code Daapi-Warnings}).
     *
     * <p>{@code GET /v1/quickbooks-desktop/price-levels} (operation {@code qbd.priceLevels.list}).
     *
     * @param params the query parameters
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link PriceLevelList} with HTTP status and headers
     */
    public ApiResponse<PriceLevelList> listWithResponse(PriceLevelListParams params, RequestOptions options) {
        return core.callWithResponse(OP_LIST, "/v1/quickbooks-desktop/price-levels", params, null, options, PriceLevelList::fromJson);
    }

    /**
     * List price levels.
     *
     * <p>{@code GET /v1/quickbooks-desktop/price-levels} (operation {@code qbd.priceLevels.list}).
     *
     * @param params the query parameters
     * @return the {@link PriceLevelList} with HTTP status and headers
     */
    public ApiResponse<PriceLevelList> listWithResponse(PriceLevelListParams params) {
        return listWithResponse(params, RequestOptions.NONE);
    }

    /**
     * List price levels.
     *
     * <p>{@code GET /v1/quickbooks-desktop/price-levels} (operation {@code qbd.priceLevels.list}).
     *
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link PriceLevelList} with HTTP status and headers
     */
    public ApiResponse<PriceLevelList> listWithResponse(RequestOptions options) {
        return listWithResponse(new PriceLevelListParams(), options);
    }

    /**
     * List price levels.
     *
     * <p>{@code GET /v1/quickbooks-desktop/price-levels} (operation {@code qbd.priceLevels.list}).
     *
     * @return the {@link PriceLevelList} with HTTP status and headers
     */
    public ApiResponse<PriceLevelList> listWithResponse() {
        return listWithResponse(new PriceLevelListParams(), RequestOptions.NONE);
    }

    /**
     * Retrieve a price level.
     *
     * <p>Returns one price level by its QuickBooks ID. An unknown ID returns `404 QBD_OBJECT_NOT_FOUND`.
     *
     * <p>Runs against the end user's QuickBooks company file (client default end user, {@code forEndUser}, or {@code RequestOptions.endUserId}).
     *
     * <p>{@code GET /v1/quickbooks-desktop/price-levels/{id}} (operation {@code qbd.priceLevels.retrieve}).
     *
     * @param id QuickBooks ID of the price level.
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link PriceLevel}
     */
    public PriceLevel retrieve(String id, RequestOptions options) {
        return core.call(OP_RETRIEVE, "/v1/quickbooks-desktop/price-levels/" + ClientCore.pathParam("id", id), null, null, options, PriceLevel::fromJson);
    }

    /**
     * Retrieve a price level.
     *
     * <p>{@code GET /v1/quickbooks-desktop/price-levels/{id}} (operation {@code qbd.priceLevels.retrieve}).
     *
     * @param id QuickBooks ID of the price level.
     * @return the {@link PriceLevel}
     */
    public PriceLevel retrieve(String id) {
        return retrieve(id, RequestOptions.NONE);
    }

    /**
     * Retrieve a price level.
     *
     * <p>Returns one price level by its QuickBooks ID. An unknown ID returns `404 QBD_OBJECT_NOT_FOUND`.
     *
     * <p>Like {@code retrieve(...)}, but also returns the HTTP status and headers ({@code Daapi-Request-Id}, {@code Daapi-Warnings}).
     *
     * <p>{@code GET /v1/quickbooks-desktop/price-levels/{id}} (operation {@code qbd.priceLevels.retrieve}).
     *
     * @param id QuickBooks ID of the price level.
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link PriceLevel} with HTTP status and headers
     */
    public ApiResponse<PriceLevel> retrieveWithResponse(String id, RequestOptions options) {
        return core.callWithResponse(OP_RETRIEVE, "/v1/quickbooks-desktop/price-levels/" + ClientCore.pathParam("id", id), null, null, options, PriceLevel::fromJson);
    }

    /**
     * Retrieve a price level.
     *
     * <p>{@code GET /v1/quickbooks-desktop/price-levels/{id}} (operation {@code qbd.priceLevels.retrieve}).
     *
     * @param id QuickBooks ID of the price level.
     * @return the {@link PriceLevel} with HTTP status and headers
     */
    public ApiResponse<PriceLevel> retrieveWithResponse(String id) {
        return retrieveWithResponse(id, RequestOptions.NONE);
    }

    /**
     * Update a price level.
     *
     * <p>Changes the fields you send on an existing price level and leaves omitted fields unchanged. Requires the current `revisionNumber`. A stale `revisionNumber` returns `409 QBD_REVISION_NUMBER_STALE`: retrieve the price level, reapply your change and send the new revision. See [Updates and line items](https://www.desktopaccountingapi.com/docs/quickbooks/updates-and-line-items/).
     *
     * <p>A write: the SDK sends an {@code Idempotency-Key} (yours, or a UUID generated once per call) and reuses it on every retry.
     *
     * <p>Runs against the end user's QuickBooks company file (client default end user, {@code forEndUser}, or {@code RequestOptions.endUserId}).
     *
     * <p>{@code POST /v1/quickbooks-desktop/price-levels/{id}} (operation {@code qbd.priceLevels.update}).
     *
     * @param id QuickBooks ID of the price level.
     * @param params the request body
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link PriceLevel}
     */
    public PriceLevel update(String id, PriceLevelUpdateInput params, RequestOptions options) {
        return core.call(OP_UPDATE, "/v1/quickbooks-desktop/price-levels/" + ClientCore.pathParam("id", id), null, params, options, PriceLevel::fromJson);
    }

    /**
     * Update a price level.
     *
     * <p>{@code POST /v1/quickbooks-desktop/price-levels/{id}} (operation {@code qbd.priceLevels.update}).
     *
     * @param id QuickBooks ID of the price level.
     * @param params the request body
     * @return the {@link PriceLevel}
     */
    public PriceLevel update(String id, PriceLevelUpdateInput params) {
        return update(id, params, RequestOptions.NONE);
    }

    /**
     * Update a price level.
     *
     * <p>Changes the fields you send on an existing price level and leaves omitted fields unchanged. Requires the current `revisionNumber`. A stale `revisionNumber` returns `409 QBD_REVISION_NUMBER_STALE`: retrieve the price level, reapply your change and send the new revision. See [Updates and line items](https://www.desktopaccountingapi.com/docs/quickbooks/updates-and-line-items/).
     *
     * <p>Like {@code update(...)}, but also returns the HTTP status and headers ({@code Daapi-Request-Id}, {@code Daapi-Warnings}).
     *
     * <p>{@code POST /v1/quickbooks-desktop/price-levels/{id}} (operation {@code qbd.priceLevels.update}).
     *
     * @param id QuickBooks ID of the price level.
     * @param params the request body
     * @param options per-call options (end user, idempotency key, timeouts, retries)
     * @return the {@link PriceLevel} with HTTP status and headers
     */
    public ApiResponse<PriceLevel> updateWithResponse(String id, PriceLevelUpdateInput params, RequestOptions options) {
        return core.callWithResponse(OP_UPDATE, "/v1/quickbooks-desktop/price-levels/" + ClientCore.pathParam("id", id), null, params, options, PriceLevel::fromJson);
    }

    /**
     * Update a price level.
     *
     * <p>{@code POST /v1/quickbooks-desktop/price-levels/{id}} (operation {@code qbd.priceLevels.update}).
     *
     * @param id QuickBooks ID of the price level.
     * @param params the request body
     * @return the {@link PriceLevel} with HTTP status and headers
     */
    public ApiResponse<PriceLevel> updateWithResponse(String id, PriceLevelUpdateInput params) {
        return updateWithResponse(id, params, RequestOptions.NONE);
    }

    /**
     * Async-mode ({@code Prefer: respond-async}) variants of the methods of {@link QbdPriceLevelsService}.
     */
    public final class Enqueue {
        private Enqueue() {}

        /**
         * Create a price level.
         *
         * <p>Creates a price level in QuickBooks Desktop and returns it. Send an `Idempotency-Key` header so a retry after a network error never creates a second price level (the SDKs do this for you). See [Idempotency and safe retries](https://www.desktopaccountingapi.com/docs/guides/idempotency/).
         *
         * <p>Async mode: sends {@code Prefer: respond-async} and returns as soon as the API queued the request ({@code 202}). Use the handle's {@code await()} or {@code result()} to get the outcome.
         *
         * <p>{@code POST /v1/quickbooks-desktop/price-levels} (operation {@code qbd.priceLevels.create}).
         *
         * @param params the request body
         * @param options per-call options (end user, idempotency key, timeouts, retries)
         * @return a handle on the queued request
         */
        public RequestHandle<PriceLevel> create(PriceLevelCreateInput params, RequestOptions options) {
            return core.enqueue(OP_CREATE, "/v1/quickbooks-desktop/price-levels", null, params, options, PriceLevel::fromJson);
        }

        /**
         * Create a price level.
         *
         * <p>{@code POST /v1/quickbooks-desktop/price-levels} (operation {@code qbd.priceLevels.create}).
         *
         * @param params the request body
         * @return a handle on the queued request
         */
        public RequestHandle<PriceLevel> create(PriceLevelCreateInput params) {
            return create(params, RequestOptions.NONE);
        }

        /**
         * List price levels.
         *
         * <p>Returns the price levels that match your filters. QuickBooks has no cursor for this list, so the response contains every matching price level at once.
         *
         * <p>Async mode: sends {@code Prefer: respond-async} and returns as soon as the API queued the request ({@code 202}). Use the handle's {@code await()} or {@code result()} to get the outcome.
         *
         * <p>{@code GET /v1/quickbooks-desktop/price-levels} (operation {@code qbd.priceLevels.list}).
         *
         * @param params the query parameters
         * @param options per-call options (end user, idempotency key, timeouts, retries)
         * @return a handle on the queued request
         */
        public RequestHandle<PriceLevelList> list(PriceLevelListParams params, RequestOptions options) {
            return core.enqueue(OP_LIST, "/v1/quickbooks-desktop/price-levels", params, null, options, PriceLevelList::fromJson);
        }

        /**
         * List price levels.
         *
         * <p>{@code GET /v1/quickbooks-desktop/price-levels} (operation {@code qbd.priceLevels.list}).
         *
         * @param params the query parameters
         * @return a handle on the queued request
         */
        public RequestHandle<PriceLevelList> list(PriceLevelListParams params) {
            return list(params, RequestOptions.NONE);
        }

        /**
         * List price levels.
         *
         * <p>{@code GET /v1/quickbooks-desktop/price-levels} (operation {@code qbd.priceLevels.list}).
         *
         * @param options per-call options (end user, idempotency key, timeouts, retries)
         * @return a handle on the queued request
         */
        public RequestHandle<PriceLevelList> list(RequestOptions options) {
            return list(new PriceLevelListParams(), options);
        }

        /**
         * List price levels.
         *
         * <p>{@code GET /v1/quickbooks-desktop/price-levels} (operation {@code qbd.priceLevels.list}).
         *
         * @return a handle on the queued request
         */
        public RequestHandle<PriceLevelList> list() {
            return list(new PriceLevelListParams(), RequestOptions.NONE);
        }

        /**
         * Retrieve a price level.
         *
         * <p>Returns one price level by its QuickBooks ID. An unknown ID returns `404 QBD_OBJECT_NOT_FOUND`.
         *
         * <p>Async mode: sends {@code Prefer: respond-async} and returns as soon as the API queued the request ({@code 202}). Use the handle's {@code await()} or {@code result()} to get the outcome.
         *
         * <p>{@code GET /v1/quickbooks-desktop/price-levels/{id}} (operation {@code qbd.priceLevels.retrieve}).
         *
         * @param id QuickBooks ID of the price level.
         * @param options per-call options (end user, idempotency key, timeouts, retries)
         * @return a handle on the queued request
         */
        public RequestHandle<PriceLevel> retrieve(String id, RequestOptions options) {
            return core.enqueue(OP_RETRIEVE, "/v1/quickbooks-desktop/price-levels/" + ClientCore.pathParam("id", id), null, null, options, PriceLevel::fromJson);
        }

        /**
         * Retrieve a price level.
         *
         * <p>{@code GET /v1/quickbooks-desktop/price-levels/{id}} (operation {@code qbd.priceLevels.retrieve}).
         *
         * @param id QuickBooks ID of the price level.
         * @return a handle on the queued request
         */
        public RequestHandle<PriceLevel> retrieve(String id) {
            return retrieve(id, RequestOptions.NONE);
        }

        /**
         * Update a price level.
         *
         * <p>Changes the fields you send on an existing price level and leaves omitted fields unchanged. Requires the current `revisionNumber`. A stale `revisionNumber` returns `409 QBD_REVISION_NUMBER_STALE`: retrieve the price level, reapply your change and send the new revision. See [Updates and line items](https://www.desktopaccountingapi.com/docs/quickbooks/updates-and-line-items/).
         *
         * <p>Async mode: sends {@code Prefer: respond-async} and returns as soon as the API queued the request ({@code 202}). Use the handle's {@code await()} or {@code result()} to get the outcome.
         *
         * <p>{@code POST /v1/quickbooks-desktop/price-levels/{id}} (operation {@code qbd.priceLevels.update}).
         *
         * @param id QuickBooks ID of the price level.
         * @param params the request body
         * @param options per-call options (end user, idempotency key, timeouts, retries)
         * @return a handle on the queued request
         */
        public RequestHandle<PriceLevel> update(String id, PriceLevelUpdateInput params, RequestOptions options) {
            return core.enqueue(OP_UPDATE, "/v1/quickbooks-desktop/price-levels/" + ClientCore.pathParam("id", id), null, params, options, PriceLevel::fromJson);
        }

        /**
         * Update a price level.
         *
         * <p>{@code POST /v1/quickbooks-desktop/price-levels/{id}} (operation {@code qbd.priceLevels.update}).
         *
         * @param id QuickBooks ID of the price level.
         * @param params the request body
         * @return a handle on the queued request
         */
        public RequestHandle<PriceLevel> update(String id, PriceLevelUpdateInput params) {
            return update(id, params, RequestOptions.NONE);
        }
    }
}
